### ISSUE TITLE
tinyproxy_cv_regex_broken test breaks crosscompile

### ISSUE THREAD

**Issue by rofl0r** [tinyproxy/tinyproxy#1]
```
checking whether the system's regex library is broken... yes
configure: error: Your system's regexec() function is broken.
```
in configure:
```
if test "$cross_compiling" = yes; then :
tinyproxy_cv_regex_broken=yes
```
solution: assume tinyproxy_cv_regex_broken=no for crosscompiles since its pretty unlikely

**Comment by obnoxxx** [comment]
Not sure about cross-compiling.
The above line from configure is not in tinyproxy's code. It seems to come from automake.

Could you try what happens if you run ./autogen.sh in your cross-compile environment before running configure/make ?

**Comment by obnoxxx** [comment]
a workaround especially for this purpose is:

   `./configure --disable-regexcheck ...`
