### ISSUE TITLE
Listen for more then one port

### ISSUE THREAD

**Issue by YoyoKarimov** [tinyproxy/tinyproxy#102]
How can I use several ports which tinyproxy will listen on.
In othe words how to create several proxy: xxx.xxx.xxx.xxx:8888 and xxx.xxx.xxx.xxx:9999

**Comment by rofl0r** [comment]
https://github.com/troglobit/redir

**Comment by rofl0r** [comment]
you can also use several instances of tinyproxy, using different config files. HTH.
