### ISSUE TITLE
remote monitoring

### ISSUE THREAD

**Issue by xxllp** [tinyproxy/tinyproxy#104]
how I can monitor

**Comment by nickivanov** [comment]
From `man 8 tinyproxy`:

> STATHOST
> --------
> 
> Tinyproxy returns a HTML page with connection statistics when it
> receives a HTTP request for a certain host -- the stathost.  The
> stathost name defaults to `TINYPROXY_STATHOST` and can be changed at
> runtime to any name or IP address with the configuration variable
> `StatHost`.
> 
> The stat file template can be changed at runtime through the
> configuration variable `StatFile`.
