### ISSUE TITLE
MinSpareServers and creating more than one child, if less then

### ISSUE THREAD

**Issue by metalurgus** [tinyproxy/tinyproxy#107]
I'm trying to use TinyProxy under quite high load. 
I use following settings:

```
MinSpareServers 1000
MaxSpareServers 3000
StartServers 3000
```

In some time I start getting logs like following:    

```
NOTICE    Jul 29 13:41:54 [11116]: Waiting servers (953) is less than MinSpareServers (1000). Creating new child.
NOTICE    Jul 29 13:41:59 [11116]: Waiting servers (938) is less than MinSpareServers (1000). Creating new child.
NOTICE    Jul 29 13:42:04 [11116]: Waiting servers (900) is less than MinSpareServers (1000). Creating new child.
```

If I'm right, this means that TinyProxy is creating new child processes not fast enough. 
If above is right, then is there way to tell it to create more than one child process when he lacks free processes? It themes that it creates 1 child process once spare processes count reduces below MinSpareServers, but I would like it to create `MinSpareServers - CurrentServers` child processes in this case. Is it possible to achieve?

**Comment by rofl0r** [comment]
the code creating child processes apparently does so only up to child_config.maxclients processes. (see src/child.c around line 485)
what is your value for maxclients ? if it's 3000 like your MaxSpareServers, it's probably just that you have > 2000 connections at that point.

**Comment by metalurgus** [comment]
@rofl0r thanks for quick response
`MaxClients 100000` is my MaxClients line. 
I thought that it creates only one child per check because I monitor the `top` command, and total processes count increases only by 1 whenever it loggs that line

**Comment by rofl0r** [comment]
so, is process count close to 10K when it happens ?

**Comment by metalurgus** [comment]
@rofl0r If I'm right, because of [https://github.com/tinyproxy/tinyproxy/blob/master/src/child.c#L500](this) `break`, it will create only 1 child. Am I wrong?

**Comment by metalurgus** [comment]
@rofl0r 

> close to 10K
no, alittle more than 3000

**Comment by rofl0r** [comment]
oh indeed, it seems i overlooked that break. maybe remove it, and change loop condition...

**Comment by metalurgus** [comment]
@rofl0r ok, I'll try to understand how to build it from sources, and create a pool request after that

**Comment by metalurgus** [comment]
I've done the changes that should solve the problem in code, but I theme to fail building it because it is my first linux application to be built from sources.

**Comment by rofl0r** [comment]
```
sh autogen.sh
./configure
make
```
should do the job. you need build-essentials, make, and autoconf/automake installed

**Comment by metalurgus** [comment]
@rofl0r themes like it worked except the documentation, which failed to build. where do I find the binaries now? I've run `make install` too, but Im not sure if it worked. I can run `service tinyproxy start` after that (even if I have uninstalled tinyproxy through `sudo apt-get remove tinyproxy`), and it is starting, but I can't find the log file in the usual location (var/log.tinyproxy)

**Comment by rofl0r** [comment]
you can `make DESTDIR=foo install` and everything will be installed into a directory structure in foo (you can start the binary directly from there).

**Comment by metalurgus** [comment]
I was unable to accomplish this. Also I don't see a reason to create a pull request to fix this issue, as the last commit was 2 month ago, and my pull request won't be merged soon, and new version of tinyproxy is not going to come to ubuntu repository soon as well, since there is 1.8.3 only available at the repo currently

**Comment by rofl0r** [comment]
well, even if your PR was not merged at all, it would still at least document that what you want is possible and how it can be achieved, so people not afraid of building from source can patch it themselfes.

**Comment by tomeichi** [comment]
Excuse me.
I also had a hard time increasing SpareServer every 5 seconds, so I deleted [break](https://github.com/tinyproxy/tinyproxy/blob/master/src/child.c#L500), added some logs and rpmbuild it for my environment (CentOS 6).
As a result, it seems that "segfault" has occurred and it stops in the middle of the loop of child_config.maxclients.

> segfault at 0 ip 0000003b16a8ac9a sp 00007ffc9552c1a8 error 4 in libc-2.12.so[3b16a00000+18a000]

If you have a solution please tell us.

**Comment by rofl0r** [comment]
obsoleted since b935dc85c3fca51de8e131d6aa2047f8a0404f0c
