### ISSUE TITLE
 How can I open more than one port

### ISSUE THREAD

**Issue by SerhatOcal** [tinyproxy/tinyproxy#109]
hi,
How can I open and run multiple ports over a rope.for example  xxx.xxx.xxx:3210 xxx.xxx.xxx:3211 xxx.xxx.xxx.3212 

this https://github.com/troglobit/redir I do not know how to use it.

I'm waiting for your help

**Comment by rofl0r** [comment]
you make tinyproxy listen on 3210 and then redirect port 3211 to 3210 with `redir`...

**Comment by SerhatOcal** [comment]
How can I do that please give me a sample.Help me
