### ISSUE TITLE
Tinyproxy segfault everyday at about 00:00

### ISSUE THREAD

**Issue by pengqi** [tinyproxy/tinyproxy#110]
Here is the syslog trace:

_segfault at 7ffc984e3ff8 ip 00007f51b1a3f8f9 sp 00007ffc984e4000 error 6 in libc-2.19.so[7f51b1a02000+1ba000]
segfault at 7ffc984e3ff0 ip 00007f51b1a3f907 sp 00007ffc984e3ff0 error 6 in libc-2.19.so[7f51b1a02000+1ba000]
segfault at 7ffc984e3ff0 ip 00007f51b1a3f907 sp 00007ffc984e3ff0 error 6 in libc-2.19.so[7f51b1a02000+1ba000]_

This happend everyday. The OS is Ubuntu 14.04.4.

I also found a similar situation as me here >>> https://bugs.launchpad.net/ubuntu/+source/tinyproxy/+bug/625751

**Comment by rofl0r** [comment]
how is tinyproxy started ? if it is run from some service supervisor, that supervisor is probably doing something unexpected behind tinyproxy's back. try to run tinyproxy with gdb from the command line, so if it crashes, you can print a backtrace:
`gdb --args tinyproxy --foo --bar`

**Comment by rofl0r** [comment]
also: try current git as a similar issue related to logrotate has been recently fixed...
