### ISSUE TITLE
Problem with the  ussage of tiny proxy

### ISSUE THREAD

**Issue by achernar72** [tinyproxy/tinyproxy#119]
HI, 
I would like to know how tiny proxy works and how to check it is running or not.

**Comment by PigNatovsky** [comment]
If You' re using systemd, the easiest way is: `systemctl status tinyproxy`.

**Comment by rofl0r** [comment]
you can also use `pgrep tinyproxy`. if it shows any resulting numbers (pids), then tinyproxy is running in the background. feel free to open a new issue if there are further questions.
