### ISSUE TITLE
Default binding to all interfaces only using IPv6 on FreeBSD

### ISSUE THREAD

**Issue by jasonemann** [tinyproxy/tinyproxy#12]
When tinyproxy has no Listen directive declared in the configuration, it defaults to binding to all interfaces, but only does so using IPv6 on FreeBSD (10.2-RELEASE in this case):

    # netstat -an | grep 8888 | grep LISTEN
    tcp6       0      0 *.8888                 *.*                    LISTEN

As the Listen directive can be specified only once with a single IP address, there is no way to make tinyproxy listen on all interfaces using IPv4.

As a suggestion, could the Listen directive be modified to permit specifying a list of multiple IP address, both v4 and v6?

**Comment by obnoxxx** [comment]
In Tinyproxy, 1.8.4, the Listen handling has been fixed to listen on ipv4 and ipv6 default if no listen is given, and also to allow to specify multiple Listen statements in the config. Please try tinyproxy 1.8.4 and reopen this issue if problems persist.

Thanks for using tinyproxy!

**Comment by jasonemann** [comment]
Apologies for failing to check the FreeBSD port version (1.8.3) against the 1.8 branch.  Will submit a bug to the port maintainer instead.

**Comment by obnoxxx** [comment]
No need to apologize. Let me know how it goes on FreeBSD!
