### ISSUE TITLE
Can I use tinyproxy as a C lib to monitor, edit, and simulate incoming and outgoing requests? (Secure)

### ISSUE THREAD

**Issue by TsundereBug** [tinyproxy/tinyproxy#124]
I want to build a layer on a proxy that allows me to edit incoming and outgoing requests, and not invalidate HTTPS. I would use mitmproxy but it can't be used as a C lib. Can tinyproxy allow me to do this?

**Comment by rofl0r** [comment]
theoretically yes, but it would need a great deal of code changes from your side - it is currently not a library, and it would several other changes.

**Comment by TsundereBug** [comment]
😔 alrighty
