### ISSUE TITLE
Uninstallation of tinyproxy leaves its user account

### ISSUE THREAD

**Issue by TuulaP** [tinyproxy/tinyproxy#126]
Hi, installed and eventually also uninstalled tinyproxy on Centos7 couple of days ago with 

`sudo yum remove tinyproxy`

what we noticed afterwards, was that the user tinyproxy was still left to the machine. I think it could have been removed alongside the software.  (Unless there is some safety feature to leave the user account just in case it would have been used for something else, too).

**Comment by rofl0r** [comment]
this is an issue of the yum package manager. you should report it to centos bugtracker.
