### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by Einsgate** [tinyproxy/tinyproxy#127]
I am a green hand on network programming. Here I have a question about the code in child_main()(src/child.c), line 234 (commit e9e0f0b)

> ret = select(maxfd + 1, &rfds, NULL, NULL, NULL);

The select() would change the rfds into the subset of the original one, so next time the select() will take the subset as the argument. I wonder why not reset the rfds before select() for every single loop or it is reset somewhere I didn't find.

**Comment by rofl0r** [comment]
maybe the loop is entered only once... but you're right that in case it is meant to be executed more than once, the code should probably call FD_CLR on the set with the found fd.

**Comment by TimWolla** [comment]
see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898492
