### ISSUE TITLE
provide official image at docker hub

### ISSUE THREAD

**Issue by davidkarlsen** [tinyproxy/tinyproxy#128]
It would be great to have an official image at docker hub for tinyproxy.
WDYT?

**Comment by rofl0r** [comment]
point of it being ? tinyproxy is a < 100 kb executable, putting it into a docker image would make it like a min 30 MB program install.

**Comment by davidkarlsen** [comment]
For ease of use - the way I intend to run tinyproxy is through docker - and I guess there are several others doing that - a bit like apache offers httpd: https://hub.docker.com/_/httpd/ - today everybody needs to roll their own.

**Comment by rofl0r** [comment]
sorry, but this is outside the scope of what i'm willing to maintain.
