### ISSUE TITLE
Encryption of the traffic

### ISSUE THREAD

**Issue by slrslr** [tinyproxy/tinyproxy#13]
Hello,

im currently using socks 5 SSH proxy according to [this tutorial](https://internetlifeforum.com/linux-forums/1326-quick-way-turn-linux-vps-into-anonymous-socks-proxy-via-ssh-encrypted/) and i assume thanks to SSH, the data are encrypted.

As i read Tinyproxy readme, i found no mention about encryption of the data. So i assume data i sent to the proxy and from the proxy are fully readable (plain text), not encrypted and also it wont be able to instruct Tinyproxy to encrypt them?

**Comment by obnoxxx** [comment]
This is correct. Tinyproxy won't currently encrypt.

**Comment by denzuko** [comment]
stunnel -> tinyproxy. Done
