### ISSUE TITLE
report error in log, cannot connect client 

### ISSUE THREAD

**Issue by yixuan178** [tinyproxy/tinyproxy#132]
Hello, 
I found some errors when using that proxy, which would report error as following. 
INFO      Jan 09 04:21:21 [274925]: Closed connection between local client (fd:6) and remote client (fd:7)
INFO      Jan 09 04:21:21 [276158]: Closed connection between local client (fd:6) and remote client (fd:7)
ERROR     Jan 09 04:22:25 [275293]: opensock: Could not establish a connection to ipv6.msftconnecttest.com
ERROR     Jan 09 04:22:25 [275293]: readbuff: recv() error "Connection reset by peer" on file descriptor 6
ERROR     Jan 09 04:22:25 [275293]: Error reading readble client_fd 6
WARNING   Jan 09 04:22:25 [275293]: Could not retrieve request entity
CONNECT   Jan 09 04:25:08 [276523]: Connect (file descriptor 6): 192.168.162.73 [192.168.162.73]
ERROR     Jan 09 04:25:08 [276523]: read_request_line: Client (file descriptor: 6) closed socket before read.
ERROR     Jan 09 04:25:08 [276523]: Error reading readble client_fd 6
WARNING   Jan 09 04:25:08 [276523]: Could not retrieve request entity

can you help give some idea how to resolve that issue? 

thanks,
yixuan

**Comment by rofl0r** [comment]
please provide some background information what you're trying to do, and what fails etc.

**Comment by yixuan178** [comment]
Hello rofl0r, 
i tried to use same lab desktop, it seems ok.  but when i used my pc to connect, it will report above error log. it seems tinyproxy will try to connect my pc but failed. not sure if it is a firewall issue. (btw, i have disable desktop's firewall) 
thanks,
Eugene

**Comment by rofl0r** [comment]
> ERROR Jan 09 04:22:25 [275293]: opensock: Could not establish a connection to ipv6.msftconnecttest.com

maybe your connection to the proxy does not work ? or your proxy does not support ipv6 ?

**Comment by rofl0r** [comment]
closing due to lack of feedback. feel free to reopen when you have news.
