### ISSUE TITLE
Security - prevent information leakage in the via header

### ISSUE THREAD

**Issue by oliverhenlich** [tinyproxy/tinyproxy#134]
Hi.
While trying to find a way to hide the information leaked in the via header I ended up looking in the source code and found that there is already a FIXME in there about it.

Is this an easy fix that could make it into another release? 
Would make our security guy much happier :)

BTW by leakage I mean the fact that it appends (tinyproxy <version>).

reqs.c
```
* FIXME: Need to add code to "hide" our internal information for security
 * purposes.
 */
static int
write_via_header (int fd, hashmap_t hashofheaders,
unsigned int major, unsigned int minor)
```

**Comment by rofl0r** [comment]
> BTW by leakage I mean the fact that it appends (tinyproxy ).

where does it do  that ? do you have some example data ?

also, do you already have an idea how this could this be fixed ?

**Comment by oliverhenlich** [comment]
Hi,

Sorry for late reply.

All connections that tinyproxy proxies it adds a "Via" header (as is required by the RFC).

You can inspect these headers with a service like:  http://www.xhaus.com/headers

The header that tinyproxy adds looks like this:
 Via: 1.1 mycustomizedname (tinyproxy/1.8.4)

Cheers
Oliver

**Comment by rofl0r** [comment]
there's a config option disableviaheader which should suppress this. please reopen if i'm wrong.
