### ISSUE TITLE
Enhancement: Apply different filters to IP's or networks

### ISSUE THREAD

**Issue by TheKernel** [tinyproxy/tinyproxy#135]
A feature to allow whitelists to be applied to specific client IPs or network ranges.

This might be through defining groups in the config file containing IP addresses and ranges and applying a group wide filter file, something like this for example:

> tinyproxy.conf:
//define the group names
Network-Group: "group-one"
Network-Group: "group-two"

//define the group members
group-one: 192.168.0.0/24
group-one: 192.168.1.100
group-two: 10.0.0.1/16

//allow group names to be used in place of networks 
Allow group-one
Allow group-two

//allow group specific config options
group-one FilterExtended On
group-one FilterURLs On
group-one FilterDefaultDeny Yes
group-one Filter "/etc/tinyproxy/whitelist-one"

group-two FilterDefaultDeny No

In the above example 192.168... addresses are restricted to the whitelist and 10.0.0.1/16 is not filtered at all.

**Comment by rofl0r** [comment]
not a bad idea, but this would be too much effort to implement and complicate the code considerably. there are already similar options in place that can be used for these purposes, although not as elegantly.

**Comment by stevekaten** [comment]
@rofl0r Sorry to dredge up an old Issue.  What are the similar options?  My goal is to implement an ACL based list where I can grant permission to an ip address to a specific domain.  An example would be give 10.10.10.12 access to tacobell.com, but nothing else.
