### ISSUE TITLE
Shell http proxy

### ISSUE THREAD

**Issue by Sabrimjd** [tinyproxy/tinyproxy#137]
Hi guys i'm new to github, first time posting

I'm verry surprised of tinyproxy loved it.

didn't get to work the` export https_proxy=http://192.168.5.15:3128/`
i have the default configuration, it's working with my web browser but not in shell.

Thanks all

**Comment by Sabrimjd** [comment]
Update : actually working

**Comment by rofl0r** [comment]
so is your issue solved? then close this pls
