### ISSUE TITLE
http2 proxy support

### ISSUE THREAD

**Issue by nmiculinic** [tinyproxy/tinyproxy#139]
Does this support http2 standard? In my experiments I don't think so

**Comment by bertliao** [comment]
Not support, currently only HTTP 1.0

**Comment by savchuk1985** [comment]
Are you planned to implement http/2?

**Comment by rofl0r** [comment]
nope, can't find that one on my todo list. i've never seen an app configured to use a proxy trying to use http/2.0 for the proxy connection itself. and 99% of traffic today is https, which uses connect method on our site and the client can use whatever protocol it wants to talk with the endpoint.
