### ISSUE TITLE
2 Memory leak found in child process

### ISSUE THREAD

**Issue by bertliao** [tinyproxy/tinyproxy#141]
2 memory leak found in the below files
src/reqs.c                                get_all_headers
`tmp = (char *) saferealloc (header, len + linelen);`
src/transparent-proxy.c          build_url
`*url = (char *) safemalloc (len);`

**Comment by bertliao** [comment]
patches:
`--- a/src/reqs.c`
`+++ b/src/reqs.c`
`@@ -672,7 +672,11 @@ static int get_all_headers (int fd, hashmap_t hashofheaders)`
`                 /*`
`                  * Append the new line to the current header field.`
`                  */`
`-                tmp = (char *) saferealloc (header, len + linelen);`
`+                if( NULL == header ) {`
`+                    tmp = (char *) safemalloc (len + linelen);`
`+                } else {`
`+                    tmp = (char *) saferealloc (header, len + linelen);`
`+                }`
``

`--- a/src/transparent-proxy.c`
`+++ b/src/transparent-proxy.c`
`@@ -38,6 +38,7 @@`
` static int build_url (char **url, const char *host, int port, const char *path)`
` {`
`         int len;`
`+        char *tmp;`
``
`         assert (url != NULL);`
`         assert (host != NULL);`
`@@ -45,10 +46,13 @@ static int build_url (char **url, const char *host, int port, const char *path)`
`         assert (path != NULL);`
``
`         len = strlen (host) + strlen (path) + 14;`
`-        *url = (char *) safemalloc (len);`
`-        if (*url == NULL)`
`+`
`+        tmp = (char *) saferealloc (*url, len);`
`+        if (tmp == NULL) {`
`                 return -1;`
`-`
`+        }`
`+        *url = tmp;`
`+`
`         return snprintf (*url, len, "http://%s:%d%s", host, port, path);`
 `}`

**Comment by rofl0r** [comment]
thanks. please open a PR so one can comment on the patches.

**Comment by bertliao** [comment]
@rofl0r PR is open. https://github.com/tinyproxy/tinyproxy/pull/142
When the 1.9.0 release?

**Comment by rofl0r** [comment]
thanks. added comments. there some more cleanups that need to be done before the release, but it's planned to happen quite soon.

btw what makes you believe there are memory leaks ?

**Comment by bertliao** [comment]
Our team found the child process take more and more memory than they start(We do not let them exit). Then we reviewed the code and found out these bugs.

**Comment by rofl0r** [comment]
on what system ? does your proposed patch fix the issue on that system ?

**Comment by rofl0r** [comment]
close by 81ea4fe
