### ISSUE TITLE
http injection error

### ISSUE THREAD

**Issue by Norabuch** [tinyproxy/tinyproxy#149]
Hi, i trying connect using http injection header, but i can't, please tell me how i can do this ?
Thanks a lot for you work.

**Comment by Norabuch** [comment]
I'm using 'HTTP Injector' android app, he allow connection using custom payload. But i can't make tinyproxy allow this function.

**Comment by rofl0r** [comment]
sorry, i have no idea what this stuff is supposed to do. unless you can come up with very specific low level details, i doubt we can help you getting this working. maybe it would be a less frustrating experience for you to try another proxy server such as squid.
anyway, i'm leaving this open for the moment because maybe someone else magically knows what you're trying to do and can help out...

**Comment by Norabuch** [comment]
I'm sorry, my fault.I use http tunnel + ssh (squid + openssh) to pass through a censoring done by the provider, for this I use an application that does http tunnel using a payload (customs headers), which fools the firewall of my provider. But I would like to use proxy + openvpn instead of ssh, there is a month I try but squid does not allow my connection to openvpn. Testing with tinyproxy I could easily connect to OpenVPN, but I was not able to use a custom payload so that in a real situation I can't go through the firewall.
Image of the error.
![whatsapp image 2018-02-26 at 12 49 14](https://user-images.githubusercontent.com/28420612/36680105-a404d7b4-1af3-11e8-9172-6993390bcf6e.jpeg)

Image of the app I use.
![whatsapp image 2018-02-26 at 12 37 10](https://user-images.githubusercontent.com/28420612/36679568-49e3bfbc-1af2-11e8-865c-591e37adc823.jpeg)
If you can any other detail I can add, please tell me.

**Comment by Norabuch** [comment]
rofl0r  
Thanks for trying help me.

**Comment by rofl0r** [comment]
what are those split things supposed to mean ?

**Comment by Norabuch** [comment]
Dan brow, i think we will not get solve my problem, i have no idea to.
I use this configuration to connect in squid proxy.
But thanks a lot for tryi help-me.
I will try anothers proxys.
