### ISSUE TITLE
When tinyproxy support HTTP 1.1

### ISSUE THREAD

**Issue by bertliao** [tinyproxy/tinyproxy#152]
Some server donot response or send error when tinyproxy connect using HTTP 1.0
When tinyproxy support HTTP 1.1?  Is there any plans?

**Comment by rofl0r** [comment]
are you talking about transparent proxy, or generally ?

**Comment by bertliao** [comment]
Transparent proxy, the HTTP 1.1 has many new features, more and more services depend on it.

**Comment by rofl0r** [comment]
i can take a look if you provide me a config and instructions to set up a test environment.

**Comment by bertliao** [comment]
I will write a doc later about the config and the env.

**Comment by rofl0r** [comment]
please reopen once you have the details ready.

**Comment by rofl0r** [comment]
search in reqs.c for all occurences of `1.0` and replace them with `1.1`, recompile tinyproxy and check whether that fixes the issue.

**Comment by lcudst** [comment]
I tried this way just before your comment and fortunately it worked! Thank you.

**Comment by rofl0r** [comment]
i opened a PR addressing this issue: https://github.com/tinyproxy/tinyproxy/pull/312

please report whether it resolves it.

**Comment by jon-walton** [comment]
Hi @rofl0r , I just tried this and it seems to need another small change to get it working 100%.

https://github.com/tinyproxy/tinyproxy/blob/master/src/reqs.c#L306 `SSL_CONNECTION_RESPONSE` needs to be able to use the correct http version, or should it always respond with 1.1 as `CONNECT` isn't valid for 1.0?

Even though it's most likely a very small fix, I don't trust my abilities to not break things via a pull request 😃 so hopefully someone is able to pick it up?

**Comment by rofl0r** [comment]
@jon-walton thanks. could you try wether pr #449 fixes your perceived issue ?

**Comment by jon-walton** [comment]
@rofl0r yep, that works great! thanks
