### ISSUE TITLE
HTTPS via CONNECT method not works.

### ISSUE THREAD

**Issue by SiarheiVolkau** [tinyproxy/tinyproxy#155]
HTTPS via CONNECT method not works on master branch (commit a53f62a212947600a785b3e94db55a856325920e).

This feature definitely works in v1.8.

Thank you.

**Comment by rofl0r** [comment]
could you please run `git bisect` and find out exactly which commit broke it for you.

Thank you.

**Comment by rofl0r** [comment]
for the record, i just used tinyproxy from git and was surfing on some HTTPS enabled sites. Works For Me (tm).
this is my config
```
$ cat tinyproxy.conf | grep -v '^#.*' | sed '/^\s*$/d'
User nobody
Group nobody
Port 8888
Timeout 600
DefaultErrorFile "/usr/local/share/tinyproxy/default.html"
StatFile "/usr/local/share/tinyproxy/stats.html"
LogLevel Info
MaxClients 100
MinSpareServers 5
MaxSpareServers 20
StartServers 10
MaxRequestsPerChild 0
Allow 127.0.0.1
ViaProxyName "tinyproxy"
```
this is on sabotage linux x86_64 FTR. tinyproxy was compiled with all default options.

**Comment by SiarheiVolkau** [comment]
Sorry, thats my fault. Works as expected.

**Comment by rofl0r** [comment]
Ah, so it was PEBKAC, as expected.
