### ISSUE TITLE
I want people connect to my Tinyproxy server in AWS EC2.

### ISSUE THREAD

**Issue by wupengshang** [tinyproxy/tinyproxy#16]
I have connect to Tinyproxy with SHH tunnel. And I commit the "Allow 127.0.0.01",but when I connect from other computers without SSH or tunnel, it can establish a TCP connection. But if I visit a website like google.com,it will be disconnected immediately.
Could you tell me what can i do for this?

**Comment by obnoxxx** [comment]
* What version of tinyproxy are you using?
* Can you show the whole config?
* Is the spelling above correct? "Allow 127.0.0.01" instead of "Allow 127.0.0.1"
* Are there other Allow lines?
* Can you provide a log of tinyproxy of LogLevel Connect when the access happens?

**Comment by obnoxxx** [comment]
any answers to the questions I posed in order to debug the issue?

**Comment by ianmarcinkowski** [comment]
Probably reasonable to close, as it is so old and the OP didn't respond.

I hope it's not annoying, but I'm going to go through a few of the oldest issues and comment on them if they seem reasonable to close.  As a user, it's hard to see 100 open issues in a small project.  Please let me know if this is annoying :)
