### ISSUE TITLE
basic authentication accepts any prefix of the correct username+password

### ISSUE THREAD

**Issue by goffrie** [tinyproxy/tinyproxy#160]
the code:
https://github.com/tinyproxy/tinyproxy/blob/4d9891e59e7c7ee77137fcdb3d02798af96811ff/src/basicauth.c#L95

notably, this only looks at the first `al` characters of `entry`.
that means you can always authenticate by passing the empty string, as in the header `"Proxy-Authorization: Basic "`.

**Comment by crozone** [comment]
Well that's not good.

Why would `al = strlen (authstring);` be used with `strncmp` instead of just using `strcmp`? What's the rationale?

**Comment by rofl0r** [comment]
oops, good find! this is a leftover of previous code. fix underway.

**Comment by rofl0r** [comment]
@goffrie @crozone please check whether the fix proposed in #161 is sufficient, thanks.

**Comment by rofl0r** [comment]
i did the testing myself, fix seems OK. let me know if there are further issues, thanks.
