### ISSUE TITLE
upstream proxy authentication not working (syntax error in conf)

### ISSUE THREAD

**Issue by larkoie** [tinyproxy/tinyproxy#164]
Hi,
I'm trying to use the authentication feature for an upstream proxy but i'm keep getting 'syntax error' in config when starting the service (CentOS 7). If i remove the authentication part + the http part, it starts without any issue. here is the config line : 
upstream http login:'password'@my.upstream.proxy:80

I cloned the master repo and followed the guide to compile it (./autogen.sh ; ./configure --enable-upstream ; make; make install).
It looks like the feature is not implemented in what's installed. Am I missing something here? Should i specify an option when installing it?

Thanks

**Comment by rofl0r** [comment]
are username and password all ascii or do they contain special characters ?

**Comment by larkoie** [comment]
My password contains an @ but even by puting a random password without special characters like username:password it does not work and I get the syntax error when launching the service. Also when putting http or socks5 I get a syntax error. It's like the feature is not known by the application.

**Comment by rofl0r** [comment]
there's an option --enable-upstream but it is active by default when you compile from git.
and both user and password must **NOT** contain special characters like `@`

**Comment by larkoie** [comment]
Thanks for your reply.
As stated in my first post i've run ./configure with --enable-upstream option. Whether I use a password containing special characters or not it will end in "syntax error". Same thing when specifying the type of upstream proxy (example : http), it does not accept this parameter and just throw the syntax error.
I had to move forward and used another solution but thanks for your effort.
Cheers

**Comment by gaheinrichs** [comment]
Facing the same issue here. Straight up copying the example from the config file throws the error when starting.

`upstream http user:pass@testproxy:8008`

Tinyproxy output:

```
Syntax error on line 183
Unable to parse config file. Not starting.
```

**Comment by jan-hudec** [comment]
For the benefit of whoever runs into this by search:

Up to and including release 1.10.0 only lowercase alphanumeric characters (and `.`, `-` and `_`) are accepted in username and password, but many configurations use more than that. That was changed in https://github.com/tinyproxy/tinyproxy/commit/dc41b3533326d745c65afaea4cb34c229a31d0c3 to accept anything except the separator, but it is not released as of early January 2019.

**Comment by schanzel** [comment]
Any updates on when this release is expected?

**Comment by hron84** [comment]
Anyone know anything about this? If you could allow only upcase alphanum letters, it could solve my problem with our corporate proxy.
