### ISSUE TITLE
How do I enable SOCKS5?

### ISSUE THREAD

**Issue by graynk** [tinyproxy/tinyproxy#166]
I can't find anything helpful about it in the docs. `Upstream socks5 user:pass@127.0.0.1:8881` doesn't work for me (actually it breaks everything, without it proxy works via HTTP on 8880). What do I do to enable SOCKS5? Does `upstream` mean I have to set up some OTHER proxy with SOCKS5 support?
I use the latest version from github.

**Comment by rofl0r** [comment]
yes, upstream means "connect to an upstream proxy".
it doesn't mean "turn tinyproxy into a socks5 proxy".
if you need a socks5 proxy, check out https://github.com/rofl0r/microsocks
