### ISSUE TITLE
cannot create pid-file on ubuntu 16.04

### ISSUE THREAD

**Issue by admzzz** [tinyproxy/tinyproxy#168]
$systemctl status tinyproxy
● tinyproxy.service - Tinyproxy Web Proxy Server
   Loaded: loaded (/lib/systemd/system/tinyproxy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-04-28 10:47:43 UTC; 2min 23s ago
 Main PID: 6577 (code=exited, status=71)

Apr 28 10:47:43 ip-172-31-40-24 systemd[1]: Started Tinyproxy Web Proxy Server.
Apr 28 10:47:43 ip-172-31-40-24 tinyproxy[6577]: tinyproxy: Could not create file /var/run/tinyproxy/tinyproxy.pid: No such file or
Apr 28 10:47:43 ip-172-31-40-24 tinyproxy[6577]: /usr/sbin/tinyproxy: Could not create PID file.
Apr 28 10:47:43 ip-172-31-40-24 systemd[1]: tinyproxy.service: Main process exited, code=exited, status=71/n/a
Apr 28 10:59:06 ip-172-31-40-24 systemd[1]: Started Tinyproxy Web Proxy Server.
Apr 28 10:47:43 ip-172-31-40-24 systemd[1]: tinyproxy.service: Unit entered failed state.
Apr 28 10:47:43 ip-172-31-40-24 systemd[1]: tinyproxy.service: Failed with result 'exit-code'.

**Solution:**

$ ls -lFa /var/run/tinyproxy
ls: cannot access '/var/run/tinyproxy': No such file or directory
$ sudo mkdir /var/run/tinyproxy
$ sudo chown nobody:nogroup /var/run/tinyproxy
$ sudo chmod 755 /var/run/tinyproxy
$ ls -lFa /var/run/tinyproxy
total 0
drwxr-xr-x  2 nobody nogroup   40 Apr 28 10:55 ./
drwxr-xr-x 29 root   root    1120 Apr 28 10:55 ../
$ sudo chmod 600 /var/run/tinyproxy

$ sudo systemctl start tinyproxy
$ systemctl status tinyproxy
● tinyproxy.service - Tinyproxy Web Proxy Server
   Loaded: loaded (/lib/systemd/system/tinyproxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-04-28 10:59:06 UTC; 14s ago
 Main PID: 6766 (tinyproxy)
    Tasks: 11
   Memory: 3.3M
      CPU: 8ms
   CGroup: /system.slice/tinyproxy.service
           ├─6766 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           ├─6770 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           ├─6771 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           ├─6772 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           ├─6773 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           ├─6774 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           ├─6775 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           ├─6776 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           ├─6777 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           ├─6778 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d
           └─6779 /usr/sbin/tinyproxy -c /etc/tinyproxy.conf -d

Apr 28 10:59:06 ip-172-31-40-24 systemd[1]: Started Tinyproxy Web Proxy Server.

**Comment by rofl0r** [comment]
i have no idea what your issue is. how about explaining what you want instead of pasting walls of logs ?

**Comment by admzzz** [comment]
rofl0r,
you'd unlearned to read at all? ;-)

the first 5 lines described, that tinyproxy cannot start on ubuntu 16.04, because it could not create file /var/run/tinyproxy/tinyproxy.pid.

the next 9 lines explaines what is going wrong in details: there are no directory /var/run/tinyproxy and /var is owned by root, i.e. tinyproxy has no access to it.

the rest is my temporary solution, which need to be transformed to a startup script, if one really needed tinyproxy to start on every boot untill tinyproxy's creator will learn to read back and fix this fantastically silly error.

**Comment by rofl0r** [comment]
> you'd unlearned to read at all? ;-)

sorry, i'm not giving free support here and wasting my time for people that can't even formulate what their problem is and then making funny remarks about my capabilities when i ask them for more info.

**Comment by admzzz** [comment]
oh, darling, you're afraid of being funny! ;-)

nevertheless, here is your second and more serious mistake: it was not a request for support - i'd turn you to the problem and even show how it could be walked around, but you preferred to run away from it ass-backwards . ;-) 

jfyi; this mistake occurred on a clean amazon image of ubuntu, so the problem is in tinyproxy only.
