### ISSUE TITLE
Behaviour for http header field 'Cache-Control'

### ISSUE THREAD

**Issue by joaocmendonca** [tinyproxy/tinyproxy#169]
From the documentation it is unclear what is the default behavior of tinyproxy for http requests containing Header Field `'Cache-Control'`.

I am specifically looking on cases where the request contains `Cache-Control: no-cache`, so that the transmitted data must not be cached on the webproxy file system. I'd be very thankful for the clarification of this point.

Refs: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9

Thanks!

**Comment by rofl0r** [comment]
afaik tinyproxy doesn't do any caching at all.

**Comment by joaocmendonca** [comment]
Thanks @rofl0r for the comment. Since I also did not find any code parts dealing with caching whatsoever, I am closing this and marking it as *closed*. Cheers!
