### ISSUE TITLE
ReversePath causes "Unable to parse config file" error

### ISSUE THREAD

**Issue by cfredhart** [tinyproxy/tinyproxy#17]
The attached tinyproxy.conf file produces the error 

```
$ /usr/local/sbin/tinyproxy -c /ram/tinyproxy.conf
Syntax error on line 305
Unable to parse config file. Not starting.
```

I can't seem to get reverse proxy function to work on OS X (installed via homebrew: tinyproxy-1.8.3.el_capitan.bottle.2.tar.gz)

[tinyproxy.txt](https://github.com/tinyproxy/tinyproxy/files/169707/tinyproxy.txt)

**Comment by obnoxxx** [comment]
Is tinyproxy compiled with reverse support?
Running "tinyproxy  -h | grep Reverse" should print "Reverse proxy support".
If it does not, then the above is the expected behaviour.
Otherwise we need to investivate further...

**Comment by pachun** [comment]
@cfredhart I had the same issue. I had to install it with the `with-reverse` option in homebrew. Check out line 17 in homebrew's installation formula for tinyproxy:

https://github.com/Homebrew/homebrew-core/blob/fb81645562f7e495a49561065912788af2d1f14f/Formula/tinyproxy.rb

For me, that consisted of first uninstalling tinyproxy with homebrew:

```
brew uninstall tinyproxy
```

Then, installing it with the `with-reverse` option this way:

```
brew install tinyproxy --with-reverse
```

I hope this helps! If so, you should probably mark this issue solved or whatever sounds best.

**Comment by obnoxxx** [comment]
@cfredhart , I guess @pachun has the answer. Closing this issue now. Please open again if problem persists...

**Comment by kdar** [comment]
Ran into this issue on Arch. Apparently, community/tinyproxy is not compiled with reverse proxy support.

**Comment by YourFin** [comment]
It should be noted that this still hasn't been added on the arch linux community package. I've filed a bug report [here](https://bugs.archlinux.org/task/59580?project=5&string=tinyproxy).
