### ISSUE TITLE
Can tinyproxy forward web traffic to different local computers based on different domain names ?

### ISSUE THREAD

**Issue by adrianTNT** [tinyproxy/tinyproxy#170]
My ISP only gives me few dedicated IPs and I need to host many websites on different computers. 
So what I am trying to do is setup a proxy that would receive all web (port 80) requests over the internet and based on requested site/domain name it would return the content from different local computers (192.168.1.2, 192.168.1.3, etc).
**Can tinyproxy do that ?** Is there a name for this functionality ? (to know what to look for).

**Comment by rofl0r** [comment]
that's called reverse proxy

**Comment by RealOrangeOne** [comment]
I've just been looking through the man pages, and it sounds like it can. You're basically looking for a reverse proxy, but tinyproxy only supports path-based reverse proxying, rather than by domain. My solution to this (completely untested) would be:

```

**Comment by rofl0r** [comment]
@adrianTNT did you try out what @RealOrangeOne suggested ? i have my doubts that it would work, but maybe i'm wrong.

**Comment by adrianTNT** [comment]
@rofl0r I don't remember testing tinyproxy much but I know for sure I was able to do this relatively easy with Nginx.

**Comment by rofl0r** [comment]
yeah, nginx is designed for this scenario. anyway it would be interesting to know whether @RealOrangeOne 's suggestion works.

**Comment by newash** [comment]
@rofl0r I just tried it, and it - kind of - works. 🎉 
Notes:
- In addition to the settings above you need at least set `ReverseOnly` (and maybe `ReverseMagic`) set, otherwise you get `Unauthorized connection from <your IP>` error.
- With multiple upstreams set, my other server on the Lan was responding and even redirecting fine, but the router's own Luci uhttpd was not (yet to be investigated).

**Comment by rofl0r** [comment]
@newash: cool, thanks for testing. i guess this issue can be closed then. if you get around to find out what's happening with "Luci uhttpd" and it's due to a bug in tinyproxy, please open a new issue.
