### ISSUE TITLE
./autogen.sh fails

### ISSUE THREAD

**Issue by chkoreff** [tinyproxy/tinyproxy#171]
I've tried cloning the project on two different Linux machines, one my laptop and another a Linode instance, and in both cases the initial autogen.sh is failing the same way:

~~~~~
web@linode-fexl:~/install/tinyproxy$ ./autogen.sh 
+ cd .
+ aclocal -I m4macros
./autogen.sh: 11: ./autogen.sh: aclocal: not found
+ cd /home/web/install/tinyproxy
+ set -
./configure
./autogen.sh: 21: ./autogen.sh: ./configure: not found

Configure failed or did not finish!
~~~~~

Seeing as how it's the very first step in the build process and it's failing the same way on two entirely different machines, I doubt I'm doing anything wrong, but who knows.

**Comment by rofl0r** [comment]
you gotta install autoconf and automake

**Comment by chkoreff** [comment]
Ah of course, sorry to bother you with that.  I just assumed those would be present on a brand new OS install.
