### ISSUE TITLE
For the MaxRequestsPerChild error/exceptional condition, issue Log Message as 'WARNING' or 'ERROR'

### ISSUE THREAD

**Issue by joaocmendonca** [tinyproxy/tinyproxy#176]
Hi There,

I've noticed situations in which tinyproxy will stop working entirely if the 'MaxRequestsPerChild' condition is reached.

```NOTICE    Jun 03 02:00:50 [2672]: Child has reached MaxRequestsPerChild (10000). Killing child.```

In this case, I believe the Log Message issued should be at least a 'WARNING' if not an 'ERROR'. This  makes tinyproxy more diagnostic-friendly.

Cheers
Joao

**Comment by rofl0r** [comment]
thanks for pointing out this issue. i don't think we should kill anything here, but rather just print a diagnostic message and reject new connections for robustness.

**Comment by rofl0r** [comment]
should be fixed by 281488a72924c6c28f8c7a0b534a4e030766a70f and b935dc85c3fca51de8e131d6aa2047f8a0404f0c
