### ISSUE TITLE
how to use the option <StatHost> ,how to see the stats.html

### ISSUE THREAD

**Issue by tony-sunjian** [tinyproxy/tinyproxy#177]
how to see the stats.html,? 
check the url  127.0.0.1:8888 ,it returns "Tinyproxy was unable to connect to the remote web server".

but  how can i see the "statistics page"?

**Comment by rofl0r** [comment]
it works via a hostname which you put into the "stathost" configuration option.

for example:

StatHost foobar

then put an entry in your DNS server config or in /etc/hosts
```127.0.0.1 foobar```
and then enter http://foobar:8888/ in the adressbar

or without DNS setup:
```
netcat IP_HERE 8888
GET / HTTP/1.1
Host: foobar
<ENTER>
<ENTER>
```
