### ISSUE TITLE
Timeout support when connection to upstream

### ISSUE THREAD

**Issue by icy** [tinyproxy/tinyproxy#18]
Hi,

Could Tinyproxy have new option to support `timeout` when connecting to upstream? For now, the timeout is very long and it's not very convenient for daily use.

( I've tried to use non-blocking `connect` (in `src/sock.c`) but I couldn't make it work. )

Thanks a lot.

**Comment by rofl0r** [comment]
this should be fixed now by 0b9a74c29036f9215b2b97a301b7b25933054302.
the global timeout also applies to upstream.
