### ISSUE TITLE
Filter an IP range

### ISSUE THREAD

**Issue by sd65** [tinyproxy/tinyproxy#180]
Hello,

I'm not sure how to filter an IP-range (network/mask).
Does tinyproxy supports this?

Thanks!

**Comment by Dreamisdead** [comment]
Me too. I need to limit proxy to only allow access to certain IP's not domain names.

Strange that you can filter clients by ip but not hosts clients are connecting to.

Can this be done?

**Comment by rofl0r** [comment]
sounds like a job for iptables

**Comment by Dreamisdead** [comment]
Thing is with iptables with rules I limit whole server - I don't want that.

I only want to filter clients access, by limiting it to certain IPs.

**Comment by rofl0r** [comment]
what you want is the opposite of OP, and yes, the `Allow`-directive can be used to implement an IP-whitelist.

**Comment by Dreamisdead** [comment]
But `Allow` is for limiting clients connecting to tinyproxy according to manual.
`The Allow and Deny options provide a means to customize which clients are allowed to access Tinyproxy.`

I want to limit hosts that **tinyproxy clients can connect to**, which I think is same thing OP wants.

For example setting `FilterDefaultDeny = yes` and then whitelist allowed hosts by IP.
Now `Filter` only works by domain names according to manual.

**Comment by rofl0r** [comment]
this is now possible since commit 335477b16e8926a51d35d94789906397524eb7bb because the upstream directive allows specification of ip masks, and together with the nullrouting functionality one could do something like 
`upstream http 0.0.0.0:0 "10.0.0.0/8"`

**Comment by jonapgartwohat** [comment]
To anyone else looking for similar, the `upstream`  doesn't actually prevent connections to that network mask. The proxy will still allow outgoing requests to hosts that resolve to a "blocked" IP.

**Comment by rofl0r** [comment]
> upstream doesn't actually prevent connections to that network mask.

if the described functionality doesn't work, please open a new issue showing the relevant parts of your config, and state which version you use.
