### ISSUE TITLE
Tinyproxy User/password authentication 

### ISSUE THREAD

**Issue by tifend** [tinyproxy/tinyproxy#182]
Hello, 

We are trying to configure basic password Auth support in our tinyproxy server, but there is no option to add this feature.

Upon searching, I just found this below thread at github, So I removed the previous installation (done via yum command) and then tried to install via this command "git clone https://github.com/tinyproxy/tinyproxy" but it throws an error.

https://github.com/tinyproxy/tinyproxy/issues/29
https://github.com/tinyproxy/tinyproxy/pull/129

Getting an error message when installing it:
`
[root@p4483673 tinyproxy]# make
make  all-recursive
make[1]: Entering directory `/root/tinyproxy'
Making all in src
make[2]: Entering directory `/root/tinyproxy/src'
make  all-am
make[3]: Entering directory `/root/tinyproxy/src'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/tinyproxy/src'
make[2]: Leaving directory `/root/tinyproxy/src'
Making all in data
make[2]: Entering directory `/root/tinyproxy/data'
Making all in templates
make[3]: Entering directory `/root/tinyproxy/data/templates'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/tinyproxy/data/templates'
make[3]: Entering directory `/root/tinyproxy/data'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/tinyproxy/data'
make[2]: Leaving directory `/root/tinyproxy/data'
Making all in etc
make[2]: Entering directory `/root/tinyproxy/etc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/tinyproxy/etc'
Making all in docs
make[2]: Entering directory `/root/tinyproxy/docs'
Making all in man5
make[3]: Entering directory `/root/tinyproxy/docs/man5'
*** a2x (asciidoc) is required to regenerate tinyproxy.conf.5 ***
make[3]: *** [tinyproxy.conf.5] Error 1
make[3]: Leaving directory `/root/tinyproxy/docs/man5'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/tinyproxy/docs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/tinyproxy'
make: *** [all] Error 2
`
Can you please tell me how to configure user/pass basic authentication?

**Comment by tifend** [comment]
Installation issue has been resolved after installing asciidoc.
Can you please tell me how to configure user/pass basic authentication?


`[root@p4483673 tinyproxy]# ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for socket in -lsocket... no
checking for htonl in -lsocket... no
checking for yp_get_default_domain... no
checking for gethostname in -lnsl... yes
checking for inet_aton in -lresolv... yes
checking for ANSI C header files... (cached) yes
checking whether time.h and sys/time.h may both be included... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking for memory.h... (cached) yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking values.h usability... yes
checking values.h presence... yes
checking for values.h... yes
checking whether lstat dereferences a symlink specified with a trailing slash... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for inet_ntoa... yes
checking for strdup... yes
checking for strlcpy... no
checking for strlcat... no
checking for setgroups... yes
checking to see if compiler understands -fdiagnostics-show-option... yes
checking to see if compiler understands -Wall... yes
checking to see if compiler understands -Wextra... yes
checking to see if compiler understands -Wno-unused-parameter... yes
checking to see if compiler understands -Wmissing-prototypes... yes
checking to see if compiler understands -Wstrict-prototypes... yes
checking to see if compiler understands -Wmissing-declarations... yes
checking to see if compiler understands -Wfloat-equal... yes
checking to see if compiler understands -Wundef... yes
checking to see if compiler understands -Wformat=2... yes
checking to see if compiler understands -Wlogical-op... yes
checking to see if compiler understands -Wmissing-include-dirs... yes
checking to see if compiler understands -Wformat-nonliteral... yes
checking to see if compiler understands -Wold-style-definition... yes
checking to see if compiler understands -Wpointer-arith... yes
checking to see if compiler understands -Waggregate-return... yes
checking to see if compiler understands -Winit-self... yes
checking to see if compiler understands -Wpacked... yes
checking to see if compiler understands --std=c89... yes
checking to see if compiler understands -ansi... yes
checking to see if compiler understands -Wno-overlength-strings... yes
checking to see if compiler understands -Wno-long-long... yes
checking to see if compiler understands -Wno-overlength-strings... yes
checking to see if compiler understands -Wdeclaration-after-statement... yes
checking to see if compiler understands -Wredundant-decls... yes
checking to see if compiler understands -Wmissing-noreturn... yes
checking to see if compiler understands -Wshadow... yes
checking to see if compiler understands -Wendif-labels... yes
checking to see if compiler understands -Wcast-qual... yes
checking to see if compiler understands -Wcast-align... yes
checking to see if compiler understands -Wwrite-strings... yes
checking to see if compiler understands -Wp,-D_FORTIFY_SOURCE=2... yes
checking to see if compiler understands -fno-common... yes
checking to see if linker understands -z,defs... yes
checking for xsltproc... /usr/bin/xsltproc
checking for a2x... /usr/bin/a2x
checking for xmllint... /usr/bin/xmllint
testing xmllint... failed
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating data/Makefile
config.status: creating data/templates/Makefile
config.status: creating etc/Makefile
config.status: creating docs/Makefile
config.status: creating docs/man5/Makefile
config.status: creating docs/man5/tinyproxy.conf.txt
config.status: creating docs/man8/Makefile
config.status: creating docs/man8/tinyproxy.txt
config.status: creating m4macros/Makefile
config.status: creating tests/Makefile
config.status: creating tests/scripts/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
[root@p4483673 tinyproxy]# make
make  all-recursive
make[1]: Entering directory `/root/tinyproxy'
Making all in src
make[2]: Entering directory `/root/tinyproxy/src'
make  all-am
make[3]: Entering directory `/root/tinyproxy/src'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/tinyproxy/src'
make[2]: Leaving directory `/root/tinyproxy/src'
Making all in data
make[2]: Entering directory `/root/tinyproxy/data'
Making all in templates
make[3]: Entering directory `/root/tinyproxy/data/templates'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/tinyproxy/data/templates'
make[3]: Entering directory `/root/tinyproxy/data'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/tinyproxy/data'
make[2]: Leaving directory `/root/tinyproxy/data'
Making all in etc
make[2]: Entering directory `/root/tinyproxy/etc'
  GEN    tinyproxy.conf
make[2]: Leaving directory `/root/tinyproxy/etc'
Making all in docs
make[2]: Entering directory `/root/tinyproxy/docs'
Making all in man5
make[3]: Entering directory `/root/tinyproxy/docs/man5'
  GEN    tinyproxy.conf.5
Note: Writing tinyproxy.conf.5
make[3]: Leaving directory `/root/tinyproxy/docs/man5'
Making all in man8
make[3]: Entering directory `/root/tinyproxy/docs/man8'
  GEN    tinyproxy.8
Note: Writing tinyproxy.8
make[3]: Leaving directory `/root/tinyproxy/docs/man8'
make[3]: Entering directory `/root/tinyproxy/docs'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/tinyproxy/docs'
make[2]: Leaving directory `/root/tinyproxy/docs'
Making all in m4macros
make[2]: Entering directory `/root/tinyproxy/m4macros'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/tinyproxy/m4macros'
Making all in tests
make[2]: Entering directory `/root/tinyproxy/tests'
Making all in scripts
make[3]: Entering directory `/root/tinyproxy/tests/scripts'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/tinyproxy/tests/scripts'
make[3]: Entering directory `/root/tinyproxy/tests'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/tinyproxy/tests'
make[2]: Leaving directory `/root/tinyproxy/tests'
make[2]: Entering directory `/root/tinyproxy'
make[2]: Leaving directory `/root/tinyproxy'
make[1]: Leaving directory `/root/tinyproxy'
[root@p4483673 tinyproxy]# make install
Making install in src
make[1]: Entering directory `/root/tinyproxy/src'
make  install-am
make[2]: Entering directory `/root/tinyproxy/src'
make[3]: Entering directory `/root/tinyproxy/src'
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin"
  /usr/bin/install -c tinyproxy '/usr/local/bin'
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/root/tinyproxy/src'
make[2]: Leaving directory `/root/tinyproxy/src'
make[1]: Leaving directory `/root/tinyproxy/src'
Making install in data
make[1]: Entering directory `/root/tinyproxy/data'
Making install in templates
make[2]: Entering directory `/root/tinyproxy/data/templates'
make[3]: Entering directory `/root/tinyproxy/data/templates'
make[3]: Nothing to be done for `install-exec-am'.
test -z "/usr/local/share/tinyproxy" || /bin/mkdir -p "/usr/local/share/tinyproxy"
 /usr/bin/install -c -m 644 debug.html default.html stats.html '/usr/local/share/tinyproxy'
make[3]: Leaving directory `/root/tinyproxy/data/templates'
make[2]: Leaving directory `/root/tinyproxy/data/templates'
make[2]: Entering directory `/root/tinyproxy/data'
make[3]: Entering directory `/root/tinyproxy/data'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/root/tinyproxy/data'
make[2]: Leaving directory `/root/tinyproxy/data'
make[1]: Leaving directory `/root/tinyproxy/data'
Making install in etc
make[1]: Entering directory `/root/tinyproxy/etc'
make[2]: Entering directory `/root/tinyproxy/etc'
make[2]: Nothing to be done for `install-exec-am'.
test -z "/usr/local/etc/tinyproxy" || /bin/mkdir -p "/usr/local/etc/tinyproxy"
 /usr/bin/install -c -m 644 tinyproxy.conf '/usr/local/etc/tinyproxy'
make[2]: Leaving directory `/root/tinyproxy/etc'
make[1]: Leaving directory `/root/tinyproxy/etc'
Making install in docs
make[1]: Entering directory `/root/tinyproxy/docs'
Making install in man5
make[2]: Entering directory `/root/tinyproxy/docs/man5'
make[3]: Entering directory `/root/tinyproxy/docs/man5'
make[3]: Nothing to be done for `install-exec-am'.
test -z "/usr/local/share/man/man5" || /bin/mkdir -p "/usr/local/share/man/man5"
 /usr/bin/install -c -m 644 tinyproxy.conf.5 '/usr/local/share/man/man5'
make[3]: Leaving directory `/root/tinyproxy/docs/man5'
make[2]: Leaving directory `/root/tinyproxy/docs/man5'
Making install in man8
make[2]: Entering directory `/root/tinyproxy/docs/man8'
make[3]: Entering directory `/root/tinyproxy/docs/man8'
make[3]: Nothing to be done for `install-exec-am'.
test -z "/usr/local/share/man/man8" || /bin/mkdir -p "/usr/local/share/man/man8"
 /usr/bin/install -c -m 644 tinyproxy.8 '/usr/local/share/man/man8'
make[3]: Leaving directory `/root/tinyproxy/docs/man8'
make[2]: Leaving directory `/root/tinyproxy/docs/man8'
make[2]: Entering directory `/root/tinyproxy/docs'
make[3]: Entering directory `/root/tinyproxy/docs'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/root/tinyproxy/docs'
make[2]: Leaving directory `/root/tinyproxy/docs'
make[1]: Leaving directory `/root/tinyproxy/docs'
Making install in m4macros
make[1]: Entering directory `/root/tinyproxy/m4macros'
make[2]: Entering directory `/root/tinyproxy/m4macros'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/tinyproxy/m4macros'
make[1]: Leaving directory `/root/tinyproxy/m4macros'
Making install in tests
make[1]: Entering directory `/root/tinyproxy/tests'
Making install in scripts
make[2]: Entering directory `/root/tinyproxy/tests/scripts'
make[3]: Entering directory `/root/tinyproxy/tests/scripts'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/root/tinyproxy/tests/scripts'
make[2]: Leaving directory `/root/tinyproxy/tests/scripts'
make[2]: Entering directory `/root/tinyproxy/tests'
make[3]: Entering directory `/root/tinyproxy/tests'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/root/tinyproxy/tests'
make[2]: Leaving directory `/root/tinyproxy/tests'
make[1]: Leaving directory `/root/tinyproxy/tests'
make[1]: Entering directory `/root/tinyproxy'
make[2]: Entering directory `/root/tinyproxy'
make[2]: Nothing to be done for `install-exec-am'.
test -z "/usr/local/share/doc/tinyproxy" || /bin/mkdir -p "/usr/local/share/doc/tinyproxy"
 /usr/bin/install -c -m 644 AUTHORS NEWS README README.md '/usr/local/share/doc/tinyproxy'
make[2]: Leaving directory `/root/tinyproxy'
make[1]: Leaving directory `/root/tinyproxy'
`

**Comment by rofl0r** [comment]
i am sorry that you ran into the annoying a2x issue. 

add this line to your config file `BasicAuth user password`
i think it's quite obivous when reading the comments in #129 ...

**Comment by rofl0r** [comment]
assuming issue is resolved due to lack of feedback.
