### ISSUE TITLE
tinyproxy: Could not create listening sockets.

### ISSUE THREAD

**Issue by qwelias** [tinyproxy/tinyproxy#183]
I've just installed the proxy and am trying to run it.
```
▶ tinyproxy -d                           
tinyproxy: Could not create listening sockets.
```
Same under sudo.
All setting are at default, 8888 port is free.
Could you please suggest what should I look for?

Sorry, I don't have much networking knowledge.

**Comment by rofl0r** [comment]
try another port, if that doesnt help run tinyproxy under strace

**Comment by qwelias** [comment]
Thanks, different port solved it for some reason.

**Comment by akarca** [comment]
Kill tinyproxy processes that listens the port: `fuser -k 8080/tcp`
