### ISSUE TITLE
tinyproxy log full request

### ISSUE THREAD

**Issue by gaborbernat** [tinyproxy/tinyproxy#184]
Now we only log the host, but not the entire request URL:

```CONNECT google.com:443 HTTP/1.1```

Would it be possible to log the entire request when Info level?

https://github.com/tinyproxy/tinyproxy/blob/c651664720d1fc21aeb36ca8dbb625a874af1d97/src/reqs.c#L117

**Comment by rofl0r** [comment]
no, it's not possible because CONNECT method works on raw TCP protocol layer. we can not look inside your encrypted HTTPS packets.

**Comment by giulianoc** [comment]
Hi,
no way to decrypt the part related to the full URL?
Regards
Giuliano
