### ISSUE TITLE
Tags on versions

### ISSUE THREAD

**Issue by Thulium-Drake** [tinyproxy/tinyproxy#185]
Hi devs!

I've got a small question, will tinyproxy receive new tagged versions in the future? As of this time the latest version is 1.8.4 which is dated december 2014.

Not having tags creates a problem with regards of lifecycle management as some distributions (like Debian) still carry arround 1.8.4 as the most recent version. In our environment we've noticed a couple of bugs in that version which have been long fixed in master.

For example in the changelog below it mentions that a bug where a SIGHUP causes tinyproxy to stop listening for new connections was fixed only quite recently (december 2017) in the Debian version. And we've known this issue for quite some time longer then that.

http://metadata.ftp-master.debian.org/changelogs//main/t/tinyproxy/tinyproxy_1.8.4-5_changelog:
> 
> tinyproxy (1.8.4-3) unstable; urgency=medium
> 
>   * Add sighup_hang.patch: Fix Tinyproxy ceasing to listen to connections
>     after it receives a SIGHUP, something that happens daily in our default
>     setup (closes: #880427).

Thanks for all the good work! (as we run a custom version at this time, it kicks ass :-) )

**Comment by rofl0r** [comment]
@obnoxxx ^

**Comment by obnoxxx** [comment]
@Thulium-Drake ok thanks. Just wanted to make sure that it is included before creating the next version.

The plan is to release the next major version (1.10.0). Or do you need a minor update with this patch (1.8.5)?

**Comment by Thulium-Drake** [comment]
We'd just like a new version that is considered stable :-)

At this time we are running a self-compiled version of the master (which functions just fine!). 

When is the new major version due?

**Comment by rofl0r** [comment]
https://github.com/tinyproxy/tinyproxy/commit/a662c11b8d106e0a2f3379b89739ed4770c5bbd3

**Comment by Thulium-Drake** [comment]
Hi @obnoxxx 

Thanks for tagging the release! :-) The Debian maintainer has picked it up in the meantime, so all the juicy new goodness should reach all Debian users in the near future as well
