### ISSUE TITLE
Debug req.c

### ISSUE THREAD

**Issue by rotragit** [tinyproxy/tinyproxy#188]
I need some help. I want to debug (trace, really) req.c. I've setup codelite and configured the project. It builds ok, it debug ok, but only the main loop. I've looked at child.c, seen I had to set TINYPROXY_DEBUG, look for the pid in the debug window and attach gdb to the pid. I've done like that (via the codelite gui) , set a breakpoint in child.c just after the sleep(10) but the program doesn't stop.

I have two question:
- it's ok to use codelite or you can suggest another IDE?
- what's the trick to trace into req.c?

Thank you!

romano

**Comment by rofl0r** [comment]
use the following gdb command:
```set follow-fork-mode child```
i can't suggest an IDE since i don't use one. using gdb in the terminal. but IIRC most gdb frontends allow to enter raw commands.

**Comment by rotragit** [comment]
Perfect! Thank you!
romano
