### ISSUE TITLE
upstream proxy authentication not working (syntax error in conf)

### ISSUE THREAD

**Issue by gaheinrichs** [tinyproxy/tinyproxy#189]
Hi, 

Would like to reopen #164 

upstream won't accept the type and it won't also work with authentication.

This does not work (`Unable to parse config file. Not starting.`):

- upstream http testproxy:8008 ".our_testbed.example.com"
- upstream http user:pass@testproxy:8008 ".test.domain.invalid"
- upstream http user:pass@testproxy:8008
- upstream user:pass@testproxy:8008

The only one that works is:

- upstream testproxy:8008

Thanks

**Comment by rofl0r** [comment]
that means you're not using latest git version, which you have to compile from source.

**Comment by gaheinrichs** [comment]
Verified works when compiling from source.

**Comment by jan-hudec** [comment]
For the benefit of whoever runs into this by search:

Up to and including release 1.10.0 only lowercase alphanumeric characters (and `.`, `-` and `_`) are accepted in username and password, but many configurations use more than that. That was changed in https://github.com/tinyproxy/tinyproxy/commit/dc41b3533326d745c65afaea4cb34c229a31d0c3 to accept anything except the separator, but it is not released as of early January 2019.
