### ISSUE TITLE
Status page error

### ISSUE THREAD

**Issue by antonluu** [tinyproxy/tinyproxy#193]
Status Page fails with error message:
'Failed to retrieve statistics from url: http://127.0.0.1:8888'
Changing stathost in /etc/config/tinyproxy to 192.168.1.1 or tinyproxy.stats only changed the display to 'Failed to retrieve statistics from url: http://192.168.1.1:8888' or 'Failed to retrieve statistics from url: http://tinyproxy.stats:8888'

On
Model	TP-Link Archer C2600
Architecture	ARMv7 Processor rev 0 (v7l)
Firmware Version	OpenWrt 18.06.0 r7188-b0b5c64c22 / LuCI openwrt-18.06 branch (git-18.219.52706-a49e4e4)
Kernel Version	4.14.54

**Comment by antonluu** [comment]
By DNS name, did you mean the DNS server on the whole network?  Since I am not sure how that would work, I edited localhost in etc/host
from: 127.0.0.1 local host
to: 192.168.1.1 router OpenWrt localhost
Rebooted the router and the Status Page in Tiny Proxy still comes up with:
'Failed to retrieve statistics from url: http://127.0.0.1:8888'

**Comment by antonluu** [comment]
What I can't understand is all the other report pages using CGI such as logs, etc... under http://192.168.1.1/cgi-bin/luci/admin/services/ are working, except for TinyProxy Status page.

**Comment by rofl0r** [comment]
1) invent a new name for your tinyproxy server
2) you edit your /etc/hosts and put that new name together with the IP of the server
3) you open your browser and go to http://newname:port/
