### ISSUE TITLE
Create a PAC file for Tinyproxy?

### ISSUE THREAD

**Issue by Benji-Collins** [tinyproxy/tinyproxy#196]
What would be the best way to create a PAC file for my Tinyproxy server. Is there some sort of auto generator I can/should use or do I need to write it by hand? Thanks.

**Comment by Benji-Collins** [comment]
I followed the examples given [here](http://community.lightspeedsystems.com/courses/pac-files-explained/) and it worked pretty well.

**Comment by Kolterdyx** [comment]
link is not available without an account :(

**Comment by rofl0r** [comment]
try web.archive.org
