### ISSUE TITLE
Forward traffic to a new port if it is not proxied traffic?

### ISSUE THREAD

**Issue by Benji-Collins** [tinyproxy/tinyproxy#197]
OpenVPN has a setting that allows non-vpn traffic to be forwarded to another port, effectively allowing two services to run on one port. Would it be possible to add a similar feature to Tinyproxy? This would allow someone to run the proxy on port 80 without having to disable Apache/Nginx.

**Comment by rofl0r** [comment]
even if it was possible to discern http proxy from http server traffic, which i doubt, i don't think it fits into the scope of functionality that tinyproxy should offer.
