### ISSUE TITLE
tinyproxy crashing when using large filter files

### ISSUE THREAD

**Issue by jasonculligan** [tinyproxy/tinyproxy#20]
Proxy dies when using a large filter file.  Issue can be replicated by using the "ads" domains list from "urlblacklist dot com" as the filter file.

**Comment by denzuko** [comment]
Why not just add those domain's IP to your host's null route table?

**Comment by obnoxxx** [comment]
crashing is bad an should be fixed. even if there is a workaround.

@jasonculligan could you describe in greater detail what you did to make TP crash?
