### ISSUE TITLE
Filter https but not http

### ISSUE THREAD

**Issue by sd65** [tinyproxy/tinyproxy#200]
Hello,

I would like to allow access to https://example.com but **not** to http://example.com.
I can't find any related option and putting the protocol in the filter file doesn't seems to work.

Can this be done with tinyproxy?
Regards,

Sylvain

**Comment by hplc** [comment]
Yes, you can do it.

From tinyproxy.conf manual:

       Filter
           Tinyproxy supports filtering of web sites based on URLs or domains.
           This option specifies the location of the file containing the
           filter rules, one rule per line.

       FilterURLs
           If this boolean option is set to Yes or On, filtering is performed
           for URLs rather than for domains. The default is to filter based on
           domains.

**Comment by rofl0r** [comment]
closing since the question was answered correctly.
