### ISSUE TITLE
error: Configure failed or did not finish!

### ISSUE THREAD

**Issue by saturn99** [tinyproxy/tinyproxy#204]
I first clone it: `git clone https://github.com/tinyproxy/tinyproxy`

and `cd tinyproxy/`

and when run `./autogen.sh` 

who this error:
```

+ cd .
+ aclocal -I m4macros
./autogen.sh: 11: ./autogen.sh: aclocal: not found
+ cd /home/ali/tinyproxy
+ set -
./configure
./autogen.sh: 21: ./autogen.sh: ./configure: not found

Configure failed or did not finish!
```
OS: Debian 9

**Comment by rofl0r** [comment]
try `autoreconf -i` instead of autogen.sh
you need to install automake, autoconf etc

**Comment by rofl0r** [comment]
alternatively you can download the release tarball in the "releases" page, it doesnt need autogen.
