### ISSUE TITLE
Upstream failback

### ISSUE THREAD

**Issue by lars18th** [tinyproxy/tinyproxy#208]
Hi,

I'm asking because I don't see the answer.

I have two different upstream HTTP proxies. One uses an _unlimited_ connection, the other uses a _metered_ connection. So, I like to use the first one... except when it is unavaliable.

How I can configure tinyproxy to support this environment?

Thank you!

**Comment by rofl0r** [comment]
that's not part of the functionality of tinyproxy. i also don't think it makes sense to implement it inside tinyproxy, it would make more sense as a standalone tool like "fallback-portredir", but i don't know if that exists yet. it would be relatively easy to implement though.

**Comment by lars18th** [comment]
> that's not part of the functionality of tinyproxy

Ah! Ok, then.

> it would be relatively easy to implement though.

That's what I think. In fact, I don't understand why tinyproxy doesn't have this functionality.

Thank you!

**Comment by rofl0r** [comment]
> In fact, I don't understand why tinyproxy doesn't have this functionality.

>  ... tinyproxy doesn't have this functionality.

>  ... tinyproxy ...

>  ... tiny ...

**Comment by lars18th** [comment]
Hi @rofl0r ,

Sorry! I don't like to be rude.
However, `tinyproxy` has a lot of functionalities... and a simple "round-robin" over a list of upstream proxies doesn't seem to be a "huge" functionality. Think only on this: With current implementation, what does `tinyproxy` when some upstream proxy fails? And what would you expect it to do?

I hope someone will try to include some enhancement targeting this.
Regards.

**Comment by rofl0r** [comment]
> Think only on this: With current implementation, what does tinyproxy when some upstream proxy fails? And what would you expect it to do?

it will fail, and that's exactly what i'd expect.

now, since you used the term "round-robin" this reminded me that [proxychains-ng](https://github.com/rofl0r/proxychains-ng) does have a round-robin mode. so you could theoretically use that to achieve your desired effect.

**Comment by rofl0r** [comment]
to be precise i mean `proxychains4 tinyproxy --foo --bar` instead of defining the upstreams in tinyproxy itself.

**Comment by lars18th** [comment]
Hi,

Any other idea to provide some "redundancy" for the upstream proxy?

My objective is _quite_ simple: Two different upstream proxies, master and slave. And use only slave when master fails. That's all!

Regards.

**Comment by rofl0r** [comment]
did you read my response above that you downvoted ?

> now, since you used the term "round-robin" this reminded me that proxychains-ng does have a round-robin mode. so you could theoretically use that to achieve your desired effect.

you can use proxychains-ng with round-robin mode. that means you run `proxychains4 tinyproxy -foo -bar` instead of `tinyproxy` and put the proxy configuration into proxychains.conf instead of tinyproxy.conf.

**Comment by lars18th** [comment]
> did you read my response above that you downvoted ?

Sure! But I can't use "proxychains4" as it's a preloader and I **can't** use it in my environment. Futhermore, I use tinyproxy with HTTP authentication for the upstream proxy. So, I can't use another tunneller without HTTP authentication support.

**Comment by lars18th** [comment]
> why exactly "can't" you use it in your environment ?

Because in my embedded system the __preloading__ function is forbidden!

Futhermore, if I use `tinyproxy` to _add_ client HTTP proxy authentication for a service that doesn't support it (but support HTTP proxies), why I need to _add_ the `proxychains-ng` tool? In this case I will use my service with proxychains directly. But, as I commented I can't.

**Comment by rofl0r** [comment]
> it would make more sense as a standalone tool like "fallback-portredir", but i don't know if that exists yet. it would be relatively easy to implement though.

https://github.com/rofl0r/rrredir

use that to redirect a local port to your proxies, and use the local ip:port as upstream proxy address in tinyproxy.

e.g. `rrredir -p 8000 proxy1.com:3128 proxy2.com:8080`

**Comment by lars18th** [comment]
> > it would make more sense as a standalone tool like "fallback-portredir", but i don't know if that exists yet. it would be relatively easy to implement though.
> 
> https://github.com/rofl0r/rrredir
> 
> use that to redirect a local port to your proxies, and use the local ip:port as upstream proxy address in tinyproxy (or directly in the browser's proxy settings).
> 
> e.g. `rrredir -p 8000 proxy1.com:3128 proxy2.com:8080`
> 
> only disadvantage of this approach: both destination proxies require the same credentials.

Thank you @rofl0r !
That's what I really need. :+1:

**Comment by rofl0r** [comment]
great. let me know if there are any issues with it.
