### ISSUE TITLE
Add INSTALL file

### ISSUE THREAD

**Issue by pnomolos** [tinyproxy/tinyproxy#21]
Minor, but right now there are a few references to "Please read the INSTALL file" even though an INSTALL file doesn't actually exist.

**Comment by denzuko** [comment]
https://github.com/tinyproxy/tinyproxy/blob/186bbc3efb4b47caac0b5e14465c97918c99e442/.gitignore#L1 shows that its autogenerated by gnu make/autotools.

So its the basic gnu oneliner: 
    autoconfig && ./configure && make all install

**Comment by obnoxxx** [comment]
The README file has intsallation instructions.
Where are these references? They should be fixed!

**Comment by pnomolos** [comment]
@obnoxxx 

- https://github.com/tinyproxy/tinyproxy/blob/186bbc3efb4b47caac0b5e14465c97918c99e442/configure.ac#L252
- https://github.com/tinyproxy/tinyproxy/blob/186bbc3efb4b47caac0b5e14465c97918c99e442/README#L24

**Comment by obnoxxx** [comment]
Okay... it seems that the addition of `foreign` as argument to `AM_INIT_AUTOMAKE` has stopped the system from adding INSTALL and COPYING file. I am not entirely sure why they were added. The purpose was to remove an old changelog file.

**Comment by obnoxxx** [comment]
Thanks for reporting this!
