### ISSUE TITLE
Tinyproxy removing headers

### ISSUE THREAD

**Issue by ivancalva** [tinyproxy/tinyproxy#210]
I have a shoutcast server 204.12.193.98:8415 I made a proxy to use port 80. 
If I do
wget -O firstrequest --user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36' http://204.12.193.98:8415/

ir returns a html page

wget -O secondrequest --user-agent='any-other-thing' http://204.12.193.98:8415/

It will return an audio stream.

But when i do the same requests with my proxy I always get the audio stream, is there some way I can make it so it will return the correct response in my proxy.

**Comment by rofl0r** [comment]
what's the relation between first connection, user agent, and shoutcast ?

**Comment by ivancalva** [comment]
I mean when i do a http request on my server it returns a website, when i use it as a stream source its returning the audio source, but with the proxy it always return as an audio source.

**Comment by rofl0r** [comment]
so how can the server determine whether you want the stream or the website ?

**Comment by rofl0r** [comment]
closing due to lack of feedback

**Comment by wvengen** [comment]
I have a similar issue of a Cookie header not being passed through.
Note that if an `Anonymous` keyword is present in the config, you need to whitelist headers.

**Comment by rofl0r** [comment]
> I have a similar issue of a Cookie header not being passed through.

in case that affects latest tinyproxy release (1.11.0) and you want to have that fixed, please open a new issue with some more details.
