### ISSUE TITLE
filter does not handle dots as expected

### ISSUE THREAD

**Issue by oliverkurth** [tinyproxy/tinyproxy#212]
The dot (```.```) in the filter rules is used to match any character. So for example ```....foo.bar``` matches ```www.foo.bar``` and ```www.foo.bar``` would also match ```wwwxfooybar```. This should be better documented, since it's not what a naive user would expect, and they might accidentally allow or block domains unintentionally. To correctly block/allow ```www.foo.bar``` you would need to set ```www\.foo\.bar```.

I would actually prefer it to be simpler. I think ```fnmatch()``` could be used instead of ```regexc()```.

**Comment by rofl0r** [comment]
thanks for pointing this out. could you propose the suggested documentation changes in a PR ? switching to fnmatch is probably out of scope at the moment, as we try hard to keep backwards compatibility.

**Comment by captn3m0** [comment]
To add to this, the https://github.com/tinyproxy/tinyproxy/blob/master/docs/filter-howto.txt file also seems pre-regex support and tells you otherwise.

**Comment by rofl0r** [comment]
https://github.com/tinyproxy/tinyproxy/commit/235b1c10a76a02f4837febcf84efd9b7edcd020e
