### ISSUE TITLE
listen on multiple interfaces

### ISSUE THREAD

**Issue by DieselDriver** [tinyproxy/tinyproxy#214]
If I try to add two lines of "Listen..." to my configuration file, only the latest line will be recognized by tinyproxy.

I want that tineproxy is listening on two interfaces.

Listen 192.168.1.1
Listen 192.168.2.1

Is this possible with one instance of tinyproxy?

**Comment by rofl0r** [comment]
i am not 100% sure, but i think generally the only way to listen on more than one interface at the same time is by using `0.0.0.0` as the listening address (i.e. listen on **all** interfaces), other than having multiple threads/processes listening on different addresses each. the latter is not supported by tinyproxy.

**Comment by TimWolla** [comment]
see https://github.com/tinyproxy/tinyproxy/issues/127#issuecomment-445852162

**Comment by rofl0r** [comment]
@DieselDriver would you mind trying out the patch from the PR above ^

**Comment by andrei-korshikov** [comment]
@rofl0r Works well (thank you!), but, unfortunately, it is not documented—both [man page](https://github.com/tinyproxy/tinyproxy/blob/cea0ebe657fed5d66fcfe4cc00d306cba0680323/docs/man5/tinyproxy.conf.txt.in#L50) and [config sample](https://github.com/tinyproxy/tinyproxy/blob/cea0ebe657fed5d66fcfe4cc00d306cba0680323/etc/tinyproxy.conf.in#L26) emphasize singular form ("listen only on one specific address", "bind to only one").

I think the ability to listen on multiple specific interfaces should be documented.

Also, I propose to change the config `Listen` sample from just `#Listen 192.168.0.1` to e.g.
```
#Listen 192.168.0.1
#Listen 127.0.0.1
#Listen ::1
```
for the consistency with `Allow`, `Anonymous`, `ConnectPort` and `ReversePath` samples.

**Comment by rofl0r** [comment]
@andrei-korshikov file a PR please ?
