### ISSUE TITLE
tinyproxy fails to start with brew services

### ISSUE THREAD

**Issue by akshaychhajed** [tinyproxy/tinyproxy#215]
I installed tinyproxy 1.10.0_1 via brew (running high sierra)
Tinyproxy fails to start when invoked via brew services
On investigating, plist file refers to incorrect binary location.
Binary is installed in #{prefix}/bin while plist refers to #{prefix}/sbin
https://github.com/Homebrew/homebrew-core/blob/794168ef6df43bd4961c0ef4e5edbf82848a81bf/Formula/tinyproxy.rb#L57

**Comment by rofl0r** [comment]
sorry, but we (tinyproxy maintainers) have no influence over 3rd party packaging. please file your issue on the homebrew repo.
