### ISSUE TITLE
Invalid header prevents processing request

### ISSUE THREAD

**Issue by anphsw** [tinyproxy/tinyproxy#220]
When proxied server in reverse proxy installation gives invalid header, processing all of the rest headers stops.
For example, invalid reply headers:

Cache-Control:no-cache,no-store
Prama:no-cache
sh:can't create dev/null: nonexistent directory
4177d0f6529d972bb3f51dbe9f9f7268c2d19c9faf7e8990964e3a624926b558
digest in image header
4177d0f6529d972bb3f51dbe9f9f7268c2d19c9faf7e8990964e3a624926b558
ap_name=voip, action=stop
Location: setup.cgi?next_file=galert.htm

Tinyproxy gives "Could not retrieve all the headers" error to client and headers stripped on first string not containing  ':'

Yes, there is bug on remote side, but all tested browsers and nginx as reverse proxy process request normally, and only stripping invalid headers.

So I think better to increase compatibility by not storing invalid headers, but processing request.
There is quick working patch for this: 5f618e09e7fd4cc9019cf9032bb2760140516d01

**Comment by rofl0r** [comment]
i agree. but i think attached patch would work better, because i think yours will produce a memleak.
could you test it please ? (need to undo yours first though)

```diff
@@ 655 src/reqs.c
                if (CHECK_CRLF (line, linelen) || !CHECK_LWS (line, linelen)) {
                        if (!double_cgi
                            && len > 0
                            && add_header_to_connection (hashofheaders, header,
                                                         len) < 0) {
                                safefree (header);
                                safefree (line);
-                                return -1;
+                                continue;
                        }
                        len = 0;
                }
```

**Comment by anphsw** [comment]
@rofl0r 
I tested your patch and it is not working. Instead of "Could not retrive all headers" tinyproxy gives ERR_EMPTY_RESPONSE at least on chrome.

**Comment by rofl0r** [comment]
```diff
@@ 655 src/reqs.c
                if (CHECK_CRLF (line, linelen) || !CHECK_LWS (line, linelen)) {
                        if (!double_cgi
                            && len > 0
                            && add_header_to_connection (hashofheaders, header,
                                                         len) < 0) {
                                safefree (header);
                                safefree (line);
-                                return -1;
+                                len = 0;
+                                continue;
                        }
                        len = 0;
                }
```
there was a bug, len needs to be set to zero after freeing the header. could you please try again with this patch ? it worked on my end.

**Comment by anphsw** [comment]
Not working again.
Some headers passed:
Cache-Control:no-cache,no-store
Prama:no-cache

Invalid headers not present and headers after invalid also not present.

**Comment by rofl0r** [comment]
hi @anphsw, sorry for the delay. would you mind opening a PR with your patch ?

**Comment by anphsw** [comment]
Ok, I will open PR.
I running this patch from Jan 1 with no errors.

**Comment by rofl0r** [comment]
thanks, let's keep this open until patch merge time

**Comment by rofl0r** [comment]
thanks, finally merged your PR.
