### ISSUE TITLE
need log with complete URLs (HTTP)

### ISSUE THREAD

**Issue by th-s-op** [tinyproxy/tinyproxy#223]
I want to use tinyproxy to monitor some devices' HTTP traffic. The ideal log file would contain the following data in a single line:

- requesting client IP
- request method
- requested full URL

ie.
192.168.0.100 GET http://google.com/search?q=tinyproxy

Would it be possible to implement a config option which when used adds another log line type?

Looking at the log file, it is event driven, and I feel the above information can be derived by massive file parsing. If that's my only choice, my question would be how to do it correctly:
- parse the log file for each PID separately because only within one PID, the log is serial and the file descriptors are defined
- look for a "Connect" to get the client IP
- from there, find the next "Request" line to get the URI (before next "Connect")
- from there, find the next "Established" line to get the host name (before next "Connect" or "Request")
- deal with all the exceptions, ie "Proxying refused" which magically contains the complete URL :-)

**Comment by rofl0r** [comment]
i doubt this makes sense in the age of HTTPS, where > 90% of connections use the CONNECT method, which in turn knows nothing else than the destination IP/hostname.

**Comment by giulianoc** [comment]
Hi,
I'm sorry, I do not know about the CONNECT method.
I need to get the complete URL in case of an HTTPS GET request.
Why is it not possible to get this information in case of the CONNECT method?
Best regards
Giuliano

**Comment by rofl0r** [comment]
> I do not know about the CONNECT method

then why not inform yourself ?

> I need to get the complete URL in case of an HTTPS GET request.

https://www.youtube.com/watch?v=oI_ZhFCS3AQ
