### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by bober2000** [tinyproxy/tinyproxy#225]
I'm trying to setup healthcheck on AWS EC2 instances. It is using HTTP for checking node status, but I cant get any answer from tinyproxy. Can I setup StatHost for example at separate url - like proxy_ip:8888/stats - than I could use this page as healthcheck

**Comment by bober2000** [comment]
My try was setting 
StatHost "tinyproxy.stats"
ReversePath "/stats/"	"tinyproxy.stats"
But trying to curl poxy_ip:8888/stats not working

**Comment by rofl0r** [comment]
tinyproxy uses the name configured under "StatHost" to detect whether one wants to retrieve the statspage, or use the regular proxy functionality.
that means you need to setup a separate hostname pointing to that ip that you only use for the stats check. you can do this via DNS, /etc/hosts, etc.

**Comment by bober2000** [comment]
@rofl0r yes. But in AWS settings I can't set LB health checker to use proxy(see screenshot)
![image](https://user-images.githubusercontent.com/5284995/52519877-dbf60600-2c6a-11e9-9bc6-9e1288106b2a.png)
So having separate url like /stats or /health could be an option

**Comment by bober2000** [comment]
Of course I could add simple web server - and make simple page check - but this is additional software - as this is minimal instance it is not preferable solution

**Comment by rofl0r** [comment]
ok. reopening this, maybe someone understands the issue

**Comment by sharkannon** [comment]
You could always just change it to a TCP check.. I know not as robust, but it'll tell you if the correct port is open and accepting TCP requests.

**Comment by bober2000** [comment]
@sharkannon for Network LB - only HTTP is allowed
![image](https://user-images.githubusercontent.com/5284995/55750942-21596880-5a4d-11e9-9782-45392b1a7839.png)

**Comment by printedheart** [comment]
Create a TCP LB instead of an ALB
![image](https://user-images.githubusercontent.com/11428184/56842083-e3c74e80-6846-11e9-8302-dc8a209dbb0a.png)

**Comment by wlodi83** [comment]
Hello,

I have exactly the same problem with TCP Healthcheck on AWS:


```CONNECT   Jun 26 10:06:08 [5887]: Connect (file descriptor 6): ec2-54-x-x-x.ap-southeast-2.compute.amazonaws.com [54.x.x.x]
ERROR     Jun 26 10:06:08 [5887]: read_request_line: Client (file descriptor: 6) closed socket before read.
ERROR     Jun 26 10:06:08 [5887]: Error reading readble client_fd 6```

Do you have idea how to improve it?

**Comment by thaiphv** [comment]
I also ran into the same issue where TCP healthchecks didn't work with tinyproxy as it was flooded with errors as above.

**Comment by rofl0r** [comment]
can someone provide a pcap (made with tcpdump) that has such a health-check "conversation" in it?

**Comment by thaiphv** [comment]
[healthcheck.pcap.gz](https://github.com/tinyproxy/tinyproxy/files/3360976/healthcheck.pcap.gz)

**Comment by rofl0r** [comment]
thanks. we can see that the health-check server simply opens a connection, but doesn't send any data, to which tinyproxy responds with "bad request".
from that, the health-check can tell that the service is up and running.
so it looks like a bug that it doesn't.
