### ISSUE TITLE
Commercial Support

### ISSUE THREAD

**Issue by blaxxton** [tinyproxy/tinyproxy#23]
Hi 

Is there a commercial support available ?
TinyProxy is listed as commercial software in wikipedia but I am not seeing any commercial support on gitub for TinyProxy.

Thanks

**Comment by denzuko** [comment]
@blaxxton Wikipedia is not the true source of any knowledge. If one checks out the development team committing code to this repo, the majority of them work at RedHat and/or cPanel. So there's your "commercial support".

Maybe one of the official devs on this project could chime in on this and close the issue.

**Comment by obnoxxx** [comment]
Hi,
I am trying to maintain tinyproxy in my spare time.
I am not aware of any commercial support...
What is the question?
Cheers - Michael

**Comment by blaxxton** [comment]
Hi Michael,
I have not tried it yet but commercial support is a must have for some companies to use either open source or proprietary software.
I was just curious in case of any problem who would help us to fix the issue.either bug or configuration issue.
Thanks

**Comment by obnoxxx** [comment]
If you are using an enterprise linux distribution like redhat or suse, you could try if support for TP is covered there. But there is no commercial support company for TP specifically, that I know of.

**Comment by obnoxxx** [comment]
Closing this issue. Please reopen or raise a new one if there are more questions.
