### ISSUE TITLE
Basic realm string editable in config file

### ISSUE THREAD

**Issue by uomoukko** [tinyproxy/tinyproxy#235]
Is it possible to change Basic realm, default=Tinyproxy
to something else using configuration file?

WORKAROUND.... to set a fixed string "MY_SECRET_SERVER"
html-error.c  line 169:
        const char auth_str[] =
            "Proxy-Authenticate: Basic realm=\""
           "MY_SECRET_SERVER" "\"\r\n";

Thank you.

**Comment by n3mxnet** [comment]
giving a real explanatory proxy password prompt has not been achieved in 30 years of www & firefox

**Comment by rofl0r** [comment]
this should be super easy to implement. PR welcome.
i'd suggest to add a config option BasicAuthRealm for this.

**Comment by Gruummy** [comment]
@rofl0r 
Hi .... i am a absolut newbee in c ... so please do not wonder ... i created a pull request for this issue.
... which should exactly do what should have been done.

Would really be great if it can be reviewed / commented if needed / merged.

I want to do a few more small changes ... and this is my first introduction of me to you ...

**Comment by Gruummy** [comment]
Here the link to the pull request with the most current commits after the first review of it

https://github.com/tinyproxy/tinyproxy/pull/547
