### ISSUE TITLE
Failed to start tinyproxy.service: Unit tinyproxy.service failed to load: No such file or directory.

### ISSUE THREAD

**Issue by yangjiafei** [tinyproxy/tinyproxy#236]
service tinyproxy start
have a error？
Failed to start tinyproxy.service: Unit tinyproxy.service failed to load: No such file or directory.

**Comment by yangjiafei** [comment]
/usr/local/etc/tinyproxy/tinyproxy.conf

enable LogFile ...

**Comment by rofl0r** [comment]
sorry, distro-specific service startup infrastructure is beyond the scope of tinyproxy development. please report the bug to the distribution you're using and consider switching to a systemd-less distribution.
meanwhile, you can start tinyproxy manually in the foreground like so: `tinyproxy -d -c /path/to/tinyproxy.conf`. without -d tinyproxy will daemonize and background itself.
