### ISSUE TITLE
[BUG] getaddrinfo crashes the thread answering the request on MacOS.

### ISSUE THREAD

**Issue by robertosgm** [tinyproxy/tinyproxy#237]
The thread listening to the request crashes and gets terminated everytime getaddrinfo is called on the opensock function.
This is happening on MacOS Mojave 10.14.4.

Reverting to using gethostbyname solves the issue.

**Comment by robertosgm** [comment]
It is working properly on branch: 
https://github.com/tinyproxy/tinyproxy/pull/218

**Comment by rofl0r** [comment]
(OP experienced the issue with 1.10.0)

**Comment by rofl0r** [comment]
closed by b935dc85c3fca51de8e131d6aa2047f8a0404f0c
