### ISSUE TITLE
Very Slow with Multiple Instances and Load Balancer

### ISSUE THREAD

**Issue by srinivasaravind5** [tinyproxy/tinyproxy#241]
When we try to route multiple instances, the tiny proxy is very slow, it works ok when the number of instances is less than 4 if it's more than 8 or so its kind of hangs

**Comment by rofl0r** [comment]
did you try the threads branch from my pr #218 ?

**Comment by srinivasaravind5** [comment]
No I havent

**Comment by rofl0r** [comment]
you should

**Comment by rofl0r** [comment]
should by fixed by b935dc85c3fca51de8e131d6aa2047f8a0404f0c
