### ISSUE TITLE
Failed to run after make install on ubuntu 16.04

### ISSUE THREAD

**Issue by MRezaNasirloo** [tinyproxy/tinyproxy#251]
I've built and installed tinyproxy 1.10.0 on ubuntu 16.04 however, I couldn’t run it successfully
```
# tinyproxy
-bash: /usr/sbin/tinyproxy: No such file or directory
```
I've downloaded  the 1.10.0 tar.gz and installed it without any errors using below commands
```
./configure
make
make install
```
Also I tried an installation with ./autogen.sh but got the same result
is there anything that I've missed?

**Comment by rofl0r** [comment]
> is there anything that I've missed?

--prefix

**Comment by MRezaNasirloo** [comment]
@rofl0r `tinyproxy -v` had the same result :/

**Comment by rofl0r** [comment]
you misunderstand what --prefix means. certainly not pointing to your bin directory.
hint: try /usr or look to what it is set by default, and then go look there for your files. maybe you can even read what's printed when you run the `make install` command :-p

**Comment by MRezaNasirloo** [comment]
Thanks for response, I tried it with `/usr` and `/` and a couple of other dirs, the thing is the make file doesn't put the binary in `sbin` folder, it makes a `what I described in --prefix arg + /bin` directory and puts the tinyproxy executable there

I actually  read the output of `make install` and `INSTALL` file
You know I can run the tinyproxy, but I don't understand why it requires to be in `/usr/sbin/tinyproxy` dir why `/usr/local/bin/tinyproxy` is not ok? after all its in the $PATH

**Comment by rofl0r** [comment]
if you want it in /usr/sbin, maybe try --bindir

> And why there isn't a /etc/init.d/tinyproxy

because management of services is distro-specific.
