### ISSUE TITLE
Origin of "Could not establish a connection to 0.0.0.0" errors?

### ISSUE THREAD

**Issue by gilgongo** [tinyproxy/tinyproxy#255]
Apologies for the possibly stupid question, but if I'm seeing a lot of "Could not establish a connection to 0.0.0.0" and "Could not establish a connection to 255.255.255.255" in my tinyproxy logs, does that indicate anything I should be concerned about?

**Comment by rofl0r** [comment]
nothing to worry about, but you may want to try to figure out which app it's doing it.
