### ISSUE TITLE
Add IPv6 Allow in default

### ISSUE THREAD

**Issue by ajmas** [tinyproxy/tinyproxy#256]
Currently the example file only has `Allow 127.0.01`. We should also add `Allow ::1` to support the IPv6 scenario.

I am using macOS X and it was failing, giving the error "The administrator of this proxy has not configured it to service requests from your host". 

Ensuring my configuration was as below resolved things. This should probably be the default?

```
Allow 127.0.01
Allow ::1
```

**Comment by rofl0r** [comment]
probably, yeah. care to make a PR ?

**Comment by ajmas** [comment]
I'll do that

**Comment by LumingSun** [comment]
@ajmas  Hi, any idea how to set ipv6 proxy on the client machine (Ubuntu)? I tried ```export http_proxy=http://[ipv6_addr]:port/``` , ```export http_proxy=http://\[ipv6_addr\]:port/```, and ```export http_proxy=http://ipv6_addr:port/```, but none of them work.

**Comment by ajmas** [comment]
@LumingSun it has been a while since I have used this, so I’ll need to reinstall to validate, though the first thing I’d check is if there is an IPv6 connection between you and the proxy host.

**Comment by LumingSun** [comment]
@ajmas Thank you for your reply, I have ipv6 connection between my local machine and the proxy host. And I have figured out how to use ipv6 proxy on linux. It should be ```export http_proxy=http://[ipv6_address]:port/```
```export https_proxy=http://[ipv6_address]:port/```. I didn't success the first time because I tested using git clone and I set a wrong git proxy. Thanks again.
