### ISSUE TITLE
writebuff: write() error "Broken pipe" on file descriptor

### ISSUE THREAD

**Issue by Jiri-Mihal** [tinyproxy/tinyproxy#258]
Hi,

after several minutes of flawless usage of Tinyproxy I start to get the following error: "writebuff: write() error "Broken pipe" on file descriptor" Then Tinyproxy doesn't return any response to client. Any idea how to solve this issue?

Thank you,

Jiri

**Comment by rofl0r** [comment]
which version ? please try 1.10.0 release or git master if you still use 1.8.x

**Comment by Jiri-Mihal** [comment]
tinyproxy 1.10.0-git-8-gc2d3470

**Comment by rofl0r** [comment]
does this happen with your own web framework ? broken pipe means that the connection was interrupted (for example if the prog on one of the connected ends would get a SIGINT or crashed etc)

**Comment by Jiri-Mihal** [comment]
I have 15s connection timeout. It drops the connection when response is too slow. But why the response from Tinyproxy becomes so slow? I stream files using the NodeJS. There are no memory leaks, no CPU overload, bandwidth limit etc. When I turn off NodeJS and keep running only Tinyproxy (TP) then this error never occurs. Can NodeJS somehow block response from TP? Interesting is, that connection to TP is always immediate, just the response is slow.

**Comment by Jiri-Mihal** [comment]
Just to be more clear. I run TP and NodeJS on the same server. Unfortunately I can't separate them.

**Comment by Jiri-Mihal** [comment]
I tried to write proxy in NodeJS to test if the problem is related to TP or to NodeJS. Symptoms are the same. It means the problem is not related to TP. Thank you for your help.

**Comment by rofl0r** [comment]
the slowness to respond could be due to DNS resolution done for logging purposes, which was removed in this PR https://github.com/tinyproxy/tinyproxy/pull/218

**Comment by Jiri-Mihal** [comment]
I experience the same issue even without the Tinyproxy. So it's unlikely. [Read more here](https://github.com/nodejs/node/issues/29271).
