### ISSUE TITLE
Can you add a BindRandom feature?

### ISSUE THREAD

**Issue by pengqi** [tinyproxy/tinyproxy#26]
The BindSame feature is very useful and easy to use(While squid needs to add many tcp_outgoing_address lines for all interfaces)!

Can you add another feature "BindRandom"?
If enabled, tinyproxy will bind the outgoing connection to a random interface(eth0, eth1, eth2, eth3, ....).

**Comment by obnoxxx** [comment]
What would be the benefit?
And would that be random each time or once?

**Comment by johnz0r** [comment]
Hello,

I would like this feature too ! 

My personal benefit would be this kind of pattern:
Let's imagine i use one instance of tinyproxy, binded on a /24 or more IP address (aka iface). On my project i need to scrap Internet, i would love to use gateway.myproject.com as proxy in curl and tinyproxy totally randomize outgoing interface. That may prevent the scrapper being banned.

Obviously i can use "BindSame yes" and my application could hold the whole IP address list, but I find it easier to maintain if it is the daemon that manages it. 

Let me know,
Thank you :)

**Comment by pengqi** [comment]
I have many ADSL connections(more than 100) ,  the IP address of each is changing aperiodically. With"BindRandom" i can ignore that.

- And would that be random each time or once?
Choise random outgoing address for each new request.

**Comment by naroga** [comment]
I too would love this feature. Having tinyproxy behave as a "proxy gateway" (sorting through many outgoing interfaces, randomizing my traffic) would be amazing.

**Comment by rofl0r** [comment]
imo this is outside the scope of tinyproxy functionality, but with the new upstream proxy capabilities you could just redirect requests to a very simple socks5 proxy to shuffle the outgoing requests. for example there is https://github.com/rofl0r/microsocks/blob/master/sockssrv.c a socks5 server in 400 lines and i guess it'd be much easier to add this functionality to something like that, or some python script.
