### ISSUE TITLE
Writable /tmp

### ISSUE THREAD

**Issue by geekdrive** [tinyproxy/tinyproxy#261]
Can you please make:
heap.c
    static const char *shared_file = "/tmp/tinyproxy.shared.XXXXXX";
child.c
    char lock_file[] = "/tmp/tinyproxy.servers.lock.XXXXXX";
configurable (I can patch them for now) for those of us who don't have a globally writable /tmp directory. I would add tinyproxy to the group that can write to the /tmp directory but tinyproxy drops all secondary groups.

There is no way for tinyproxy to run without a globally writable /tmp.

**Comment by rofl0r** [comment]
iirc threads branch which is about to become the new master soon, already works without /tmp.

**Comment by rofl0r** [comment]
obsoleted by b935dc85c3fca51de8e131d6aa2047f8a0404f0c
