### ISSUE TITLE
[Documentation] add filter file howto to website

### ISSUE THREAD

**Issue by ghost** [tinyproxy/tinyproxy#262]
I didn't see any links to [the filter file how-to](https://github.com/tinyproxy/tinyproxy/blob/master/docs/filter-howto.txt) on the website or in the manpages. It would be helpful for people who mainly want to use tinyproxy for filtering websites rather than as a proxy rewriting tool.

**Comment by talishka** [comment]
Yes, i second that idea.

**Comment by rofl0r** [comment]
please file a PR on the website repo, thanks

**Comment by rofl0r** [comment]
closed by c4dc3ba007fe34d6b7704ffb5ec812a436c326e7
