### ISSUE TITLE
Configure tinyproxy for custom ssl certificate and port

### ISSUE THREAD

**Issue by Poimen** [tinyproxy/tinyproxy#263]
We are using tinyproxy to connect to a SOAP service that uses a custom CA certificate that is private key protected on a custom port. When we connect directly without a proxy, using SoapUI, the connection is established correctly (so we know that the setup of the cert is correct). 

However, when we route through tinyproxy, it reports a ssl handshake failure:
```
ERROR:javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```
We have configured tinyproxy with `ConnectPort 4556`  (the port for SSL connection), but it seems like tinyproxy wants to check the certificate, or something.

Is it possible to get tinyproxy to just pass the data through to the service listening on port `4556` that has the certificate and private key?

**Comment by Poimen** [comment]
Does tinyproxy just pass the data straight through?

Also do you have an idea of what I would be looking for on wireshark?

**Comment by rofl0r** [comment]
> Does tinyproxy just pass the data straight through?

if the connect method is used as it should, yes.

> Also do you have an idea of what I would be looking for on wireshark?

of what happens during a request between client, proxy, and backend.

**Comment by Poimen** [comment]
We have decided to open the external port to our environment rather than routing through tinyproxy. Closing the ticket.
