### ISSUE TITLE
Tinyproxy not binding to all interfaces?

### ISSUE THREAD

**Issue by gilgongo** [tinyproxy/tinyproxy#264]
I have an Ubuntu 16.04 server using Tinyproxy 1.8.3-3ubuntu1 which has an IPv6 dynamic address routing to the Internet, and a static IPv4 address on the LAN with no Internet routing.

By default, Tinyproxy only binds to one interface (which doesn't have Internet routing):

```
~$ netstat -plunt | grep tiny
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      2231/tinyproxy
```
Is there a way I can get it to bind to the IPv6 interface?

**EDIT**: I notice that installing Tinyproxy on an Ubuntu 18.04 machine running v1.8.4-5 in a similar network config (although the IPv6 address is static), Tinyproxy **does** bind to both the IPv4 and IPv6 interfaces. Is this therefore a version thing?

**Comment by rofl0r** [comment]
> Is this therefore a version thing?

apparently. you should always try at least the latest release version of a product (in this case 1.10 or even better, git master) before opening a bug report/issue. i guess it could also help lobbying debian/ubuntu to finally update their package (the release is out since almost a year).
