### ISSUE TITLE
Redirecting an external http domain to local webserver

### ISSUE THREAD

**Issue by will-code-for-pizza** [tinyproxy/tinyproxy#265]
Hi folks,
I want to redirect an external domain to my local webserver.
For example:

cloud-images.ubuntu.com:80  -->  localhost:80/test/

Is this possible with tinyproxy ?

Regards and thanks al lot.
:-)

**Comment by will-code-for-pizza** [comment]
Another alternative could be 
cloud-images.ubuntu.com:80 --> localhost:8888/test/

**Comment by rofl0r** [comment]
yes, this is called "reverse proxy". check the docs on how to set it up.

**Comment by will-code-for-pizza** [comment]
Sorry, but the manpage only describes the possibility to access example.com, using http://localhost:8888/example/.
I am searching for the opposite solution.

Accessing http:/localhost:8888 via example.com

Regards.
