### ISSUE TITLE
Tinyproxy Not Forwarding HTTPS requests

### ISSUE THREAD

**Issue by greg5678** [tinyproxy/tinyproxy#267]
I just installed tinyproxy on a Linux box and am currently using a MacOS client running Firefox to connect to tinyproxy. Tinyproxy successfully proxies the HTTP requests but I haven't been able to get it to proxy HTTPS traffic. Any suggestions?

**Comment by rofl0r** [comment]
use latest tinyproxy release, which has a proper configuration for CONNECT method

**Comment by greg5678** [comment]
I'm on tinyproxy 1.10. Is that have issues with the CONNECT method with HTTPS?

**Comment by rofl0r** [comment]
no, but you need to use the default settings which enable CONNECT method on any port

**Comment by greg5678** [comment]
Great. The issue is resolved.
