### ISSUE TITLE
opensock: Could not retrieve info for x

### ISSUE THREAD

**Issue by wickedsp1d3r** [tinyproxy/tinyproxy#269]
Information:
```
$ tinyproxy -v
tinyproxy 1.10.0-git-8-gc2d3470

$ tinyproxy -h
Usage: tinyproxy [options]

Options are:
  -d        Do not daemonize (run in foreground).
  -c FILE   Use an alternate configuration file.
  -h        Display this usage information.
  -v        Display version information.

Features compiled in:
    Filtering
    Transparent proxy support
    Upstream proxy support

For support and bug reporting instructions, please visit
<https://tinyproxy.github.io/>.
```

Problem:
```
$ curl --head https://github.com
HTTP/1.0 500 Unable to connect
Server: tinyproxy/1.10.0-git-8-gc2d3470
Content-Type: text/html
Connection: close

curl: (56) Received HTTP code 500 from proxy after CONNECT
```
Syslog says:
```
opensock: Could not retrieve info for github.com
```

What is the cause of this problem?
How could I get my HTTP requests working?
Any help would be appreciated.

**Comment by rofl0r** [comment]
1) show your config (with comment lines omitted)
2) it would be helpful to have a pcap taken on the server running the proxy during this transaction

**Comment by wickedsp1d3r** [comment]
This is my config
```
Allow 127.0.0.1
Anonymous "Accept"
Anonymous "Accept-Charset"
Anonymous "Accept-Encoding"
Anonymous "Accept-Language"
Anonymous "Authorization"
Anonymous "Cache-Control"
Anonymous "Connection"
Anonymous "Content-Length"
Anonymous "Content-Type"
Anonymous "Cookie"
Anonymous "Host"
Anonymous "If-Modified-Since"
Anonymous "If-None-Match"
Anonymous "TE"
ConnectPort 443
ConnectPort 563
DefaultErrorFile "/usr/share/tinyproxy/default.html"
DisableViaHeader Yes
Filter "/usr/local/etc/tinyproxy/filter"
Group tinyproxy
Listen 127.0.0.1
LogLevel Warning
MaxClients 100
MaxRequestsPerChild 0
MaxSpareServers 20
MinSpareServers 5
# PidFile "/run/tinyproxy/tinyproxy.pid"
Port 8888
StartServers 10
StatFile "/usr/share/tinyproxy/stats.html"
Syslog On
Timeout 600
User tinyproxy
ViaProxyName "tinyproxy"
```

**Comment by rofl0r** [comment]
try with the 2 connectport items removed

**Comment by wickedsp1d3r** [comment]
I installed the latest stable version (1.10.0) and changed `LogLevel` to `Info`.
```
$ curl --head https://github.com -x http://localhost:8888

HTTP/1.0 500 Unable to connect
Server: tinyproxy/1.10.0
Content-Type: text/html
Connection: close

curl: (56) Received HTTP code 500 from proxy after CONNECT
```
The log shows this:
```
CONNECT   Oct 26 17:20:08 [18320]: Connect (file descriptor 6): localhost.localdomain [127.0.0.1]
CONNECT   Oct 26 17:20:08 [18320]: Request (file descriptor 6): CONNECT github.com:443 HTTP/1.1
INFO      Oct 26 17:20:08 [18320]: No upstream proxy for github.com
INFO      Oct 26 17:20:08 [18320]: opensock: opening connection to github.com:443
ERROR     Oct 26 17:20:08 [18320]: opensock: Could not retrieve info for github.com
INFO      Oct 26 17:20:08 [18320]: no entity
```
Removing `ConnectPort` from the config did not help.

**Comment by rofl0r** [comment]
the message you get is from sock.c line 100. it happens when getaddrinfo fails. why does it fail? is your DNS setup broken?

**Comment by wickedsp1d3r** [comment]
> is your DNS setup broken?

I am using a local DNS server. How to configure this with Tinyproxy?

I am using the same setup on one of my other computers and there Tinyproxy works just fine with roughly same configuration.

**Comment by rofl0r** [comment]
> How to configure this with Tinyproxy?

tinyproxy uses libc interfaces for dns resolution. so whatever is set globally will be used (/etc/resolv.conf).

> I am using the same setup on one of my other computers and there Tinyproxy works just fine with roughly same configuration.

if getaddrinfo() fails, dns setup is broken for the machine. so `host github.com` should fail as well.

**Comment by wickedsp1d3r** [comment]
> so host github.com should fail as well.

Seems like it is working.
```
$ host github.com
github.com has address 140.82.118.3
github.com mail is handled by 5 ALT1.ASPMX.L.GOOGLE.com.
github.com mail is handled by 1 ASPMX.L.GOOGLE.com.
github.com mail is handled by 10 ALT4.ASPMX.L.GOOGLE.com.
github.com mail is handled by 5 ALT2.ASPMX.L.GOOGLE.com.
github.com mail is handled by 10 ALT3.ASPMX.L.GOOGLE.com.
```
And
```
$ dig github.com

; <<>> DiG 9.10.2-P4 <<>> github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55994
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             256     IN      A       140.82.118.3

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Oct 30 11:52:52 EET 2019
;; MSG SIZE  rcvd: 55
```

**Comment by rofl0r** [comment]
> I have disabled IPv6 connections

how/where ?

> Could it have an impact on this problem?

well possible. could you try to turn it temporarily on to see whether it would resolve the issue ? that'd give more clues to find the bug.

**Comment by wickedsp1d3r** [comment]
The local DNS server I am running is blocking AAAA queries.
I disabled it to check if it is causing this problem, but it had no effect.

I turned off all my `iptables` rules too, but this had no effect on Tinyproxy's operation.

**Comment by rofl0r** [comment]
maybe set a breakpoint with gdb on getaddrinfo to see what's going on.

**Comment by wickedsp1d3r** [comment]
I have figured out that if I start it directly, it works, but as a `systemd` service Tinyproxy spits out these 500 errors.

So the problem is not in Tinyproxy but in `systemd`.
Here's the service file
```
[Unit]
Description=Tinyproxy Web Proxy Server
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/tinyproxy -d
Restart=always

[Install]
WantedBy=multi-user.target
```
Does it need some kind of network directives? Any ideas to help me out with this? I am not so familiar with this stuff. Thanks a lot!

**Comment by masi** [comment]
Try compiling tinyproxy yourself:

In https://github.com/tinyproxy/tinyproxy/blob/master/src/sock.c you have to change the lines 89/99
```
log_message (LOG_ERR,
                             "opensock: Could not retrieve info for %s", host);
```
to look like this:
```
log_message (LOG_ERR,
                             "opensock: getaddrinfo failed for %s:%d: %s", host, port, gai_strerror(s));
```

See http://man7.org/linux/man-pages/man3/gai_strerror.3.html

Maybe this will help you to find the error.

**Comment by rofl0r** [comment]
could be this then: https://www.linode.com/community/questions/17081/dns-stops-resolving-on-ubuntu-1804

**Comment by rofl0r** [comment]
@masi care to provide a PR changing that line? it seems useful.

**Comment by masi** [comment]
@rofl0r done

**Comment by wickedsp1d3r** [comment]
I finally got everything working using a `systemd` user service. I am using the following service file

```
[Unit]
Description=Lightweight HTTP(S) proxy daemon
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/tinyproxy -d
Restart=always

[Install]
WantedBy=default.target
```

Thanks for all the help!
