### ISSUE TITLE
Tinyproxy and Cloudflare unable to connect

### ISSUE THREAD

**Issue by greg5678** [tinyproxy/tinyproxy#270]
I'm using Tinyproxy and `cloudflared` to try and access tinyproxy from outside my home network. I'm running on a CGNAT so I don't have my own public ip address. To solve this issue I thought of using [`cloudflared`](https://blog.cloudflare.com/a-free-argo-tunnel-for-your-next-project/), but when I looked at cloudflared's logs I kept seeing `ERRO[0174] HTTP request error                            error="Error proxying request to origin: read tcp xxx.xxx.xxx.xxx:36484->xxx.xxx.xxx.xxx:8888: read: connection reset by peer"`?

**Comment by rofl0r** [comment]
i don't know about this setup, but you could try https://github.com/rofl0r/nat-tunnel

**Comment by greg5678** [comment]
I believe the issue has to do with Tinyproxy and not cloudflared. I ran the `cloudflared` command `./cloudflared tunnel --url http://xxx.xxx.xxx.xxx:8888` and used tcpdump to listen on port 8888 and I could see traffic coming from the machine running cloudflared.

**Comment by rofl0r** [comment]
if you keep opening and closing issues, without comment, and in one case even without response, i'll consider that as spam and will block you.

**Comment by greg5678** [comment]
I'm sorry, I will not do that again.
