### ISSUE TITLE
How to reload configuration for running daemon

### ISSUE THREAD

**Issue by erenoglu** [tinyproxy/tinyproxy#278]
is there a way to force the daemon to reload its configuration? Or maybe does it do it automatically if the configuration file is changed?

I tried to send HUP signal to the first pid, it did nothing. (kill -1).

I need it to change the upstream setting when I roam between office with an upstream proxy and home where there is no proxy.

**Comment by rofl0r** [comment]
sigusr1

**Comment by erenoglu** [comment]
Hi again, this signal does not work, it kills the deamon. I tried:
kill -10 pid  
kill -sigusr1 pid 
kill -USR1 pid

pid being the parent process pid, not the spawn forks. Does not make any difference, they all kill the parent process of the deamon and the other forks become separated from the parent process. Any ideas how to re-read the configuration file?

**Comment by rofl0r** [comment]
which tinyproxy version are you using ?

**Comment by erenoglu** [comment]
Hi, I think I was using latest release v1.10.0

**Comment by Xon** [comment]
v1.10.0 `sighub` triggers config (including closing/opening log files)

**Comment by rofl0r** [comment]
> v1.10.0 sighub triggers config (including closing/opening log files)

SIGHUP, actually.

but one should really use 1.11.0-rc1 these days, it's fixed like 40 issues/bugs (there it's SIGHUP in daemon mode, or SIGUSR1 in any mode).
