### ISSUE TITLE
`Maximum number of connections reached` upon staring proxy

### ISSUE THREAD

**Issue by RugnarLodbrok** [tinyproxy/tinyproxy#283]
Trying to launch proxy.
My config:
```
user nobody
group nogroup
port 8888
```
command: `tinyproxy -d -c /etc/tinyproxy/tinyproxy.conf`
output:
```
INFO      Jan 07 13:59:04 [16383]: Initializing tinyproxy ...
INFO      Jan 07 13:59:04 [16383]: Reloading config file
INFO      Jan 07 13:59:04 [16383]: listen_sock called with addr = '(NULL)'
INFO      Jan 07 13:59:04 [16383]: trying to listen on host[0.0.0.0], family[2], socktype[1], proto[6]
INFO      Jan 07 13:59:04 [16383]: listening on fd [3]
INFO      Jan 07 13:59:04 [16383]: trying to listen on host[::], family[10], socktype[1], proto[6]
INFO      Jan 07 13:59:04 [16383]: listening on fd [4]
WARNING   Jan 07 13:59:04 [16383]: Not running as root, so not changing UID/GID.
INFO      Jan 07 13:59:04 [16383]: Setting the various signals.
INFO      Jan 07 13:59:04 [16383]: Starting main loop. Accepting connections.
NOTICE    Jan 07 13:59:04 [16383]: Maximum number of connections reached. Refusing new connections.
```
What's wrong with that maximum number of conenctins?

**Comment by rofl0r** [comment]
are you using git master ? earlier versions of tinyproxy (such as latest release) require explicit limits (see etc/tinyproxy.conf.in in your source directory).

**Comment by RugnarLodbrok** [comment]
Yes, I'm using master. Found solution, had to add `maxclients 1` in conf file. Apparently default value is 0 so it is always reached. Thanks for help!

**Comment by rofl0r** [comment]
> Apparently default value is 0 so it is always reached.

the hardcoded default value is 100, so something goes wrong here. i'm leaving this open as a reminder to investigate.
