### ISSUE TITLE
DOS with servers not being cleaned up

### ISSUE THREAD

**Issue by BobBall** [tinyproxy/tinyproxy#289]
We are using tinyproxy with buildroot as a reverse proxy only. After a security scan, we have seen many instances of our setup reaching the maximum number of servers (tinyproxy[8]: Waiting servers (0) is less than MinSpareServers (5). Creating new child.). These never recover.

```
# ps | grep tinyproxy | wc -l
102
```

We have tested killing all of the local services that could be keeping a port open, and our config includes "Timeout 600", however no servers are killed after the 10m timeout.

A tinyproxy that is frozen is:

```
# strace -p 25057
strace: Process 25057 attached
recvfrom(10,
...
# ps l | grep 25057
S   101 25057  3816 20180  4820 0:0   Oct23 00:00:00 /usr/sbin/tinyproxy -d
# ls /proc/25057/fd -l
lr-x------    1 root     root            64 Nov 13 16:42 0 -> pipe:[18812]
l-wx------    1 root     root            64 Nov 13 16:42 1 -> pipe:[18813]
lrwx------    1 root     root            64 Nov 13 16:42 10 -> socket:[74779627]
l-wx------    1 root     root            64 Nov 13 16:42 2 -> pipe:[18814]
lrwx------    1 root     root            64 Nov 13 16:42 3 -> /tmp/tinyproxy.shared.RD4Vy1 (deleted)
lrwx------    1 root     root            64 Nov 13 16:42 4 -> socket:[18840]
lrwx------    1 root     root            64 Nov 13 16:42 5 -> socket:[18841]
lrwx------    1 root     root            64 Nov 13 16:42 6 -> socket:[18874]
lrwx------    1 root     root            64 Nov 13 16:42 7 -> /tmp/tinyproxy.shared.hl8dkn (deleted)
lrwx------    1 root     root            64 Nov 13 16:42 8 -> /tmp/tinyproxy.shared.ptUx5I (deleted)
lrwx------    1 root     root            64 Nov 13 16:42 9 -> /tmp/tinyproxy.servers.lock.zeqSQ4 (deleted)
# cat /proc/25057/status
Name:   tinyproxy
Umask:  0177
State:  S (sleeping)
Tgid:   25057
```

What could the clients be doing to keep these connections open, and how can we force close them?
Without the ability to force close connections, there is an obvious denial of service

**Comment by rofl0r** [comment]
> Waiting servers (0) is less than MinSpareServers (5). 

please try code from git master. there have been numerous improvements in this area.

> What could the clients be doing to keep these connections open

for example using http keep-alive option and then sending a tiny packet in an interval ?

> how can we force close them

iirc iptables has an option to force-close a specific connection

**Comment by outtersg** [comment]
Couldn't this be a duplicate of #274?

**Comment by BobBall** [comment]
I've not been able to test the latest from git master yet.
It could absolutely be related to 274, but in this case we have no control over the clients. The issue is that a client can apparently cause a denial of service against a tiny-proxy reverse-proxy environment by keeping their connection alive indefinitely and exhausting the number of servers from the config file.
I thought 274 was focused on an environment where the client could be controlled.

**Comment by rofl0r** [comment]
this is indeed a dup of #274. the latter has now a possible bugfix in my [comment](https://github.com/tinyproxy/tinyproxy/issues/274#issuecomment-599601045), therefore i'm closing this one.
