### ISSUE TITLE
HTTP authentication

### ISSUE THREAD

**Issue by inkrement** [tinyproxy/tinyproxy#29]
is it possible to add http authentication?

**Comment by lucaswxp** [comment]
+1

**Comment by obnoxxx** [comment]
You mean client authenticating against the proxy?
It would require some time developing the feature, in theory possible and desirable...

**Comment by inkrement** [comment]
Exactly, a client authentication.

**Comment by lucaswxp** [comment]
I guess you could put nginx in front of it for basic auth.

**Comment by inkrement** [comment]
You are right, but I like tiny proxy because it's a lightweight and easy to configure software. If someone has to put nginx in front you will have to configure a second software, which makes it more difficult.

**Comment by obnoxxx** [comment]
Yeah, I'd like to develop proxy authentication. But it's not a super trivial task. You need to add crypto / ssl / etc. I currently have difficulties finding time for such an endeavour. Patches or someone willing to collaborate on such a project would be welcome. :-)

**Comment by VadVoci** [comment]
how about mini-httpd-htpasswd or .. lighttpd-mod-auth ?
I successfully used htpasswd command for squid 2.7 proxy server Basic Auth.
htpasswd is build during the compilation of mini_httpd, but not put in mini_httpd package.
htpasswd is basic authentication (see squid-mod-basic-auth-ncsa).
mini-httpd-htpasswd is an utility to generate HTTP access authentication files

**Comment by huiyiqun** [comment]
Hi, I'm preparing a [patch](https://github.com/huiyiqun/tinyproxy) for this feature.

As noticed by @obnoxxx , this requires some crypto / ssl functions such as base64, md5 or something else.

I'm not sure whether Is it ok to link tinyproxy against library such as openssl, which may noteworthily increase the size of binary generated and increase compiling-time dependencies.

PS: I'm planning to implement the authentication with basic http auth or digest http auth, but which is
not secure with plain http protocal. Is there any suggestions?

**Comment by VadVoci** [comment]
@ huiyiqun if you can doit!
 implement that authentication with basic http auth or digest http auth, even is
not very secure

**Comment by rofl0r** [comment]
@huiyiqun if i may suggest https://tweetnacl.cr.yp.to/ , a crypto-library in a single small C file.
if that is not sufficient it may be best linking against openssl / libressl, which is ubiquitous, or at least use their md5/ whatever implementations for the time being until a good candidate is found which code can be embedded into the source tree (so it should be small and license-compatible).

**Comment by huiyiqun** [comment]
I will take a look at `tweetnacl`. Thanks for your suggestions.

**Comment by diwu1989** [comment]
really would appreciate basic auth in this one

**Comment by sakurai-youhei** [comment]
+1 and what about exposing authentication to external command instead of owning it?

**My idea**

- Add one configuration property like AuthCommand.
- Unless AuthCommand exists, then tinyproxy shall not require Proxy-Authorization header.
- If AuthCommand exists, then tinyproxy shall require Proxy-Authorization header and authenticate client.

**How to authenticate**

1. Run AuthCommand (without shell for security).
2. Input value of Proxy-Authorization header through STDIN.
3. Wait and check return code; If 0, then allow request. Otherwise deny request.

**Examples of tinyproxy.conf**

```
# Always allow
AuthCommand = "true"

# Always deny
AuthCommand = "false"

# Allow if value of Proxy-Authorization header
# matches line(s) in the file.
AuthCommand = "grep -f - /path/to/file"

# Allow if the Python script ends with 0.
AuthCommand = "python /path/to/script.py"

# Allow if the Shell (sh) ends with 0.
AuthCommand = "sh -c 'xargs | foo | bar | and_so_on'"
```

**Advantages**

- No need to link crypto-library.
- Allow any types of custom authentication.

**Disadvantages**

- Authentication costs very much unless no cache function like AuthCacheTtl.
- Authentication using htpasswd becomes unstraightforward.

*P.S. I can maybe give only idea because I'm not good at C coding at all.*

**Comment by h-2-0** [comment]
I second everybody that wants authentication. :)

**Comment by rofl0r** [comment]
meanwhile there's microsocks: https://github.com/rofl0r/microsocks

it can do standard socks5 auth and has a feature called "auth-once", which puts an ip on a whitelist once it has successfully authed (so it can be used with socks5 clients that don't support password auth, such as firefox)

**Comment by lfxc** [comment]
+1  must have authentication

**Comment by Ardakilic** [comment]
Another +1 here.

**Comment by kalsolio** [comment]
+1

**Comment by hunter-xue** [comment]
+1

**Comment by pengqi** [comment]
+1 need this feature.

**Comment by ppar** [comment]
+1, would be very nice. 

@sakurai-youhei's idea sounds good too, but basic auth happens on every HTTP request, so it could cause a lot of subprocesses, and creating a new process can be expensive.

**Comment by patricioe** [comment]
+1 for this feature

**Comment by jisri** [comment]
+1 too

**Comment by radoslawprzytula** [comment]
I would love to see that feature! :1st_place_medal:

**Comment by danielsantiago** [comment]
+1

**Comment by rofl0r** [comment]
i actually have this feature already implemented, but i'm getting warnings due to the stupid -Wc++-compat flag that's turned on by default, and i'm not willing to waste time to work around it.

**Comment by 2ge** [comment]
@rofl0r it is possible to use (I can ignore warning). Otherwise +1, this is must feature

**Comment by vicmosin** [comment]
So any news to this issue? 
@rofl0r was your fix merged?

**Comment by rofl0r** [comment]
see PR #129 . you may test it and leave your comments in the PR issue.

**Comment by raysbudo** [comment]
Need to implement digest auth in my centos httpd container for team only access id there any way to get this to work in docker 1.18

**Comment by rofl0r** [comment]
yes, clone git master and follow the instruction in the README on how to build.

**Comment by raysbudo** [comment]
can you let me know which master you are speaking of

**Comment by rofl0r** [comment]
i am talking about this repo: `git clone https://github.com/tinyproxy/tinyproxy`.
if you have further issues/question, please open a new issue.
