### ISSUE TITLE
Build failure on centos 7

### ISSUE THREAD

**Issue by OliDrouin** [tinyproxy/tinyproxy#291]
Hello
I'm running Centos 7.7 and I'm getting an error running ./autogen.sh:

```[root@master tinyproxy]# ./autogen.sh
+ cd .
+ aclocal -I m4macros
unknown channel -1- m4_pattern_allow(^HAVE_REALLOC$)
obsolete at /usr/share/autoconf/Autom4te/Channels.pm line 638.
        Autom4te::Channels::msg('-1- m4_pattern_allow(^HAVE_REALLOC$)\x{a}obsolete', 'configure.ac:148', 'warning: The macro `AC_TRY_COMPILE\' is obsolete.\x{a}You should ...',
'partial', 1) called at /bin/autom4te line 1026
aclocal: error: echo failed with exit status: 1
+ cd /vagrant/tinyproxy
+ set -
./configure
./autogen.sh: line 21: ./configure: No such file or directory

Configure failed or did not finish!
```

I also tried to run `autoreconf -i ` as per [issue #72 ](https://github.com/tinyproxy/tinyproxy/issues/72#issuecomment-269475184) with the same result. 

Any idea what's going on here? 

Thank you,
Oli.

**Comment by OliDrouin** [comment]
nvm, It compiled on debian 10.

**Comment by OliDrouin** [comment]
The current master seems to be fixing an issue I had with the EPEL release where tinyproxy would have trouble processing requests under load.

**Comment by yucongo** [comment]
Ubuntu18， same problem when doing ./autogen.sh：
```./autogen.sh: 21: ./autogen.sh: ./configure: not found```
I did a ``` git clone https://github.com/tinyproxy/tinyproxy.git ``` and read README.md.

**Comment by xaander1** [comment]
### Make sure your machine is updated

```
apt update
apt upgrade -y
reboot
```
###  Include the dependencies
`apt install -y git automake build-essential asciidoc xsltproc`
 

> Should work now
> Tested on ubuntu 18.04

**Comment by rofl0r** [comment]
if this is still an issue, please reopen.
