### ISSUE TITLE
anonymous_insert() segfault 

### ISSUE THREAD

**Issue by CaptBoykin** [tinyproxy/tinyproxy#292]
Leaving *any* string value greater than length 0 for Anonymous in the Anonymous Proxying section of etc/tinyproxy.conf causes a segfault in `anonymous_insert()`.  config->anonymous_map appears NULL at time of conditional?

Version: `tinyproxy 1.10.0-git-27-g2e02dce`
OS: `Linux kali 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux`
Install:
```
./autogen.sh
./configure --enable-debug
make
make install
```

![tinyproxy_01](https://user-images.githubusercontent.com/25166954/76605162-fe95c680-64dd-11ea-88a8-95f7af285b28.png)

**Comment by rofl0r** [comment]
thanks for your report. i hope the above commit fixes the issue for you too
