### ISSUE TITLE
A suspected double-free vulnerability

### ISSUE THREAD

**Issue by p611148aadsl** [tinyproxy/tinyproxy#293]
Hello，I was doing a static code audit and found a suspected double-free vulnerability.
in process_request() in reqs.c
```
if (extract_url (skipped_type, HTTP_PORT, request) < 0) {
                        indicate_http_error (connptr, 400, "Bad Request",
                                             "detail", "Could not parse URL",
                                             "url", url, NULL);
                        goto fail;
```

it will call extract_url() function to extract url. But when extract fail, it will free request->path and request->host, but not set to NULL
```
ERROR_EXIT:
        if (request->host)
                safefree (request->host);
        if (request->path)
                safefree (request->path);

        return -1;
```
And then in process_request() will goto fail:
```
fail:
        safefree (url);
        free_request_struct (request);
        return NULL;
```

due to not set request->path and request->host to NULL when calling safefree. Maybe cause double-free in free_request_struct()
```
static void free_request_struct (struct request_s *request)
{
        if (!request)
                return;

        safefree (request->method);
        safefree (request->protocol);

        if (request->host)
                safefree (request->host);
        if (request->path)
                safefree (request->path);

        safefree (request);
}
```
Is this a bug?

**Comment by rofl0r** [comment]
safefree is defined in heap.h as a macro:

```c
#  define safefree(x) (free (x), *(&(x)) = NULL)
```

it sets the macro argument to NULL after calling free.

but if you're uncertain, you could set a breakpoint in gdb and inspect the values manually after triggering this code path by sending a malformed request.

**Comment by p611148aadsl** [comment]
yeah, you are right.I see the same in compilation.
