### ISSUE TITLE
warnings during build

### ISSUE THREAD

**Issue by rofl0r** [tinyproxy/tinyproxy#3]
```
network.c: In function 'get_ip_string':
network.c:262:53: warning: cast increases required alignment of target type [-Wcast-align]
                         struct sockaddr_in *sa_in = (struct sockaddr_in *) sa;
                                                     ^
network.c:270:29: warning: cast increases required alignment of target type [-Wcast-align]
                             (struct sockaddr_in6 *) sa;
```

**Comment by obnoxxx** [comment]
Hmmm, I don't see the warning on my machine.
On what system are you building? 32bit?

**Comment by rofl0r** [comment]
i cannot reproduce it right now, neither with my native compiler nor a i486 crosscompiler. i suspect it was due to differences in the musl version i used back in january (or maybe the crosscompiler arch/version, iirc i used gcc 4.8.4 armv7hf back then).
