### ISSUE TITLE
How to install Procedure

### ISSUE THREAD

**Issue by davidnovotech** [tinyproxy/tinyproxy#30]
It seems like non of the install scripts are at the root folder. Could you update us on the new way to install from this repository ?

**Comment by obnoxxx** [comment]
what 'install scripts' are you referring to?

**Comment by obnoxxx** [comment]
It has not changed from before:
* It you are using a git clone, you run ./autogen.sh and then configure, make, make install.
* If you are using a release tarball, the autogen.sh step can be skipped.

**Comment by blaketmiller** [comment]
@obnoxxx I had the same question as @davidnovotech and the instruction to run `./autogen.sh` for a git clone could only be found on this issue. Could that bit of info be added to `README`?

**Comment by blaketmiller** [comment]
In fact, even simply running `./autogen.sh` fails for me:

```
~$ git clone https://github.com/tinyproxy/tinyproxy.git
Initialized empty Git repository in /srv/users/gredapi/tinyproxy/.git/
remote: Counting objects: 7374, done.
remote: Total 7374 (delta 0), reused 0 (delta 0), pack-reused 7374
Receiving objects: 100% (7374/7374), 1.63 MiB | 876 KiB/s, done.
Resolving deltas: 100% (5190/5190), done.
~$ cd tinyproxy
~/tinyproxy$ ./autogen.sh 
+ cd .
+ aclocal -I m4macros
+ autoheader
+ automake --gnu --add-missing
configure.ac:25: installing `./config.guess'
configure.ac:25: installing `./config.sub'
configure.ac:26: installing `./install-sh'
configure.ac:26: installing `./missing'
src/Makefile.am: installing `./depcomp'
Makefile.am: installing `./INSTALL'
Makefile.am: required file `./ChangeLog' not found
+ cd /srv/users/gredapi/tinyproxy
+ set -
./configure
./autogen.sh: line 21: ./configure: No such file or directory

Configure failed or did not finish!
```

For what it's worth:
```
~$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.7 (Santiago)
Release:	6.7
Codename:	Santiago
```

and I do not have root privileges nor access to EPEL.

**Comment by btsimonh** [comment]
I have the same issue... ./autogen.sh does not produce a configure :(.

**Comment by btsimonh** [comment]
ok, fixed by creating a file called ChangeLog, which allows autogen to complete.  Also commented out asciidocs error (for my simple use, I don;t want to install over 1GB of asciidoc just to compile), and fixed spaces in makefile in src folder.... and now can build and install (just with errors in docs).

**Comment by dportabella** [comment]
Please add this to the README:
$ touch ChangeLog
$ ./autogen.sh
