### ISSUE TITLE
Document BasicAuth

### ISSUE THREAD

**Issue by pauldraper** [tinyproxy/tinyproxy#303]
`BasicAuth` is documented on the [wiki](https://github.com/tinyproxy/tinyproxy/wiki/user-&-password), but not the [main website](https://tinyproxy.github.io/).

It took me a bit of searching to find out that Tinyproxy even support authentication, which was a must-have requirement. Fortunately I found the [PR](https://github.com/tinyproxy/tinyproxy/pull/129) from two years ago.

**Comment by rofl0r** [comment]
do you think the documentation in the config file example is insufficient ?

**Comment by pauldraper** [comment]
I didn't look.

Prior to install, I was trying to figure out whether tinyproxy supported any form of authentication. I couldn't figure that out until I happened across the PR.

**Comment by rofl0r** [comment]
ok. could you file a PR with the updated documentation against the repo of the website?

**Comment by rofl0r** [comment]
fixed via 5e594e593a77f25f48e2ff073058ec71cbec1680
