### ISSUE TITLE
Do we support IPV6 Only in TinyProxy Version tinyproxy-1.8.3-2.el7.x86_64

### ISSUE THREAD

**Issue by cs-priyank-mankad** [tinyproxy/tinyproxy#305]

**Comment by cs-priyank-mankad** [comment]
Do we also support Giving Username and password to Tiny proxy server with version tinyproxy-1.8.3-2.el7.x86_64

**Comment by rofl0r** [comment]
ipv6 only: i don't know.
basic auth: no

there's a stable release of tinyproxy 1.10 with basic auth available since more than a year so i'd suggest to ask red hat support to upgrade the available package or you compile it yourself from source.
