### ISSUE TITLE
explain the code

### ISSUE THREAD

**Issue by xverizex** [tinyproxy/tinyproxy#307]
in line 239, the structure gets prev. but if tail turned out to be null, then prev will point to invalid data.

https://github.com/tinyproxy/tinyproxy/blob/25e2cc330c5f6b403d91a316304f92bae0047227/src/hashmap.c#L238-L245

**Comment by rofl0r** [comment]
why invalid? i see one odd thing, which is that line 240 checks for tail being NULL but line 243 assigns to it without the check. did you experience an actual issue ?

**Comment by xverizex** [comment]
excuse me. I studied your code and did not understand that everything is fine. I then laughed.
