### ISSUE TITLE
Setup IPv6

### ISSUE THREAD

**Issue by sirrobo-development** [tinyproxy/tinyproxy#309]
Hello,

i've just installed tinyproxy. It works great - thank you!
At least i have one question. How to setup IPv6? How i have to configure it in tinyproxy?
I don't found any configuration here, as well @ Google.

Greetings,
Felix

**Comment by rofl0r** [comment]
i think it should be sufficient to use 0.0.0.0 as the listening address. did you try that ?

**Comment by rofl0r** [comment]
i found that by not using any listening address or `Listen ::` tinyproxy listens on both 0.0.0.0 and ::, so it accepts incoming connections on all ipv4 and ipv6 interfaces.
when specifiying `Listen 0.0.0.0` otoh tinyproxy listens only on ipv4 interfaces.

**Comment by LumingSun** [comment]
@rofl0r Hi, any idea how to set ipv6 proxy on the client machine (Ubuntu)? I tried ```export http_proxy=http://[ipv6_addr]:port/``` , ```export http_proxy=http://\[ipv6_addr\]:port/```, and ```export http_proxy=http://ipv6_addr:port/```, but none of them work.
