### ISSUE TITLE
Mutiple Interface Ports and Multiple Listen Ports

### ISSUE THREAD

**Issue by ozican** [tinyproxy/tinyproxy#313]
Hello people. 
I have 1 interface with multiple ports. For example;
Interface1 -> 127.0.0.1:1001
Interface2 -> 127.0.0.1:1002
Interface3 -> 127.0.0.1:1003

I want to listen 3 different ports on tinyproxy. For example

Client1 ->  my_proxy_server_ip:1001 -> Connect to interface's 1001 port (127.0.0.1:1001)
Client2 ->  my_proxy_server_ip:1002 -> Connect to interface' s 1002 port (127.0.0.1:1002)
Client3 ->  my_proxy_server_ip:1003 -> Connect to interface's 1003 port (127.0.0.1:1003)

I try to edit config file but I couldn't success. Would you give me an example please.

**Comment by rofl0r** [comment]
why don't you simply run 3 instances, where each one runs on a different port?

**Comment by ozican** [comment]
it is little bit complicated, I have a virtualized device which is controller. It manage the other instances. @rofl0r

**Comment by ozican** [comment]
hello again @rofl0r  I change my structure and all interface have different local ips. Is there a solution in this case?

I want to set
172.17.0.2 to 3001 port
172.17.0.3  to 3002 port

**Comment by rofl0r** [comment]
> I want to set
> 172.17.0.2:8888 to 3001 port

what do you mean? should it listen on 8888 or 3001 ?

**Comment by ozican** [comment]
> > I want to set
> > 172.17.0.2:8888 to 3001 port
> 
> what do you mean? should it listen on 8888 or 3001 ?

Thank you very much first of all. You take your time. And really good repo! Thank you so much.

I mean; 
if my client connect to my_public_ip:3001 -> I want to give him 127.0.0.1:1018
if my client connext to my_public_ip:3002 -> I want to give him 127.0.0.1:1019


Is that possible with tiny proxy? Please say yes :) I really need that.

**Comment by rofl0r** [comment]
> if my client connect to my_public_ip:3001 -> I want to give him 127.0.0.1:1018

that sounds like you just want to redirect a port. for such case "portredir" program is the best option.

**Comment by ozican** [comment]
> > if my client connect to my_public_ip:3001 -> I want to give him 127.0.0.1:1018
> 
> that sounds like you just want to redirect a port. for such case "portredir" program is the best option.

can I use it as a proxy?
For example, if I put my_public_ip:3001 in to firefox proxy settings. Can I connect to internet from my server's 127.0.0.1:1018?

**Comment by rofl0r** [comment]
>can I use it as a proxy?
>For example, if I put my_public_ip:3001 in to firefox proxy settings. Can I connect to internet from my server's 127.0.0.1:1018?

depends on whether a proxy service is listening on 127.0.0.1:1018

**Comment by ozican** [comment]
> > can I use it as a proxy?
> > For example, if I put my_public_ip:3001 in to firefox proxy settings. Can I connect to internet from my server's 127.0.0.1:1018?
> 
> depends on whether a proxy service is listening on 127.0.0.1:1018

yes it is listening. Ok I'm trying immediately. Thank you so much!!

**Comment by ozican** [comment]
@rofl0r You're amazing. you saved me! Thank you million times. It works how I want! Such a good day! :)

**Comment by encryptblockr** [comment]
> [@rofl0r](https://github.com/rofl0r) You're amazing. you saved me! Thank you million times. It works how I want! Such a good day! :)

mind sharing the final config you went with and what is usecase of this your setup?

i am looking for something that may be similar where i want tinyproxy to bind to multiple interfaces on different ports
usecase for me i have a server with multiple ipv6 addresses and i want to proxy through all those ipv6 addresses so i want to bind single instance of tinyproxy running to lets say 16 ipv6 addresses each on different ports

and then i can proxy to tinyproxy using same tinyproxy ip address but now with different ports correlating to the ipv6 addresses that tinyproxy bind to
