### ISSUE TITLE
client ip in logs

### ISSUE THREAD

**Issue by pankajmt** [tinyproxy/tinyproxy#314]
is it possible to see the client ip in logs? proxy would have the info as its able to set xtinyproxy header!

**Comment by rofl0r** [comment]
yes, it is possible. please post a chunk of your logfile output so i can explain you how it works.

**Comment by pankajmt** [comment]
this is what i see in the logs

CONNECT   Aug 24 04:00:14 [1]: Connect (file descriptor 21): 10.213.13.135
CONNECT   Aug 24 04:00:14 [1]: Request (file descriptor 21): CONNECT 10.213.13.1:443 HTTP/1.1
NOTICE    Aug 24 04:00:14 [1]: Proxying refused on filtered domain "10.213.13.1"
INFO      Aug 24 04:00:14 [1]: no entity

**Comment by rofl0r** [comment]
you can link who does what via the file descriptor. in this case, someone with ip "10.213.13.135" connected to the proxy, got assigned fd (file descriptor) 21, and then tried to connect to "10.213.13.1".
is it clear now?

**Comment by pankajmt** [comment]
ah ok. thanks!
