### ISSUE TITLE
Cross compiling for a synology nas fails

### ISSUE THREAD

**Issue by TheStaticTurtle** [tinyproxy/tinyproxy#318]
Hi I want to create an executable for running my synology nas.
After trying to compile it I found that malloc realloc needed to be patched see https://github.com/SynoCommunity/spksrc/issues/4159 

Unfortunately using the same config as my Debian 64bit server doesn't work and spits out 
`./tinyproxy: Could not create the pool of children.`
Log file says
`ERROR     Sep 06 00:46:26 [18950]: child_pool_create: "StartServers" must be greater than zero`
Setting the value StartServers to 15 for instance seems to get the program working but loading google on firefox doesn't work log files gives this
```
CONNECT   Sep 06 02:59:04 [19523]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:04 [19523]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1
CONNECT   Sep 06 02:59:05 [19522]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:05 [19522]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1
CONNECT   Sep 06 02:59:05 [19521]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:05 [19521]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1
CONNECT   Sep 06 02:59:06 [19520]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:06 [19520]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1
CONNECT   Sep 06 02:59:06 [19519]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:07 [19519]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1
CONNECT   Sep 06 02:59:07 [19518]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:07 [19518]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1
CONNECT   Sep 06 02:59:07 [19517]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:07 [19517]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1
CONNECT   Sep 06 02:59:08 [19516]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:08 [19516]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1
CONNECT   Sep 06 02:59:09 [19514]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:09 [19514]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1
CONNECT   Sep 06 02:59:09 [19513]: Connect (file descriptor 10): 192.168.1.77 [192.168.1.77]
CONNECT   Sep 06 02:59:09 [19513]: Request (file descriptor 10): GET http://www.tugler.fr/ HTTP/1.1 
```

And I'm kinda stuck here cause I don't know the root of the program

**Comment by rofl0r** [comment]
i don't see any tinyproxy package in their source tree but they probably use an ancient version, as we don't use gnulib (the rpl_* stuff you get suggests that gnulib is being used).
you should crosscompile the sources from this repo (current master) manually or tell them to update to current git (if they even have a package for tinyproxy).

**Comment by TheStaticTurtle** [comment]
They don't have a package for it as I'm currently trying to create it. Their system download the source each time and do checksums on it and using the 1.10.0 release of this repo result to this. I'll look into downloading it from the master branch which I'm sure will solve some issues that I'm having (Commit f20681e0c628fa1d5f222e69615e9d48529b61ec for instance) but I might have some issues with the checksums. Maybe you could do a release in the near future ?

**Comment by rofl0r** [comment]
you use as dl url e.g. https://github.com/ORGANIZATION/REPO/archive/HASH.tar.gz
and then you hash the result. since you target a specific hash, the checksum will stay identical

i'd like to do a release since about a month but unfortunately the gpg key owner @obnoxxx is currently M.I.A.

**Comment by TheStaticTurtle** [comment]
Ok I'll try that when I have the time (probably tomorrow)

**Comment by TheStaticTurtle** [comment]
Ok I tried it didn't know you could do that but it works thanks for the help
