### ISSUE TITLE
No BasicAuth user&pass request in Firefox

### ISSUE THREAD

**Issue by githuborer** [tinyproxy/tinyproxy#322]
Hi,
I installed tinyproxy 1.10.0 in Debian Buster over old tinyproxy 1.8.3 with this conf:

```
User tinyproxy
Group tinyproxy
Port 8081
Listen 192.168.1.254
Bind 192.168.0.222
Timeout 30
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
Logfile "/var/log/tinyproxy/tinyproxy-bypass.log"
Syslog Off
LogLevel Info
PidFile "/var/run/tinyproxy/tinyproxy2.pid"
MaxClients 100
MinSpareServers 1
MaxSpareServers 10
StartServers 3
MaxRequestsPerChild 1000
Allow 127.0.0.1
Allow 192.168.1.8
BasicAuth username pass
ViaProxyName "tinyproxy2"
#DisableViaHeader Yes
#FilterDefaultDeny Yes
ConnectPort 443
```

I tried many settings but proxy over client 192.168.1.8 is just open.

**Comment by rofl0r** [comment]
firefox saves user password for http proxies if so requested. did you maybe forget it's been saved once? try to change password and see whether that causes a dialog to pop up.

additionally you can try it with curl like so:
`curl -x  http://user:pass@proxyip:port foo.com`

**Comment by githuborer** [comment]
Okay I changed it and restarted firefox and tinyproxy.
No Login request and no websites opening.


`INFO      Sep 10 13:49:28 [11212]: Shutting down.
ERROR     Sep 10 13:49:28 [11212]: No more children left. Shutting down.
INFO      Sep 10 13:49:31 [14101]: Initializing tinyproxy ...
INFO      Sep 10 13:49:31 [14101]: Reloading config file
INFO      Sep 10 13:49:31 [14101]: Added address [192.168.1.254] to listen addresses.
INFO      Sep 10 13:49:31 [14101]: Outgoing connections bound to IP 192.168.0.222
INFO      Sep 10 13:49:31 [14101]: Added basic auth user : xxxxxxxxxx
INFO      Sep 10 13:49:31 [14101]: Setting "Via" header to 'tinyproxy2'
INFO      Sep 10 13:49:31 [14101]: Adding Port [443] to the list allowed by CONNECT
INFO      Sep 10 13:49:31 [14101]: listen_sock called with addr = '192.168.1.254'
INFO      Sep 10 13:49:31 [14101]: trying to listen on host[192.168.1.254], family[2], socktype[1], proto[6]
INFO      Sep 10 13:49:31 [14101]: listening on fd [0]
INFO      Sep 10 13:49:31 [14101]: Now running as group "tinyproxy".
INFO      Sep 10 13:49:31 [14101]: Now running as user "tinyproxy".
INFO      Sep 10 13:49:31 [14101]: Setting the various signals.
INFO      Sep 10 13:49:31 [14101]: Creating child number 1 of 3 ...
INFO      Sep 10 13:49:31 [14101]: Creating child number 2 of 3 ...
INFO      Sep 10 13:49:31 [14101]: Creating child number 3 of 3 ...
INFO      Sep 10 13:49:31 [14101]: Finished creating all children.
INFO      Sep 10 13:49:31 [14101]: Starting main loop. Accepting connections.
CONNECT   Sep 10 13:49:47 [14104]: Connect (file descriptor 6): lappi [192.168.1.8]
CONNECT   Sep 10 13:49:47 [14104]: Request (file descriptor 6): CONNECT www.speedtest.net:443 HTTP/1.1
INFO      Sep 10 13:49:47 [14104]: no entity
CONNECT   Sep 10 13:49:51 [14104]: Connect (file descriptor 6): lappi [192.168.1.8]
CONNECT   Sep 10 13:49:51 [14104]: Request (file descriptor 6): CONNECT www.speedtest.net:443 HTTP/1.1
INFO      Sep 10 13:49:51 [14104]: no entity
CONNECT   Sep 10 13:49:58 [14104]: Connect (file descriptor 6): lappi [192.168.1.8]
CONNECT   Sep 10 13:49:58 [14104]: Request (file descriptor 6): CONNECT www.speedtest.net:443 HTTP/1.1
INFO      Sep 10 13:49:58 [14104]: no entity
`

But with curl in windows it seems to be okay:

curl -x http://xxxxxxxx:testmypasswd@192.168.1.254:8081 google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```
CONNECT   Sep 10 13:56:27 [14102]: Connect (file descriptor 6): lappi [192.168.1.8]
CONNECT   Sep 10 13:56:27 [14102]: Request (file descriptor 6): GET http://google.com/ HTTP/1.1
INFO      Sep 10 13:56:27 [14102]: No upstream proxy for google.com
INFO      Sep 10 13:56:27 [14102]: opensock: opening connection to google.com:80
INFO      Sep 10 13:56:27 [14102]: opensock: getaddrinfo returned for google.com:80
CONNECT   Sep 10 13:56:27 [14102]: Established connection to host "google.com" using file descriptor 7.
INFO      Sep 10 13:56:27 [14102]: Closed connection between local client (fd:6) and remote client (fd:7)
```
