### ISSUE TITLE
compile failed (since version 35c8edcf73056e20b0c055acb2f286cc37093ce3)

### ISSUE THREAD

**Issue by harryboo** [tinyproxy/tinyproxy#329]
problem since [version](https://github.com/tinyproxy/tinyproxy/commit/35c8edcf73056e20b0c055acb2f286cc37093ce3)

make[3]: Verzeichnis „/home//tinyproxy-8d27503cc3/src“ wird betreten
  CC       anonymous.o
  CC       acl.o
  CC       buffer.o
  CC       child.o
  CC       conf-tokens.o
  CC       conf.o
  CC       conns.o
conf.c: In function 'config_parse':
conf.c:412:21: error: 'LINE_MAX' undeclared (first use in this function)
         char buffer[LINE_MAX], *p, *q, c;
                     ^
conf.c:412:21: note: each undeclared identifier is reported only once for each function it appears in
conf.c:412:14: warning: unused variable 'buffer' [-Wunused-variable]
         char buffer[LINE_MAX], *p, *q, c;
              ^
conf.c: In function 'initialize_config_defaults':
conf.c:475:9: warning: implicit declaration of function 'strdup' [-Wimplicit-function-declaration]
         conf->stathost = safestrdup (TINYPROXY_STATHOST);
         ^
conf.c:475:24: warning: assignment makes pointer from integer without a cast [enabled by default]
         conf->stathost = safestrdup (TINYPROXY_STATHOST);
                        ^
conf.c:477:25: warning: assignment makes pointer from integer without a cast [enabled by default]
         conf->logf_name = safestrdup (LOCALSTATEDIR "/log/tinyproxy.log");
                         ^
conf.c:478:23: warning: assignment makes pointer from integer without a cast [enabled by default]
         conf->pidpath = safestrdup (LOCALSTATEDIR "/tinyproxy.pid");
                       ^
Makefile:456: recipe for target 'conf.o' failed

**Comment by rofl0r** [comment]
what OS/glibc version ?

**Comment by rofl0r** [comment]
never mind, travis fails too. https://travis-ci.org/github/tinyproxy/tinyproxy/builds/731693504

this is due to the [+!%$# feature test macro hell](https://man7.org/linux/man-pages/man7/feature_test_macros.7.html)
