### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by PhilT001** [tinyproxy/tinyproxy#33]
I'm getting the following error when running make on the latest git version:
```
Making all in etc
make[2]: Entering directory '/home/user/builds/source/tinyproxy-1.8.3/etc'
  GEN    tinyproxy.conf
make[2]: Leaving directory '/home/user/builds/source/tinyproxy-1.8.3/etc'
Making all in docs
make[2]: Entering directory '/home/user/builds/source/tinyproxy-1.8.3/docs'
Making all in man5
make[3]: Entering directory '/home/user/builds/source/tinyproxy-1.8.3/docs/man5'
  GEN    tinyproxy.conf.5
: line 43: cd: a2x.py: Not a directory
a2x: ERROR: xmllint --nonet --noout --valid /home/user/builds/source/tinyproxy-1.8.3/docs/man5/tinyproxy.conf.xml returned non-zero exit status 4
Makefile:446: recipe for target 'tinyproxy.conf.5' failed
make[3]: **\* [tinyproxy.conf.5] Error 1
make[3]: Leaving directory '/home/user/builds/source/tinyproxy-1.8.3/docs/man5'
Makefile:256: recipe for target 'all-recursive' failed
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory '/home/user/builds/source/tinyproxy-1.8.3/docs'
Makefile:300: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/user/builds/source/tinyproxy-1.8.3'
Makefile:238: recipe for target 'all' failed
make: **\* [all] Error 2
```

This is on a "Debian like" arm device.

_Edit_ this is the output from version 1.8.3, but I get the same error from the git version.

**Comment by rofl0r** [comment]
see #2

**Comment by PhilT001** [comment]
Thank you for your reply.
I have asciidoc installed, more specifically a2x. (Its required to pass configure)

┌─[user@Nokia-N810-43-7]─[~]
└──╼ python /usr/bin/a2x.py --version
a2x 8.5.2

I am just an end user, so forgive me if I am missing something obvious.

**Comment by obnoxxx** [comment]
Hmm, I have no idea. The only very similar error I found searching the web is this: https://aur.archlinux.org/packages/bmpanel2/

Can you install 'more' asciidoc? just to make sure there's nothing missing. It seems like the installation is incomplete. tinyproxy does not do anything special with a2x , just calls it...

Can you manually use a2x on other input?

**Comment by obnoxxx** [comment]
Any answer to the questions?
As I said, TP build does not do anything special with a2x...
Otherwise, I will close this one soon.

**Comment by PhilT001** [comment]
I'm fairly sure that it is simply an incomplete installation of asciidoc. Unfortunately, the large size of the whole asciidoc package is to much to build for this device. TinyProxy builds without the docs anyway, but to the casual user it appears that it fails because of the error messages.

**Comment by obnoxxx** [comment]
@PhilT001 thanks for confirming. You will very soon have pre-built manpages shipped with the release tarball. See pr #63 . Closing...

**Comment by LinuXperia** [comment]
Hi All.
I had the same Build Error Message when building TinyProxy from the Sources.

I solved the Build error Problem by Installing this additional package here on Ubuntu.

> sudo apt install asciidoc-doc

before i had to install however this Packages too as ./configure would fail also

>  sudo apt install xsltproc asciidoc-base 

After this TinyProxy builded without any Problems.
