### ISSUE TITLE
Some request are very slow (>5seconds) possibly waiting for a timeout ?

### ISSUE THREAD

**Issue by dprslt** [tinyproxy/tinyproxy#330]
We use tinyproxy in a docker container (alpine) to access services inside Swarm.

While trying to reach ressources inside the swarm all the request are very long to proceed, all of them took at least 5 seconds. It look like tinyproxy is waiting for something, this thing timeout after 5s and then he proceed the request.

Querying by a Domain name or an IP address give the same result.

I've found nothing in the logs nor in the config which can explain that...

Do you have any idea of what could be the cause of this ?

---

Our config is pretty straightforward : 

````
User tinyproxy
Group tinyproxy
Port 8888
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogLevel Connect
MaxClients 100
MinSpareServers 5
MaxSpareServers 20
StartServers 10
MaxRequestsPerChild 0

ViaProxyName "tinyproxy"
```



**Installed version** : tinyproxy-1.10.0-r3

**Comment by rofl0r** [comment]
could you please try tinyproxy 1.11-rc1 (see releases page) it has dozens of performance improvements and bugfixes.

**Comment by dprslt** [comment]
I've to build a new docker image but that works! Thank you!
Two more questions :
- Where does the binary looks for the config file? When using the (old) version from the packets it will look into /etc/tinyproxy/. This does not work anymore with the sources, i' ve had to use the - c option explicitly.
- Do you have some kind of release date for the stable 1.11?

**Comment by rofl0r** [comment]
```
CONF              308 src/main.c               config_file = SYSCONFDIR "/tinyproxy.conf";
```
config file path is made up of sysconfdir, which is an option to the configure script (--sysconfdir=/etc). you probably also want to set --prefix=/usr

i don't have a definite date for 1.11 release but i'm working on it.

**Comment by dprslt** [comment]
Okay, i'll have a look :)

Thank you for your work, tiny proxy is amazing ! 🥇
