### ISSUE TITLE
[Question]: How can I configure TinyProxy to use different upstream proxies for different destinations?

### ISSUE THREAD

**Issue by dclong** [tinyproxy/tinyproxy#331]
Let's say that there's a server S1 which can only be visited through proxy P1 and a server S2 which can only be visited through proxy P2. Is it possible to configure a TinyProxy server so that it automatically uses the proxy P1 when I visit the server S1 and uses the proxy P2 when I visit the server S2? There's very little information on this in the official TinyProxy documentation.

**Comment by rofl0r** [comment]
```
# first rules: don't redirect local ips over upstreams
upstream none "127.0.0.1/8"
upstream none "10.0.0.0/8"
upstream none "192.168.0.0/16"

#nullroute ads/trackers
upstream http 0.0.0.0:0  ".adserver.com"
upstream http 0.0.0.0:0  ".spy-analytics.com"

#route google traffic over proxy1
upstream socks5 127.0.0.1:8001 ".google.com"

#route yahoo traffic over proxy2
upstream socks5 127.0.0.1:8002 ".yahoo.com"

#route everything else over tor
upstream socks4 127.0.0.1:9050
```

**Comment by rofl0r** [comment]
this is all documented in the tinyproxy.conf manpage, available also on https://tinyproxy.github.io/

**Comment by dclong** [comment]
Thank you very much, @rofl0r! This is really helpful! 

One more questions regarding the configuration for local IPs. Why do we use `127.0.0.1/8` etc. instead of using `127.0.0.1/0` etc. (`/0`)?
```
# first rules: don't redirect local ips over upstreams
upstream none "127.0.0.1/8"
upstream none "10.0.0.0/8"
upstream none "192.168.0.0/16"
```

**Comment by rofl0r** [comment]
this is called a netmask. /8 means that the entire 127.* class a subnet is matched by the rule.

**Comment by dclong** [comment]
@rofl0r,

I see. Get that. Thank you very much!
