### ISSUE TITLE
An exception at compile time. tinyproxy-1.11.0-rc1

### ISSUE THREAD

**Issue by downdawn** [tinyproxy/tinyproxy#337]
environment：
CentOS release 6.9 (Final)
tinyproxy-1.11.0-rc1

issue：

when yun

```
./configure
make
```

throw

```
[root@server tinyproxy-1.11.0-rc1]# make
make  all-recursive
make[1]: Entering directory `/opt/module/tinyproxy-1.11.0-rc1'
Making all in src
make[2]: Entering directory `/opt/module/tinyproxy-1.11.0-rc1/src'
  CCLD   tinyproxy
conf.o: In function `config_parse':
/opt/module/tinyproxy-1.11.0-rc1/src/conf.c:419: undefined reference to `config_directive_find'
collect2: ld 返回 1
make[2]: *** [tinyproxy] 错误 1
make[2]: Leaving directory `/opt/module/tinyproxy-1.11.0-rc1/src'
make[1]: *** [all-recursive] 错误 1
make[1]: Leaving directory `/opt/module/tinyproxy-1.11.0-rc1'
make: *** [all] 错误 2
```

config_directive_find undefined？

centos7 is work

What should I do？

thanks

**Comment by rofl0r** [comment]
did you download the release tarball or the github archive ?
what is the ouput of the configure run ?

also try `./configure ac_cv_path_GPERF=no`

**Comment by downdawn** [comment]
`./configure ac_cv_path_GPERF=no`
work!

thanks

**Comment by rofl0r** [comment]
ok, could you answer my questions anyway, i'm trying to figure out what went wrong.

**Comment by downdawn** [comment]
Sorry for replying to you so late.
Because I directly "yum install tinyproxy", the version is 1.8.3, and there is no basic HTTP authentication. Then I saw that Version 1.10.0 added this feature, so my process is:
```
wget -P /opt/software https://github.com/tinyproxy/tinyproxy/releases/download/1.11.0-rc1/tinyproxy-1.11.0-rc1.tar.gz

mkdir /opt/module
cd /opt/software
tar -zxvf tinyproxy-1.11.0-rc1.tar.gz -C /opt/module/

cd /opt/module/tinyproxy-1.11.0-rc1/
yum -y install gcc

./configure
make
make install
```

When running to "make", an error occurs:

```
make  all-recursive
make[1]: Entering directory `/opt/module/tinyproxy-1.11.0-rc1'
Making all in src
make[2]: Entering directory `/opt/module/tinyproxy-1.11.0-rc1/src'
  CCLD   tinyproxy
conf.o: In function `config_parse':
/opt/module/tinyproxy-1.11.0-rc1/src/conf.c:419: undefined reference to `config_directive_find'
collect2: ld returns 1
make[2]: *** [tinyproxy] error 1
make[2]: Leaving directory `/opt/module/tinyproxy-1.11.0-rc1/src'
make[1]: *** [all-recursive] error 1
make[1]: Leaving directory `/opt/module/tinyproxy-1.11.0-rc1'
make: *** [all] error 2
```

Finally, I have a question, why not release 1.10.0 and above in CentOS. . (Novice question)
thanks

**Comment by downdawn** [comment]
By the way, maybe this server is special, I don't have this problem on other CentOS7 servers

**Comment by rofl0r** [comment]
> When running to "make", an error occurs:

yes, you already said that, but i need to see what ./configure output is to find out what went wrong.

> why not release 1.10.0 and above in CentOS

centos is really conservative with their packages, but maybe they don't even know a newer release is available. you could open a ticket on centos bug tracker and tell them.

**Comment by downdawn** [comment]
[root@server tinyproxy-1.11.0-rc1]# ./configure
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for socket in -lsocket... no
checking for htonl in -lsocket... no
checking for yp_get_default_domain... no
checking for gethostname in -lnsl... yes
checking for inet_aton in -lresolv... yes
checking for ANSI C header files... (cached) yes
checking whether time.h and sys/time.h may both be included... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking for memory.h... (cached) yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking values.h usability... yes
checking values.h presence... yes
checking for values.h... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking whether lstat dereferences a symlink specified with a trailing slash... yes
checking for strlcpy... no
[root@server0946 tinyproxy-1.11.0-rc1]# ./configure
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for socket in -lsocket... no
checking for htonl in -lsocket... no
checking for yp_get_default_domain... no
checking for gethostname in -lnsl... yes
checking for inet_aton in -lresolv... yes
checking for ANSI C header files... (cached) yes
checking whether time.h and sys/time.h may both be included... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking for memory.h... (cached) yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking values.h usability... yes
checking values.h presence... yes
checking for values.h... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking whether lstat dereferences a symlink specified with a trailing slash... yes
checking for strlcpy... no
checking for strlcat... no
checking for setgroups... yes
checking to see if compiler understands -fdiagnostics-show-option -Wall -Wextra -Wno-unused-parameter -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wfloat-equal -Wundef -Wformat=2 -Wlogical-op -Wmissing-include-dirs -Wformat-nonliteral -Wold-style-definition -Wpointer-arith -Waggregate-return -Winit-self -Wpacked --std=c89 -ansi -Wno-overlength-strings -Wno-long-long -Wno-overlength-strings -Wdeclaration-after-statement -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wcast-qual -Wcast-align -Wwrite-strings -Wp,-D_FORTIFY_SOURCE=2 -fno-common... yes
checking to see if linker understands -z,defs... yes
checking for pod2man... /usr/bin/pod2man
checking for gperf... /usr/bin/gperf
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating data/Makefile
config.status: creating data/templates/Makefile
config.status: creating etc/Makefile
config.status: creating docs/Makefile
config.status: creating docs/man5/Makefile
config.status: creating docs/man5/tinyproxy.conf.txt
config.status: creating docs/man8/Makefile
config.status: creating docs/man8/tinyproxy.txt
config.status: creating m4macros/Makefile
config.status: creating tests/Makefile
config.status: creating tests/scripts/Makefile
config.status: creating scripts/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

**Comment by rofl0r** [comment]
the only issue i can see in your output is that you have gperf installed:
```
checking for gperf... /usr/bin/gperf
```
since you said it works with `./configure ac_cv_path_GPERF=no` the issue is probably that the gperf version is too old, but then there should be another make error earlier on when gperf is invoked, before finally failing with the error you pasted.

**Comment by downdawn** [comment]
Do You want me to copy the logs? It seems a little long.

**Comment by rofl0r** [comment]
yes, please. it shouldnt be that long since there are only few c files to compile.
it should be sufficient if you do just run `make 2>log.txt` and paste the contents of log.txt.

**Comment by downdawn** [comment]
```
[root@server tinyproxy-1.11.0-rc1]# make
make  all-recursive
make[1]: Entering directory `/opt/module/tinyproxy-1.11.0-rc1'
Making all in src
make[2]: Entering directory `/opt/module/tinyproxy-1.11.0-rc1/src'
  CC     acl.o
  CC     anonymous.o
  CC     buffer.o
  CC     child.o
  CC     conf-tokens.o
  CC     conf.o
  CC     conns.o
  CC     daemon.o
  CC     heap.o
  CC     html-error.o
  CC     http-message.o
  CC     log.o
  CC     network.o
  CC     reqs.o
reqs.c: 在函数‘relay_connection’中:
reqs.c:1149: 警告：初始值设定周围缺少花括号 [-Wmissing-braces]
reqs.c:1149: 警告：(在‘fds[0]’的初始化附近) [-Wmissing-braces]
reqs.c:1149: 警告：缺少初始值设定 [-Wmissing-field-initializers]
reqs.c:1149: 警告：(在‘fds[0].events’的初始化附近) [-Wmissing-field-initializers]
reqs.c: 在函数‘get_request_entity’中:
reqs.c:1434: 警告：初始值设定周围缺少花括号 [-Wmissing-braces]
reqs.c:1434: 警告：(在‘fds[0]’的初始化附近) [-Wmissing-braces]
reqs.c:1434: 警告：缺少初始值设定 [-Wmissing-field-initializers]
reqs.c:1434: 警告：(在‘fds[0].events’的初始化附近) [-Wmissing-field-initializers]
  CC     sock.o
  CC     stats.o
  CC     text.o
  CC     main.o
  CC     utils.o
  CC     upstream.o
  CC     basicauth.o
  CC     orderedmap.o
orderedmap.c: 在函数‘orderedmap_create’中:
orderedmap.c:33: 警告：缺少初始值设定 [-Wmissing-field-initializers]
orderedmap.c:33: 警告：(在‘o.map’的初始化附近) [-Wmissing-field-initializers]
orderedmap.c: 在函数‘orderedmap_append’中:
orderedmap.c:54: 警告：‘index’的声明隐藏了一个全局声明 [-Wshadow]
/usr/include/string.h:489: 警告：被隐藏的声明在这里 [-Wshadow]
  CC     loop.o
  CC     mypoll.o
  CC     connect-ports.o
  CC     filter.o
  CC     reverse-proxy.o
  CC     transparent-proxy.o
  CCLD   tinyproxy
conf.o: In function `config_parse':
/opt/module/tinyproxy-1.11.0-rc1/src/conf.c:419: undefined reference to `config_directive_find'
collect2: ld 返回 1
make[2]: *** [tinyproxy] 错误 1
make[2]: Leaving directory `/opt/module/tinyproxy-1.11.0-rc1/src'
make[1]: *** [all-recursive] 错误 1
make[1]: Leaving directory `/opt/module/tinyproxy-1.11.0-rc1'
make: *** [all] 错误 2
```

There's some Chinese, but you should be able to understand it

**Comment by rofl0r** [comment]
there's nothing in there concerning the generation of the gperf hash table..

> There's some Chinese, but you should be able to understand it

you can make that english by exporting LC_ALL=C in the shell

**Comment by mckaygerhard** [comment]
i have same problem in my deban stable servers.. please  any news on this?

`/src/tinyproxy-1.11.0-rc1/src/conf.c:419: undefined reference to `config_directive_find'`

**Comment by rofl0r** [comment]
as mentioned above, you need `./configure ac_cv_path_GPERF=no`. i'll prepare a fix for the issue soon.

**Comment by rofl0r** [comment]
this should now be fixed in master. @downdawn @mckaygerhard could you both please test whether it does indeed fix the issue ?

**Comment by mckaygerhard** [comment]
i will test right now and post feedback in hours..  currently i backported the same package from debian unstable to wheeze, jessie and inclusivelly squeeze ...
