### ISSUE TITLE
How to finish tinyproxy install

### ISSUE THREAD

**Issue by aluisioalves123** [tinyproxy/tinyproxy#339]
Im trying to install the latest version, which is the 1.11, because the problem 
"Waiting servers (0) is less than MinSpareServers (5). Creating new child."
is fixed.

I cant install the latest version with apt-get install, so I have to install it with make, ./configure and etc...

I follow up the instructions on the main page README but after that I dont know what to do, can someone help me, please?

**Comment by rofl0r** [comment]
> so I have to install it with make, ./configure and etc...

the order is wrong. if you expect help, then provide details. usually one runs make install as last step after which tinyproxy is installed. (and typically one runs `./configure --prefix=/usr`)
