### ISSUE TITLE
PIDFile=references a path below legacy directory /var/run/

### ISSUE THREAD

**Issue by aluisioalves123** [tinyproxy/tinyproxy#340]
I'm trying to start Tinyproxy but I always get this message at
systemctl status tinyproxy.service

/etc/systemd/system/tinyproxy.service:8: PIDFile= references a path below legacy directory /var/run/

**Comment by rofl0r** [comment]
tinyproxy ships without systemd service. the pidfile path can be configured in /etc/tinyproxy.conf
