### ISSUE TITLE
User need to be defined in systemd unit

### ISSUE THREAD

**Issue by wickedsp1d3r** [tinyproxy/tinyproxy#342]
Hey,
```
$ tinyproxy -v
tinyproxy 1.11.0-rc1
```
My `tinyproxy.conf` has:
```
...
Group tinyproxy
User tinyproxy
...
```
I am running Tinyproxy as `systemd` service. The unit file has:
```
[Service]
...
User=tinyproxy
```

The proxy is working fine when the `User=` parameter is defined also in the `systemd` unit. If I comment it out, proxy is not connecting anymore. Log after restarting and `curl`ing to https://github.com:
```
...: Initializing tinyproxy ...
...: Reloading config file
...: Adding Port [443] to the list allowed by CONNECT
...: Added address [127.0.0.1] to listen addresses.
...: Reloading config file finished
...: listen_sock called with addr = '127.0.0.1'
...: trying to listen on host[127.0.0.1], family[2], socktype[1], proto[6]
...: listening on fd [3]
...: Now running as group "tinyproxy".
...: Now running as user "tinyproxy".
...: Setting the various signals.
...: Starting main loop. Accepting connections.
...: Connect (file descriptor 5): 127.0.0.1
...: Request (file descriptor 5): CONNECT github.com:443 HTTP/1.1
...: opensock: opening connection to github.com:443
...: opensock: Could not retrieve address info for github.com:443: Temporary failure in name resolution
```
My question is why I need to add `User=` parameter to the `systemd` unit for the proxy to work - why keywords in the config file are not enough?

**Comment by rofl0r** [comment]
i don't know - maybe try to add `strace -o log.txt tinyproxy ...` to the systemd service to see what fails in strace log - probably some permission problem.
theoretically it should be sufficient to only specify the user in the systemd file but not in the tinyproxy config, since switching to a different user assumes root privs.

**Comment by wickedsp1d3r** [comment]
I tried to debug the unit with `strace` without getting any notable advice.
This is not a problem. It would just be nice to know the reason for this.

Btw, what [capabilities](https://wiki.archlinux.org/index.php/capabilities) Tinyproxy needs in its execution?

**Comment by rofl0r** [comment]
> Btw, what capabilities Tinyproxy needs in its execution?

actually none, if you bind to a port > 1024

**Comment by wickedsp1d3r** [comment]
> actually none, if you bind to a port > 1024

Yeah. I am using the default (8888) port.

When I run Tinyproxy standalonely as `tinyproxy` user, it works fine (`sudo -u tinyproxy tinyproxy -d`). But when run as a `systemd` service, the user needs to be explicitly defined in the unit file (the unit lives in `/etc/systemd/system/`). I am not so familiar with `systemd` to be able to understand this.
