### ISSUE TITLE
SIGHUB vs SIGUSR1 for configuration reloading

### ISSUE THREAD

**Issue by Xon** [tinyproxy/tinyproxy#343]
Currently v1.10 allows `SIGHUB` (for log rotation/configuration reloading) when in non-daemonized mode, while v1.11 does not. 

Confusingly in v1.11, `SIGUSR1`  appears to trigger the same code-path as `SIGHUB`

The comment in "do not catch SIGHUP in foreground-mode"  https://github.com/tinyproxy/tinyproxy/commit/8ba0ac4e8662ddc9c109229594f8a8ff0471b0df implies a foreground tinyproxy is always on a console. Depending on systemd unit-file configuration, this may not be the case.

Systemd support a `type=simple` service definition, which runs the target process as a simple blocking process, that is identical to being in the foreground. This way PID file management isn't required, and even explicit logging isn't required.

The current v1.10 unit file I'm using is;
```
[Unit]
Description=Tinyproxy lightweight HTTP Proxy
After=network.target
Documentation=man:tinyproxy(8) man:tinyproxy.conf(5)

[Service]
Type=simple
ExecStart=/usr/local/bin/tinyproxy -d
ExecReload=/bin/kill -HUP $MAINPID
PrivateDevices=yes
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Obviously the reload statement can be changed, but it would be nice if it was a simple drop-in replacement to v1.10, much how the deprecated configuration options are ignored (but warned).

**Comment by rofl0r** [comment]
> Obviously the reload statement can be changed

yes, this is what should be done. it's been a historic mistake that SIGHUP didn't terminate the proxy in foreground mode, and the intention is to make tinyproxy better, not holding on to past mistakes.
