### ISSUE TITLE
PidFile should be owned by configured User/Group

### ISSUE THREAD

**Issue by helmat** [tinyproxy/tinyproxy#348]
The PidFile is created before change_user(), so it's normally owned by root. Consequently upon exit, the attempt to remove the PidFile fails: 'Could not remove PID file "/var/run/tinyproxy.pid": Permission denied.'

Fix: chown/chgrp the PidFile by the configured User/Group before dropping privilege. This allows the PidFile to be removed upon exit.

**Comment by rofl0r** [comment]
this was done in the past before this CVE: https://github.com/tinyproxy/tinyproxy/issues/106

my personal opinion is that pid files are an ill-advised historical concept (along the lines of FTP) and shouldn't be used at all. any reasonable service supervision suite (including the less-reasonable systemd) can retrieve the PID of processes it started and save it. and if you launch the process as user (hopefully with logging to stdout) the pid is displayed in every single line printed to the log, or can be grabbed from ps aux output.

**Comment by helmat** [comment]
Yeah, I noticed #106 just after raising this issue. However in my environment I'm seeing ISC BIND, ClamAV, and SpamAssassin also writing private-uid owned PID files. That doesn't rhyme with the CVE's reasoning obviously.

I agree PID files should best be handled by a daemon supervisor.
