### ISSUE TITLE
Feature request: read config from stdin

### ISSUE THREAD

**Issue by smattheis** [tinyproxy/tinyproxy#359]
Thanks for the fantastic software. Would it be a big issue to enable reading the config from stdin? As an example, I would like to start a tinyproxy in upstream mode as follows:

``` bash
cat tinyproxy.conf.template | sed -i 's/<pass>/password/' | tinyproxy -d
```
The reason is that I want to run an upstream proxy in a corporate Zuul CI system with a job pipeline where start-up jobs do some preparation and configuration while subsequent jobs perform software builds and checks. The start-up jobs have access to secrets and passwords while the build and check jobs must not have access to those secrets and passwords. The jobs run all in a sequence on the same virtual machine such that a password in a file is readable by build and check jobs. (Simply deleting the file after starting the tinyproxy daemon doesn't seem save to me ...)

**Comment by rofl0r** [comment]
that feature is built into linux:
```
cat tinyproxy.conf | src/tinyproxy -d -c /proc/self/fd/0
```

**Comment by smattheis** [comment]
Yep, that's exactly what I need. Didn't know we can pass a file descriptor. Nice and elegant. Many thanks.
