### ISSUE TITLE
Debian 10, Bind directive not working

### ISSUE THREAD

**Issue by stevehjhu** [tinyproxy/tinyproxy#361]
Debian 10, installed tinyproxy using apt. This proxy system has two network interfaces, one on my internal network, and one public to the outside world. All proxy requests come from the internal network and go out to the world via the public network interface.  I have the Bind directive set to the public static IP of my public network interface and I have UFW set to allow outgoing traffic on ports 80 and 443 from the same public network interface.  

What I'm seeing is UFW is blocking the outgoing as the requests are trying to be sent using the internal network interface instead of the public interface specified in the Bind directive in tinyproxy.conf.  I've read some older message boards describing this but they all say this was fixed since then.  I need to have all proxy traffic going out on port 80 and 443 of the public interface.  

Any suggestions as to how to make this happy?  Cheers!

**Comment by rofl0r** [comment]
> Debian 10, installed tinyproxy using apt.

which tinyproxy version? i'd expect that the tinyproxy shipped by debian is 4 releases aka 5 years behind.

**Comment by stevehjhu** [comment]
1.10.0-2+deb10u1

**Comment by rofl0r** [comment]
you gotta compile 1.11.0 from source, dozens of bugs have been fixed including bind-related ones.

**Comment by stevehjhu** [comment]
Thanks.  I did exactly that about 30 mins ago.  I have it running and I think it's doing what I want.  The weird part is that I setup my UFW so that only the public interface is allowed out.  When I start tinyproxy, UFW logs show it blocking the proxy requests on the private interface (which they are all coming from).  I had to add rules for ports 80 and 443 for the private interface so that the proxy requests could get out.  The tinyproxy logs say that there is binding to the correct public static IP so I guess it's doing what I want and proxy traffic appears to be coming from the one public static IP.  Still, all my curl tests time out.  Something is still not right.

**Comment by rofl0r** [comment]
wireshark is a great tool to debug such issues, ftr

**Comment by stevehjhu** [comment]
OK, so I'm further along and I guess I should close this thread as the bind part appears to work with the newest version.  My curl tests work on the proxy server itself so the breakdown in communication now is somewhere between my clients and the proxy server itself.  I'm sure I'm just missing something small and stupid in the config.

Thanks for the help rofl0r!!
