### ISSUE TITLE
https cant works

### ISSUE THREAD

**Issue by downdawn** [tinyproxy/tinyproxy#362]
tail -f /var/log/tinyproxy/tinyproxy.log

CONNECT   Apr 23 02:23:07 [19659]: Request (file descriptor 6): 
WARNING   Apr 23 02:23:12 [19659]: Could not retrieve all the headers from the client
ERROR     Apr 23 02:23:12 [19659]: Error reading readable client_fd 6
WARNING   Apr 23 02:23:12 [19659]: Could not retrieve request entity

my config:

`User nobody
Group nobody
Port 8888
BindSame yes
Timeout 20
DefaultErrorFile "/usr/local/share/tinyproxy/default.html"
StatFile "/usr/local/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
MaxClients 500
ViaProxyName "tinyproxy"
BasicAuth admin downdawn

DisableViaHeader Yes
Anonymous "Host"
Anonymous "Authorization"
Anonymous "Cookie"
ConnectPort 443
ConnectPort 563
`

**Comment by rofl0r** [comment]
remove connectport directives, use latest tinyproxy 1.11.0, read the issue here about GFW https://github.com/tinyproxy/tinyproxy/issues/162
