### ISSUE TITLE
Waiting servers (-1) exceeds MaxSpareServers (50). Killing child.

### ISSUE THREAD

**Issue by pk1057** [tinyproxy/tinyproxy#365]
Hello,
on a Ubuntu 20.04.2 LTS with tinyproxy 1.10 we sometimes have a situation where tinyproxy is not responding anymore.

In the logfiles we saw plenty of
NOTICE   Waiting servers (-1) exceeds MaxSpareServers (50). Killing child.

And after a while:
ERROR    No more children left. Shutting down.

After this tinyproxy is not reachable anymore.

MinSpareServer was set to 10

**Comment by rofl0r** [comment]
this bug is fixed in 1.11.0. please urge debian maintainers to upgrade the package.
