### ISSUE TITLE
Proxy Auth not working 

### ISSUE THREAD

**Issue by uniqsyshnf** [tinyproxy/tinyproxy#368]
Hi , 
 /usr/sbin/tinyproxy -version
tinyproxy 1.11.0

Config file 
 cat /root/PROXY/proxy103.conf
User nobody
Group nobody

Port 9821
Listen X.X.X.X
BindSame yes
Timeout 600
PidFile "tmp/proxy103.pid"
Logfile "tmp/proxy103.log"
LogLevel Warning
MaxClients 30
MinSpareServers 0
MaxSpareServers 1
StartServers 1
MaxRequestsPerChild 0
DisableViaHeader yes
BasicAuth usertest userpass

Try using auth with curl : 
curl -L http://google.com/ --proxy http://X.X.X.X:9821/ 
and page open without any username and pass 

What a configuration need to be for only user in config can access to sites via proxy ? 

Thanks

**Comment by uniqsyshnf** [comment]
My bad. Need kill proccess after changes and start

**Comment by rofl0r** [comment]
> /usr/sbin/tinyproxy

what distro is that? tinyproxy should be installed into */bin, not */sbin

**Comment by uniqsyshnf** [comment]
Centos 7


-------- Original message --------
From: rofl0r ***@***.***>
Date: 5/10/21 18:28 (GMT+02:00)
To: tinyproxy/tinyproxy ***@***.***>
Cc: Helpdesk | Host And Found ***@***.***>, State change ***@***.***>
Subject: Re: [tinyproxy/tinyproxy] Proxy Auth not working (#368)


/usr/sbin/tinyproxy

what distro is that? tinyproxy should be installed into */bin, not */sbin
