### ISSUE TITLE
Performance Issue when used a scanning proxy

### ISSUE THREAD

**Issue by thesubmitter** [tinyproxy/tinyproxy#375]
In my use case. I would like to use tinyproxy as a proxy for BURP to scan websites it doesn't have direct access too. I have found that after a while it stops working properly. Eitehr process limit is hit, or because the conenctions aren't closed or something similar. Might be that burp doesn't close the scan connections properly. I tried adjusting clients and timeout, neither seemd to have a desired impact. I didn't reduce timeout below 30s because I still wanted to connect to a slow site. There maybe needs to be some variable to terminate unused processes or something...

**Comment by rofl0r** [comment]
you probably didn't use tinyproxy 1.11.0 but some old version shipped on your OS-
