### ISSUE TITLE
tinyproxy upstream password must be ascii characters

### ISSUE THREAD

**Issue by demigoldberg** [tinyproxy/tinyproxy#376]
when using upstream with a password that contains non-ascii characters like: ! ~ @ etc
autentication failed

for example:
upstream http user:Password!@<server>:<port>

**Comment by rofl0r** [comment]
see https://github.com/tinyproxy/tinyproxy/pull/326 - only @ isn't allowed currently.

**Comment by demigoldberg** [comment]
According to #326 @ should be supported ... is there any change that @ will be allowed roo ?

**Comment by rofl0r** [comment]
326 is a PR that's not yet merged, because i have a local branch with incompatible changes.
