### ISSUE TITLE
https proxy doesn't work even with upstream proxy

### ISSUE THREAD

**Issue by pansila** [tinyproxy/tinyproxy#379]
I set up an upstream proxy (anti GFW proxy) for tinyproxy, which should not be confused by `GFW`(China firewall) anymore. I've checked the issue #162 and I believe this is different from that, any suggestions?

I added some debug log to `src/reqs.c` in the function `get_all_headers` after reading each line. It seems all http headers are encrypted, thus tinyproxy keeps complaining `Could not retrieve all the headers from the client`.
```
CONNECT   Jun 07 16:04:16.531 [20274]: Connect (file descriptor 8): 172.17.64.1
CONNECT   Jun 07 16:04:16.545 [20274]: Request (file descriptor 8): 
INFO      Jun 07 16:04:16.547 [20274]: >>> 0c&{cqaV{xL

INFO      Jun 07 16:04:16.549 [20274]: >>> Mr ?II7ctO

INFO      Jun 07 16:04:16.550 [20274]: >>> yϵ{^h7
INFO      Jun 07 16:04:16.552 [20274]: >>>
INFO      Jun 07 16:04:16.553 [20274]: >>>
CONNECT   Jun 07 16:04:20.973 [20274]: Connect (file descriptor 9): 172.17.64.1
CONNECT   Jun 07 16:04:20.987 [20274]: Request (file descriptor 9): 
INFO      Jun 07 16:04:20.989 [20274]: >>> *QQ2
INFO      Jun 07 16:04:20.991 [20274]: >>>
INFO      Jun 07 16:04:20.993 [20274]: >>>
CONNECT   Jun 07 16:04:26.083 [20274]: Connect (file descriptor 10): 172.17.64.1
CONNECT   Jun 07 16:04:26.085 [20274]: Request (file descriptor 10): 
INFO      Jun 07 16:04:26.087 [20274]: >>>
INFO      Jun 07 16:04:26.089 [20274]: >>>
WARNING   Jun 07 16:04:30.006 [20274]: Could not retrieve all the headers from the client
```

tinyproxy.conf
```
User tinyproxy
Group tinyproxy
Port 8888
Timeout 600
DefaultErrorFile "/usr/local/share/tinyproxy/default.html"
StatFile "/usr/local/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
Upstream http 127.0.0.1:1088
MaxClients 100
Allow 172.17.64.1
Allow 127.0.0.1
Allow ::1
ViaProxyName "tinyproxy"
```

PS:
1. I'm testing the https proxy in the `Chrome` with the extenstion `SwitchyOmega`.
2. tinyproxy version: tip of the branch master (7168a42)
3. [stackoverflow](https://stackoverflow.com/questions/36214703/tinyproxy-unable-to-forward-connect-methods) provides an explanation while it's for transparent proxy, I'm using https proxy so I think this is a different case as well.

**Comment by rofl0r** [comment]
does it work if you use your `Upstream http 127.0.0.1:1088` directly in firefox ?

**Comment by pansila** [comment]
@rofl0r Yes, it works.

**Comment by rofl0r** [comment]
so as it turned out in the other 3 issues you openened that you used tinyproxy as "https" proxy, where you should have selected "http", so we can pretty confidently assume that it works as expected when you properly configure your browser.

**Comment by pansila** [comment]
@rofl0r Thanks for the clarification.
