### ISSUE TITLE
Need direction on ACL type functionality

### ISSUE THREAD

**Issue by stevekaten** [tinyproxy/tinyproxy#380]
I'd like an option to run an ACL list where I can grant a specific source address (eg, 10.10.10.12/32) access to a specific domain (eg, tacobell.com).

Is there a way to accomplish this with the built-in tinyproxy functionality?  I've looked over filters and upstream but haven't been able to get anything to work.  Any suggestions would be helpful.

**Comment by rofl0r** [comment]
well, i guess you could run 2 tinyproxy instances, one listening e.g. on localhost port 9000 with Allow only for that ip range, and a second one on network-reachable interface (e.g. 10.10.10.1 port 8000) with upstream for tacobell.com set to localhost:9000 without any ACL restriction, in which case users outside that range would get a 403 and users inside would be able to load that page.

**Comment by stevekaten** [comment]
Thanks @rofl0r.  I thought bout this as an implementation, but it seems pretty kludgy.  Was hoping there was a better alternative.
