### ISSUE TITLE
AWS DNS Config 

### ISSUE THREAD

**Issue by attahkhan016** [tinyproxy/tinyproxy#39]
Hello i am using a AWS load balancer as a proxy target to the proxy servers , can you help me with this , as the AWS Load balancer provides a DNS , can you help me out to where to config it in the tinyproxy config .

(aws)Proxy server 1&2------> (aws) Load balancer -------> internet

**Comment by obnoxxx** [comment]
I'd don't get it. I think it would be something like this:

```
clients ----> (aws) load balanced --->(aws)proxy server 1& 2 ---> internet
```

- Were are the clients living? in aws or outside?
- how does dns come into play?

**Comment by rofl0r** [comment]
closing due to lack of feedback.
