### ISSUE TITLE
netmask not working in upstream rule

### ISSUE THREAD

**Issue by huaraz** [tinyproxy/tinyproxy#394]
## Tinyproxy version
tinyproxy 1.11.0-rc1-42-git-39d7bf6

## Issue
I try to use an upstream rule
upstream none "192.168.0.0/255.255.0.0"
which fails 
WARNING   Aug 22 14:25:06.930 [16716]: line 186: Nonsense upstream rule: failed to parse netmask

The following rule works
upstream none "192.168.0.0/16"

But both versions of mask are documented as correct config lines.

Markus

**Comment by rofl0r** [comment]
the upstream netmask parsing was rewritten since 1.11.0 release. please try if master fixes it.

**Comment by huaraz** [comment]
It is the master

~/git/tinyproxy$ git branch
* master

**Comment by rofl0r** [comment]
should be fixed now, thanks for the report.
