### ISSUE TITLE
autogen.sh: 9: Bad substitution

### ISSUE THREAD

**Issue by dflock** [tinyproxy/tinyproxy#398]
## Tinyproxy version
Current git master: d3d8943fe45e53a39864070b74fdfa95dd93f1f0

## Issue

Trying to compile tinyproxy on:

```
OS: Xubuntu 20.04.3 LTS x86_64 
Kernel: 5.4.0-80-generic
Shell: bash 5.0.17
DE: Xfce 4.16 
```

I did this and got an error running autogen:

```console
$ gh repo clone tinyproxy/tinyproxy
$ cd tinyproxy/
$ ./autogen.sh 
./autogen.sh: 9: Bad substitution
```

I made the following change to `autogen.sh` and it worked for me:

```diff
diff --git a/autogen.sh b/autogen.sh
index fb6da78..6a82a6a 100755
--- a/autogen.sh
+++ b/autogen.sh
@@ -1,10 +1,10 @@
-#!/bin/sh
+#!/usr/bin/env bash
+set -o xtrace
 
 srcdir=`dirname $0`
 test -z "$srcdir" && srcdir=.
 ORIGDIR=`pwd`
 
-set -x
 
 cd $srcdir
```

Once I made that change, autogen ran fine

Presumably this work fine for everyone else, so not sure what's going on here?

**Comment by rofl0r** [comment]
/bin/sh is dash is on ubuntu, so maybe your ubuntu ships a broken dash ?
set -x is standard way to toggle debug output on, and works fine with my dash 0.5.11.2.
please report this to your distro's bugtracker.

**Comment by dflock** [comment]
Sorry should have been more clear - it's [line 9 that causes the error](https://github.com/tinyproxy/tinyproxy/blob/d3d8943fe45e53a39864070b74fdfa95dd93f1f0/autogen.sh#L9) This first 9 lines of `autogen.sh` currently look like this:

```sh
#!/bin/sh

srcdir=`dirname $0`
test -z "$srcdir" && srcdir=.
ORIGDIR=`pwd`

set -x

cd $srcdir
```

So, it looks like it's the:

```
srcdir=`dirname $0`
...
cd $srcdir
```

pair that aren't working.

Changing it to use Bash fixes it, so yes, presumably something to do with Dash. I currently have Dash version 0.5.10.2

**Comment by rofl0r** [comment]
either way i don't see a substitution going on here. please report this to ubuntu launchpad so they can get their dash fixed (and hopefully updated).
