### ISSUE TITLE
Add SOCKS support

### ISSUE THREAD

**Issue by dave-kennedy** [tinyproxy/tinyproxy#40]
It looks like somebody has already done the work: https://github.com/koolshare/tinyproxy

**Comment by rofl0r** [comment]
oh nice. the socks connect code/comments look *very* similar to the one from proxychains core.c ...

**Comment by dave-kennedy** [comment]
Ah, does that mean we can't use it?

**Comment by rofl0r** [comment]
at the contrary, both projects use GPL-2.0.

**Comment by dave-kennedy** [comment]
I see. Not knowing you and this being the internet and all, I thought maybe that was sarcasm :)

**Comment by rofl0r** [comment]
well i saw the code that very much resembles the proxychains code (which i'm very familiar with as i'm maintaining its successor) but no attribution... otoh that's nothing unexpected from chinese coders... and then i doubt that netcreature, the original author cares, plus the method of settings up socks packets is pretty straightforward and more or less dictated by the RFC, so who cares. definitely a nice feature to have.

**Comment by crosscutrat** [comment]
SOCKS support for each upstream config would be a great feature to have in tinyproxy without having to apply patches.  Anything that would help get a patch like this pulled:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=392848)#12

**Comment by rofl0r** [comment]
oh nice find. so the patch that was used in OPs link was actually taken from the debian bugtracker.

**Comment by rofl0r** [comment]
i opened a PR with the updated patch so it can be discussed here on GH.

**Comment by crosscutrat** [comment]
Awesome @rofl0r ... Thanks!

**Comment by rofl0r** [comment]
merged as https://github.com/tinyproxy/tinyproxy/commit/8906b0734e5c61016d9d4090507f010b2006292d
