### ISSUE TITLE
can tinyproxy support keep-alive

### ISSUE THREAD

**Issue by siegelionnet** [tinyproxy/tinyproxy#41]

**Comment by obnoxxx** [comment]
can you elaborate a bit?

**Comment by kiran-redhat** [comment]
@obnoxxx I think he @siegelionnet  is talking about something like this: https://stackoverflow.com/questions/24882816/tcp-socket-over-http-proxy-disconnects-after-idle-timeout

What I also faced is: when upstream takes too long (for example more than 4 minutes) log is not getting written into *.log file (issue1) and request and responses hangs without getting timed out after 4 minutes(issue2). 

Note: I can see "Idle Timeout (after select) as 61 > 60." when timeout is set to 60 seconds.

**Comment by rofl0r** [comment]
closing due to lack of feedback.
