### ISSUE TITLE
Trying to use tinyproxy to inject a header and forward to a different port on same machine

### ISSUE THREAD

**Issue by Charles-Schleich** [tinyproxy/tinyproxy#410]
Hello, I have the scenario where i am running tinyproxy (v1.11.0) and I simply want to add a header and forward the request to a service running on the same machine. 
The other service is running on 127.0.0.1:9000 and requires a header `UniqueHeader` to be set.

tinyproxy.conf
```
Port 8888
Bind 127.0.0.1

LogLevel Info
upstream http 0.0.0.0:9001
upstream http 127.0.0.1:8888 "127.0.0.1:9001"

MaxClients 100
Allow 127.0.0.1
Allow ::1
AddHeader "UniqueHeader" "HeaderVal"
ViaProxyName "tinyproxy"

StartServers 5
MinSpareServers 5
MaxSpareServers 10 
MaxRequestsPerChild 0
```
I am not entirely sure what i am doing wrong, 
I keep getting
 
`Bad Request You tried to connect to the machine the proxy is running on`
I'm clearly wrong with `upstream http 127.0.0.1:8888 "127.0.0.1:9001"`

What is the correct upstream declaration to achieve this ?

Thank you in advance.

**Comment by rofl0r** [comment]
is the other service a proxy or a http server ? if the later you want to configure tinyproxy as reverse proxy without upstream. if the former you need to change your upstream statement to `upstream http 127.0.0.1:9000`

**Comment by Charles-Schleich** [comment]
Awesome stuff, looks like its working as a reverse proxy without upstream. 
config for prosperity.

```
Port 8888
listen 127.0.0.1

StartServers 5
MinSpareServers 5
MaxSpareServers 10 
MaxRequestsPerChild 0

LogLevel Info

MaxClients 100
Allow 127.0.0.1
Allow ::1
AddHeader "UniqueHeader" "HeaderVal"

ViaProxyName "tinyproxy"

ConnectPort 8888
ConnectPort 80

ConnectPort 443
ConnectPort 563

ReversePath "/" "http://localhost:9000/"
ReversePath "/path1/" "http://localhost:9000/"
ReversePath "/path2/" "http://localhost:9000/"

ReverseOnly Yes
ReverseMagic Yes
ReverseBaseURL "http://127.0.0.1:8888/"
```
Thanks @rofl0r !
