### ISSUE TITLE
If a request is made to a proxy port (public IP address), a proxy loop will occur

### ISSUE THREAD

**Issue by YJ-UP** [tinyproxy/tinyproxy#413]
tinyproxy version 1.11.0

If I request TinyProxy on a public IP address, no connection is available to TinyProxy

I hope you can give me a solution

**Comment by YJ-UP** [comment]
``CONNECT   Jan 15 20:11:41.294 [25855]: Established connection to host "Public IP Address" using file descriptor 178.
CONNECT   Jan 15 20:11:41.295 [25855]: Connect (file descriptor 179): Public IP Address
CONNECT   Jan 15 20:11:41.297 [25855]: Request (file descriptor 179): GET / HTTP/1.0
INFO      Jan 15 20:11:41.299 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 179
INFO      Jan 15 20:11:41.301 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.302 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.303 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.307 [25855]: Established connection to host "Public IP Address" using file descriptor 180.
CONNECT   Jan 15 20:11:41.309 [25855]: Connect (file descriptor 181): Public IP Address
CONNECT   Jan 15 20:11:41.310 [25855]: Request (file descriptor 181): GET / HTTP/1.0
INFO      Jan 15 20:11:41.312 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 181
INFO      Jan 15 20:11:41.314 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.315 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.316 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.320 [25855]: Established connection to host "Public IP Address" using file descriptor 182.
CONNECT   Jan 15 20:11:41.322 [25855]: Connect (file descriptor 183): Public IP Address
CONNECT   Jan 15 20:11:41.323 [25855]: Request (file descriptor 183): GET / HTTP/1.0
INFO      Jan 15 20:11:41.326 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 183
INFO      Jan 15 20:11:41.327 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.328 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.329 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.334 [25855]: Established connection to host "Public IP Address" using file descriptor 184.
CONNECT   Jan 15 20:11:41.336 [25855]: Connect (file descriptor 185): Public IP Address
CONNECT   Jan 15 20:11:41.337 [25855]: Request (file descriptor 185): GET / HTTP/1.0
INFO      Jan 15 20:11:41.340 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 185
INFO      Jan 15 20:11:41.342 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.343 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.344 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.348 [25855]: Established connection to host "Public IP Address" using file descriptor 186.
CONNECT   Jan 15 20:11:41.350 [25855]: Connect (file descriptor 187): Public IP Address
CONNECT   Jan 15 20:11:41.351 [25855]: Request (file descriptor 187): GET / HTTP/1.0
INFO      Jan 15 20:11:41.354 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 187
INFO      Jan 15 20:11:41.355 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.356 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.358 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.362 [25855]: Established connection to host "Public IP Address" using file descriptor 188.
CONNECT   Jan 15 20:11:41.364 [25855]: Connect (file descriptor 189): Public IP Address
CONNECT   Jan 15 20:11:41.366 [25855]: Request (file descriptor 189): GET / HTTP/1.0
INFO      Jan 15 20:11:41.369 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 189
INFO      Jan 15 20:11:41.370 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.371 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.372 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.377 [25855]: Established connection to host "Public IP Address" using file descriptor 190.
CONNECT   Jan 15 20:11:41.379 [25855]: Connect (file descriptor 191): Public IP Address
CONNECT   Jan 15 20:11:41.381 [25855]: Request (file descriptor 191): GET / HTTP/1.0
INFO      Jan 15 20:11:41.384 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 191
INFO      Jan 15 20:11:41.386 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.387 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.388 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.393 [25855]: Established connection to host "Public IP Address" using file descriptor 192.
CONNECT   Jan 15 20:11:41.394 [25855]: Connect (file descriptor 193): Public IP Address
CONNECT   Jan 15 20:11:41.395 [25855]: Request (file descriptor 193): GET / HTTP/1.0
INFO      Jan 15 20:11:41.399 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 193
INFO      Jan 15 20:11:41.400 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.401 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.402 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.408 [25855]: Established connection to host "Public IP Address" using file descriptor 194.
CONNECT   Jan 15 20:11:41.410 [25855]: Connect (file descriptor 195): Public IP Address
CONNECT   Jan 15 20:11:41.411 [25855]: Request (file descriptor 195): GET / HTTP/1.0
INFO      Jan 15 20:11:41.415 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 195
INFO      Jan 15 20:11:41.416 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.417 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.419 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.423 [25855]: Established connection to host "Public IP Address" using file descriptor 196.
CONNECT   Jan 15 20:11:41.425 [25855]: Connect (file descriptor 197): Public IP Address
CONNECT   Jan 15 20:11:41.426 [25855]: Request (file descriptor 197): GET / HTTP/1.0
INFO      Jan 15 20:11:41.430 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 197
INFO      Jan 15 20:11:41.431 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.432 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.433 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.439 [25855]: Established connection to host "Public IP Address" using file descriptor 198.
CONNECT   Jan 15 20:11:41.441 [25855]: Connect (file descriptor 199): Public IP Address
CONNECT   Jan 15 20:11:41.442 [25855]: Request (file descriptor 199): GET / HTTP/1.0
INFO      Jan 15 20:11:41.446 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 199
INFO      Jan 15 20:11:41.447 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.448 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.449 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.454 [25855]: Established connection to host "Public IP Address" using file descriptor 200.``

**Comment by YJ-UP** [comment]
我使用的配置是默认的，只有一个是例外，那就是Timeout 10

**Comment by YJ-UP** [comment]
The configuration I use is the default, with one exception, Timeout 10

**Comment by YJ-UP** [comment]
```log
INFO      Jan 15 20:11:41.369 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 189
INFO      Jan 15 20:11:41.370 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.371 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.372 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.377 [25855]: Established connection to host "Public IP Address" using file descriptor 190.
CONNECT   Jan 15 20:11:41.379 [25855]: Connect (file descriptor 191): Public IP Address
CONNECT   Jan 15 20:11:41.381 [25855]: Request (file descriptor 191): GET / HTTP/1.0
INFO      Jan 15 20:11:41.384 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 191
INFO      Jan 15 20:11:41.386 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.387 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.388 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.393 [25855]: Established connection to host "Public IP Address" using file descriptor 192.
CONNECT   Jan 15 20:11:41.394 [25855]: Connect (file descriptor 193): Public IP Address
CONNECT   Jan 15 20:11:41.395 [25855]: Request (file descriptor 193): GET / HTTP/1.0
INFO      Jan 15 20:11:41.399 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 193
INFO      Jan 15 20:11:41.400 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.401 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.402 [25855]: opensock: getaddrinfo returned for Public IP Address:27890

**Comment by YJ-UP** [comment]
This is my log output
```log
`CONNECT   Jan 15 20:11:41.294 [25855]: Established connection to host "Public IP Address" using file descriptor 178.
CONNECT   Jan 15 20:11:41.295 [25855]: Connect (file descriptor 179): Public IP Address
CONNECT   Jan 15 20:11:41.297 [25855]: Request (file descriptor 179): GET / HTTP/1.0
INFO      Jan 15 20:11:41.299 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 179
INFO      Jan 15 20:11:41.301 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.302 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.303 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.307 [25855]: Established connection to host "Public IP Address" using file descriptor 180.
CONNECT   Jan 15 20:11:41.309 [25855]: Connect (file descriptor 181): Public IP Address
CONNECT   Jan 15 20:11:41.310 [25855]: Request (file descriptor 181): GET / HTTP/1.0
INFO      Jan 15 20:11:41.312 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 181
INFO      Jan 15 20:11:41.314 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.315 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.316 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.320 [25855]: Established connection to host "Public IP Address" using file descriptor 182.
CONNECT   Jan 15 20:11:41.322 [25855]: Connect (file descriptor 183): Public IP Address
CONNECT   Jan 15 20:11:41.323 [25855]: Request (file descriptor 183): GET / HTTP/1.0
INFO      Jan 15 20:11:41.326 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 183
INFO      Jan 15 20:11:41.327 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.328 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.329 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.334 [25855]: Established connection to host "Public IP Address" using file descriptor 184.
CONNECT   Jan 15 20:11:41.336 [25855]: Connect (file descriptor 185): Public IP Address
CONNECT   Jan 15 20:11:41.337 [25855]: Request (file descriptor 185): GET / HTTP/1.0
INFO      Jan 15 20:11:41.340 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 185
INFO      Jan 15 20:11:41.342 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.343 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.344 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.348 [25855]: Established connection to host "Public IP Address" using file descriptor 186.
CONNECT   Jan 15 20:11:41.350 [25855]: Connect (file descriptor 187): Public IP Address
CONNECT   Jan 15 20:11:41.351 [25855]: Request (file descriptor 187): GET / HTTP/1.0
INFO      Jan 15 20:11:41.354 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 187
INFO      Jan 15 20:11:41.355 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.356 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.358 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.362 [25855]: Established connection to host "Public IP Address" using file descriptor 188.
CONNECT   Jan 15 20:11:41.364 [25855]: Connect (file descriptor 189): Public IP Address
CONNECT   Jan 15 20:11:41.366 [25855]: Request (file descriptor 189): GET / HTTP/1.0
INFO      Jan 15 20:11:41.369 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 189
INFO      Jan 15 20:11:41.370 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.371 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.372 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.377 [25855]: Established connection to host "Public IP Address" using file descriptor 190.
CONNECT   Jan 15 20:11:41.379 [25855]: Connect (file descriptor 191): Public IP Address
CONNECT   Jan 15 20:11:41.381 [25855]: Request (file descriptor 191): GET / HTTP/1.0
INFO      Jan 15 20:11:41.384 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 191
INFO      Jan 15 20:11:41.386 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.387 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.388 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.393 [25855]: Established connection to host "Public IP Address" using file descriptor 192.
CONNECT   Jan 15 20:11:41.394 [25855]: Connect (file descriptor 193): Public IP Address
CONNECT   Jan 15 20:11:41.395 [25855]: Request (file descriptor 193): GET / HTTP/1.0
INFO      Jan 15 20:11:41.399 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 193
INFO      Jan 15 20:11:41.400 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.401 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.402 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.408 [25855]: Established connection to host "Public IP Address" using file descriptor 194.
CONNECT   Jan 15 20:11:41.410 [25855]: Connect (file descriptor 195): Public IP Address
CONNECT   Jan 15 20:11:41.411 [25855]: Request (file descriptor 195): GET / HTTP/1.0
INFO      Jan 15 20:11:41.415 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 195
INFO      Jan 15 20:11:41.416 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.417 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.419 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.423 [25855]: Established connection to host "Public IP Address" using file descriptor 196.
CONNECT   Jan 15 20:11:41.425 [25855]: Connect (file descriptor 197): Public IP Address
CONNECT   Jan 15 20:11:41.426 [25855]: Request (file descriptor 197): GET / HTTP/1.0
INFO      Jan 15 20:11:41.430 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 197
INFO      Jan 15 20:11:41.431 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.432 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.433 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.439 [25855]: Established connection to host "Public IP Address" using file descriptor 198.
CONNECT   Jan 15 20:11:41.441 [25855]: Connect (file descriptor 199): Public IP Address
CONNECT   Jan 15 20:11:41.442 [25855]: Request (file descriptor 199): GET / HTTP/1.0
INFO      Jan 15 20:11:41.446 [25855]: process_request: trans Host GET http://Public IP Address:27890/ for 199
INFO      Jan 15 20:11:41.447 [25855]: No upstream proxy for Public IP Address
INFO      Jan 15 20:11:41.448 [25855]: opensock: opening connection to Public IP Address:27890
INFO      Jan 15 20:11:41.449 [25855]: opensock: getaddrinfo returned for Public IP Address:27890
CONNECT   Jan 15 20:11:41.454 [25855]: Established connection to host "Public IP Address" using file descriptor 200.`

**Comment by YJ-UP** [comment]
Using `netstat - nap | grep: 27890` command
```log
tcp        0      0 0.0.0.0:27890           0.0.0.0:*               LISTEN      21716/tinyproxy     
tcp        0      0 172.28.45.250:36486     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36560    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36418    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36588    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36440    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36574    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36510     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36532    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36456     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36552    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36444    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36604    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36442     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36458     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36482     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36592     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36430     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36492     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36490     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36438     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36510    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36602     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36550    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36520    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36466     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36484     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36408    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36508     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36540     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36564    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36562    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36460     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36446    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:36562     Public IP Address:27890    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36492    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36464    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36412    TIME_WAIT   -                   
tcp        0      0 172.28.45.250:27890     Public IP Address:36476    TIME_WAIT   -

**Comment by YJ-UP** [comment]
I only changed two configuration items, `Timeout 10` and `Port 27890`

**Comment by YJ-UP** [comment]
And my machine information
```l
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

**Comment by rofl0r** [comment]
please describe 

- what you do
- what you expect to happen
- what instead happens

**Comment by YJ-UP** [comment]
Let's say my public proxy address is 8.8.8.8:27890 and I request this address. Tinyproxy will loop the proxy, but I want TinyProxy to automatically recognize malicious requests

**Comment by YJ-UP** [comment]
I'm sorry, maybe my description is not very accurate, because my English is not very good, but I will try my best to describe

**Comment by YJ-UP** [comment]
`curl 8.8.8.8:27890` to my proxy server, tinyProxy will loop the proxy. I hope TinyProxy will automatically recognize the malicious request and automatically close the malicious connection

**Comment by YJ-UP** [comment]
Tinyproxy logs are generated after commands are sent:  
```lCONNECT   Jan 16 02:20:25.465 [28094]: Connect (file descriptor 195): 8.8.8.8
CONNECT   Jan 16 02:20:25.466 [28094]: Request (file descriptor 195): GET / HTTP/1.0
INFO      Jan 16 02:20:25.470 [28094]: process_request: trans Host GET http://8.8.8.8:27890/ for 195
INFO      Jan 16 02:20:25.471 [28094]: No upstream proxy for 8.8.8.8
INFO      Jan 16 02:20:25.472 [28094]: opensock: opening connection to 8.8.8.8:27890
INFO      Jan 16 02:20:25.473 [28094]: opensock: getaddrinfo returned for 8.8.8.8:27890
CONNECT   Jan 16 02:20:25.478 [28094]: Established connection to host "8.8.8.8" using file descriptor 196.
CONNECT   Jan 16 02:20:25.480 [28094]: Connect (file descriptor 197): 8.8.8.8
CONNECT   Jan 16 02:20:25.481 [28094]: Request (file descriptor 197): GET / HTTP/1.0
INFO      Jan 16 02:20:25.484 [28094]: process_request: trans Host GET http://8.8.8.8:27890/ for 197
INFO      Jan 16 02:20:25.486 [28094]: No upstream proxy for 8.8.8.8
INFO      Jan 16 02:20:25.487 [28094]: opensock: opening connection to 8.8.8.8:27890
INFO      Jan 16 02:20:25.488 [28094]: opensock: getaddrinfo returned for 8.8.8.8:27890
CONNECT   Jan 16 02:20:25.493 [28094]: Established connection to host "8.8.8.8" using file descriptor 198.
CONNECT   Jan 16 02:20:25.494 [28094]: Connect (file descriptor 199): 8.8.8.8
CONNECT   Jan 16 02:20:25.496 [28094]: Request (file descriptor 199): GET / HTTP/1.0
INFO      Jan 16 02:20:25.499 [28094]: process_request: trans Host GET http://8.8.8.8:27890/ for 199
INFO      Jan 16 02:20:25.500 [28094]: No upstream proxy for 8.8.8.8
INFO      Jan 16 02:20:25.502 [28094]: opensock: opening connection to 8.8.8.8:27890
INFO      Jan 16 02:20:25.503 [28094]: opensock: getaddrinfo returned for 8.8.8.8:27890
CONNECT   Jan 16 02:20:25.508 [28094]: Established connection to host "8.8.8.8" using file descriptor 200.
WARNING   Jan 16 02:20:25.509 [28094]: Maximum number of connections reached. Refusing new connections.

**Comment by rofl0r** [comment]
doesn't happen for me:
```
~/tinyproxy[master]$ cat tinyproxy-local.conf 
Port 1080
Listen 127.0.0.1
Timeout 600
LogLevel Connect
MaxClients 500
Allow 127.0.0.1
ViaProxyName "tinyproxy"
DisableViaHeader Yes
```

terminal 1:
```
~/tinyproxy[master]$ src/tinyproxy -d -c tinyproxy-local.conf 
DEBUG     Jan 16 18:05:05.899 [2823]: sending stored logs
NOTICE    Jan 16 18:05:05.899 [2823]: Initializing tinyproxy ...
NOTICE    Jan 16 18:05:05.899 [2823]: Reloading config file
NOTICE    Jan 16 18:05:05.899 [2823]: Reloading config file finished
DEBUG     Jan 16 18:05:05.899 [2823]: done sending stored logs
```

terminal 2:
```
~ $ curl localhost:1080
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head><title>400 Bad Request</title></head>
<body>
<h1>Bad Request</h1>
<p>You tried to connect to the machine the proxy is running on</p>
<hr />
<p><em>Generated by tinyproxy version 1.11.0-rc1-36-git-7168a42.</em></p>
</body>
</html>
```

terminal 1:
```
CONNECT   Jan 16 18:05:13.715 [2823]: Connect (file descriptor 4): 127.0.0.1
CONNECT   Jan 16 18:05:13.715 [2823]: Request (file descriptor 4): GET / HTTP/1.1
CONNECT   Jan 16 18:05:13.715 [2823]: Established connection to host "localhost" using file descriptor 5.
CONNECT   Jan 16 18:05:13.715 [2823]: Connect (file descriptor 6): 127.0.0.1
CONNECT   Jan 16 18:05:13.715 [2823]: Prevented endless loop (file descriptor 6): 127.0.0.1
^CNOTICE    Jan 16 18:05:50.559 [2823]: Shutting down.
```

**Comment by YJ-UP** [comment]
No, I'm sending a request to a public IP address, and the request will loop through the proxy

**Comment by YJ-UP** [comment]
`8.8.8.8`is my public IP address
Using `curl localhost:27890` will be recognized as a malicious request by TinyProxy, but it does not seem to recognize the public network

**Comment by darylteo** [comment]
Observing a behaviour with a couple of docker builds that could be explained by this bug.

Basically if tinyproxy receives a HTTP request rather than a proxy request it basically hangs completely and never responds to anything else after.

With `ajoergensen/tinyproxy` and `vimagick/tinyproxy`

```
➜ curl --proxy 54.79.204.47:8888 -I http://www.example.com
HTTP/1.0 200 OK
Content-Encoding: gzip
Accept-Ranges: bytes
Age: 548322
Cache-Control: max-age=604800
Content-Type: text/html; charset=UTF-8
Date: Sat, 05 Mar 2022 11:13:14 GMT
Etag: "3147526947"
Expires: Sat, 12 Mar 2022 11:13:14 GMT
Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
Server: ECS (sab/571B)
X-Cache: HIT
Content-Length: 648

➜  curl --proxy 54.79.204.47:8888 -I http://www.example.com
HTTP/1.0 200 OK
Content-Encoding: gzip
Accept-Ranges: bytes
Age: 549157
Cache-Control: max-age=604800
Content-Type: text/html; charset=UTF-8
Date: Sat, 05 Mar 2022 11:13:14 GMT
Etag: "3147526947"
Expires: Sat, 12 Mar 2022 11:13:14 GMT
Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
Server: ECS (sab/5783)
X-Cache: HIT
Content-Length: 648

➜  curl 54.79.204.47:8888 -I
^C
➜  curl --proxy 54.79.204.47:8888 -I http://www.example.com
^[ # hangs here

```

**Comment by rofl0r** [comment]
i'm unable to reproduce this. just tried on a cloud host with 4 different public ips, same config as above just changed listen to 0.0.0.0 and removed allow directive. the loop detection works correctly with both ubuntu and musl-based rootfs using all 4 public ips.

if you want to have this fixed, start with posting your configs so i can eventually reproduce this.

**Comment by darylteo** [comment]
@rofl0r I've personally worked around this by adding Basic Auth so that unauthorized traffic doesn't hit the loop. :)

Re: configs - I'm using the Docker Images directly. It's possible that this has been fixed already in master. So I can only direct you to these configs that I've found

https://github.com/ajoergensen/docker-tinyproxy/blob/master/root/etc/cont-init.d/90_tinyproxy.sh

https://github.com/vimagick/dockerfiles/blob/master/tinyproxy/data/tinyproxy.conf

Re: fix - i would never demand provided free be fixed :) much appreciation for your work and effort. My comment is merely to provide additional data points that could help reveal an issue.

Thanks for your time! Hope this is useful. 

Daryl

**Comment by rofl0r** [comment]
at least the ajoergensen one is totally outdated - see https://github.com/ajoergensen/docker-tinyproxy/issues/2
the second one seems to be more up2date. which one do you actually use? can you observe the described behaviour on the 2nd one too ?

> Re: fix - i would never demand that something provided free be fixed :) 

that's laudable, but in this case this is a critical issue which basically makes it impossible to host an open public proxy (if this is really not fixed yet)

**Comment by gingerbeardman** [comment]
ajoergensen/tinyproxy is now running tinyproxy 1.11.0

**Comment by rofl0r** [comment]
@darylteo ^  can you try whether using the updated docker fixes this ?

**Comment by darylteo** [comment]
Apologies for the delay I'm not on github very often.

The updated image from ajoergensen seems to have fixed the issue. Thank you very much @rofl0r! 💪

https://i.imgur.com/aNNjc9o.mp4

**Comment by rofl0r** [comment]
> The updated image from ajoergensen seems to have fixed the issue. Thank you very much @rofl0r! 💪

thanks for feedback, until further new issue is opened i will assume that OP was actually running 1.10 and the issue is resolved.
