### ISSUE TITLE
HUP signal doesn't work as expected when tinyproxy is started in foreground

### ISSUE THREAD

**Issue by crspl** [tinyproxy/tinyproxy#416]
Version: 1.11.0

Issue: when started in foreground (-d flag) and HUP signal is received then tinyproxy exits to system instead of reloading configuration

Steps to reproduce:
- start tinyproxy with -d flag
- in separate window find out its PID
- run `kill -HUP <PID>`
- effect: process exits to system with message "Hangup" on stdout

![2022-01-25_13-10](https://user-images.githubusercontent.com/1543827/150977039-cce53b34-1e84-4d22-9511-dbd64d53f24c.png)

**Comment by rofl0r** [comment]
works as intended 8ba0ac4e8662ddc9c109229594f8a8ff0471b0df 8c86e8b3ae6ffcec693a06a4ea7d03274f3e5687
