### ISSUE TITLE
Passing logfile on command line + log to stdout/stderr.

### ISSUE THREAD

**Issue by spectras** [tinyproxy/tinyproxy#43]
Probably could be part of a series aiming at making tinyproxy systemd-friendly.

It would be great to have the two somewhat related following features:
1) Specify the logfile on the command line. It should probably override that of the config file in that case (as a sidenote, allowing to specify the pidfile on the command line would be a good idea as well).
2) Allow logging to stdout or stderr. One possibility is to support `-` as a logfile name. The other would be to lift some of the checks done while creating the logfile, so `/dev/stdout` works. Right now, passing `/dev/stdout` as logfile fails with this error:
    ```
     tinyproxy: The file /dev/stdout has been changed before it could be opened
    ```

**Comment by eadz** [comment]
Useful not just for systemd, but for docker as well.

**Comment by Nakilon** [comment]
I don't see how linked issues help here. I do the `apk add tinyproxy`, then `tinyproxy` and see:
```
WARNING: logging deactivated (can't log to stdout when daemonized)
````

**Comment by rofl0r** [comment]
tinyproxy can now log to stdout/stderr when running in foreground mode. you can then redirect the output to whatever file you'd like.

**Comment by luckypoem** [comment]
just uncomment the line:  #LogFile "/usr/local/var/log/tinyproxy/tinyproxy.log" to fix the issue: "WARNING: logging deactivated (can't log to stdout when daemonized)"

**Comment by rofl0r** [comment]
@luckypoem just use `tinyproxy -d -c myconfig.conf`

**Comment by luckypoem** [comment]
@rofl0r 

hi,

i installed stunnel and tinyproxy on my vps.

root@p1601860745:~# ps aux|grep stunnel
root     20021  0.0  0.4 542208  4736 ?        Ssl  Jul20   0:01 stunnel /etc/stunnel/stunnel-backend-is-tinyproxy.conf
root       944  0.0  0.0   6212   888 pts/1    S+   11:50   0:00 grep stunnel
root@p1601860745:~# ps aux|grep tinyproxy
root       946  0.0  0.0   6212   884 pts/1    S+   11:51   0:00 grep tinyproxy
nobody   19961  0.0  0.2 267016  2160 ?        S    Jul20   0:00 /usr/local/bin/tinyproxy -d -c /usr/local/etc/tinyproxy/tinyproxy.conf
root@p1601860745:~# cat /etc/stunnel/stunnel-backend-is-tinyproxy.conf

client = no
cert = /etc/stunnel/public.crt
key = /etc/stunnel/private.key

[tinyproxy]
accept  = 4443
connect = 127.0.0.1:28888
root@p1601860745:~# cat /usr/local/etc/tinyproxy/tinyproxy.conf
User nobody
Group nobody

Port 28888

Timeout 600

DefaultErrorFile "/usr/local/share/tinyproxy/default.html"

StatFile "/usr/local/share/tinyproxy/stats.html"

#LogFile "/usr/local/var/log/tinyproxy/tinyproxy.log"

#Syslog On

LogLevel Info

MaxClients 100

Allow 127.0.0.1
#Allow ::1

# BasicAuth: HTTP "Basic Authentication" for accessing the proxy.
# If there are any entries specified, access is only granted for authenticated
# users.
#BasicAuth user password

ViaProxyName "tinyproxy"
root@p1601860745:~#

on my mac:
cd /usr/local/etc/stunnel/
yudeMacBook-Air:stunnel brite$ ls
private.key
public.crt
stunnel-backend-is-tinyproxy-on-vps.conf
yudeMacBook-Air:stunnel brite$ cat stunnel-backend-is-tinyproxy-on-vps.conf
client = yes
cert = public.crt 
key = private.key

[tinyproxy]
accept  = 127.0.0.1:7779 
connect = vps-public-ip:4443
yudeMacBook-Air:stunnel brite$

then,i set the browser's http proxy server to be 127.0.0.1 , port to be 7779 ,but i just can't cross GFW(great firewall of china) to visit the blocked websites.

why?

**Comment by rofl0r** [comment]
@luckypoem you dont need stunnel on your client (mac). and you need to configure your browser to use a **https** proxy if you run tinyproxy behind an stunnel.

also i'm afraid that this question is entirely unrelated to this issue, so please open a new one if you have further questions.
