### ISSUE TITLE
ReversePath not being used

### ISSUE THREAD

**Issue by gerald-brandt** [tinyproxy/tinyproxy#434]
## Tinyproxy version
1.11.0 stable.

## Issue
This is my conf file:
```
Port 9999

MaxClients 100
MinSpareServers 2
MaxSpareServers 5
StartServers 2

Logfile "/tmp/tinyproxy.log"

#ConnectPort 5803


ReversePath "/" "http://localhost:10000/"

ReversePath "/websockify" "ws://localhost:5801/websockify"

ReversePath "/fileserver_6/" "http://localhost:5801/"

```

http://<IP>:9999/websockify does not go to http://localhost:5801/websockify, instead it goes to http://localhost:10000/websockify

Am I doing something wrong?

Gerald

**Comment by gerald-brandt** [comment]
Okay, so it works if I add a trailing slash. The conf file is now:

```
Port 9999

MaxClients 100
MinSpareServers 2
MaxSpareServers 5
StartServers 2

Logfile "/tmp/tinyproxy.log"

#ConnectPort 5803


ReversePath "/" "http://localhost:10000/"


ReversePath "/fileserver_6/" "http://localhost:5801/"

ReversePath "/websockify/" "ws://localhost:5801/websockify"

But this is the output from tinyproxy, and that final URL looks way wrong.

```
CONNECT   Apr 29 15:04:47.363 [2458738]: Connect (file descriptor 6): 10.20.30.33
CONNECT   Apr 29 15:04:47.391 [2458738]: Request (file descriptor 6): GET /websockify/ HTTP/1.1
CONNECT   Apr 29 15:04:47.416 [2458738]: Rewriting URL: /websockify/ -> ws://localhost:5801/websockify
INFO      Apr 29 15:04:47.441 [2458738]: process_request: trans Host GET http://kvm4:9999ws://localhost:5801/websockify for 6
INFO      Apr 29 15:04:47.466 [2458738]: No upstream proxy for kvm4
INFO      Apr 29 15:04:47.491 [2458738]: opensock: opening connection to kvm4:9999
INFO      Apr 29 15:04:47.516 [2458738]: opensock: getaddrinfo returned for kvm4:9999
CONNECT   Apr 29 15:04:47.541 [2458738]: Established connection to host "kvm4" using file descriptor 7.
CONNECT   Apr 29 15:04:47.542 [2458738]: Connect (file descriptor 8): 127.0.0.1
CONNECT   Apr 29 15:04:47.591 [2458738]: Prevented endless loop (file descriptor 8): 127.0.0.1
INFO      Apr 29 15:04:47.617 [2458738]: Read request entity of 527 bytes
INFO      Apr 29 15:04:47.642 [2458738]: Closed connection between local client (fd:6) and remote client (fd:7)
NOTICE    Apr 29 15:06:34.030 [2458738]: Shutting down.
INFO      Apr 29 15:06:34.056 [2458738]: trying to bring down 2 threads...

```

**Comment by rofl0r** [comment]
the issue with the trailing slash was fixed in 
2529597ea0201c147b4bb5fb713040b117368b50

that's why i recommend everywhere to use master, not release.
