### ISSUE TITLE
NoUpstream Proxy for www.website.com

### ISSUE THREAD

**Issue by Beta66** [tinyproxy/tinyproxy#436]
Version is v11

HI guys - everything seems to work fine but I keep getting no up stream proxy for imagefiles.com - from our server at OVH to the proxy server everything is being handled correctly. Not seeing any degradation or errors other than "no upstream proxy"
see below: 

```
CONNECT   May 05 13:52:49 [9442]: Established connection to host "imagefiles.com" using file descriptor 8.
INFO      May 05 13:52:52 [9443]: Closed connection between local client (fd:7) and remote client (fd:8)
CONNECT   May 05 13:52:59 [9443]: Connect (file descriptor 7): ovh-servers.com [1.1.1.1] at [2.2.2.2]
CONNECT   May 05 13:52:59 [9443]: Request (file descriptor 7): GET http://imagefiles.com:8888/32323/imgur.jpg HTTP/1.1
INFO      May 05 13:52:59 [9443]: No upstream proxy for imagefiles.com
```
is this the correct behavior?

**Comment by rofl0r** [comment]
depends on your config. loglevel info is a high verbosity level, reduce it to connect if you don't want to see the message. it just means that no upstream was configured.
