### ISSUE TITLE
Question: Will TinyProxy handle internal redirects?

### ISSUE THREAD

**Issue by Beta66** [tinyproxy/tinyproxy#439]
TinyProxy  v1.11.0 stable.

Will tiny proxy follow internal 301 redirects

client -> tinyproxyserver -> host -> sends a 301 to another host -> back-to-tiny-proxyserver -> back to client
 
We have an IPSEC Site2Site VPN to a server where i want to install tinyproxy and that way I dont have to add 10 tunnels to the VPN, i could just use tinyproxy as as the only host in the VPN but our php will send back 301's redirecting to the server where the asset is.

**Comment by rofl0r** [comment]
> client -> tinyproxyserver -> host -> sends a 301 to another host -> back-to-tiny-proxyserver -> back to client

without having tested this, i'd say the normal behaviour of tinyproxy is to relay upstream response back to the client, so this should work. did you test already ?
