### ISSUE TITLE
SIG-USR1 should dump stats in simple plain text

### ISSUE THREAD

**Issue by tb3088** [tinyproxy/tinyproxy#44]
This signal is a pretty common mechanism to dump simple status information.
Construct a simple 1-liner like:
open:num requests:num bad:num denied:num refused:num 
and perhaps defined by 'StatusLine' keyword which would be parsed for known tokens.

Would be output to LogFile or Syslog as appropriate and STDOUT if running attached to a terminal.

**Comment by rofl0r** [comment]
SIGUSR1 has now been introduced for a different purpose.
