### ISSUE TITLE
tinyproxy does not forward SOCKS5h to upstream proxy

### ISSUE THREAD

**Issue by crispy-duckling** [tinyproxy/tinyproxy#442]
## Tinyproxy version
tinyproxy 1.11.0-rc1-63-git-8b373f8 (up-to-date master)

## Issue
I would like to provide SOCKS5h support for clients connecting to tinyproxy, overall making it a domain-filtering SOCKS proxy with help of an upstream server. 

My idea was to forward SOCKS requests to an `upstream` SOCKS proxy simply established by SSH dynamic port-forwarding.

### Test case

`/usr/local/etc/tinyproxy/tinyproxy.conf`:
```
Filter "/etc/tinyproxy/filter"
FilterDefaultDeny Yes
```

`/usr/local/etc/tinyproxy/filter`:
```
example\.net$
```

```sh
/usr/local/bin/tinyproxy -d -c '/usr/local/etc/tinyproxy/tinyproxy.conf'
```

#### 1. HTTPS-only - works
```sh
curl --proxy http://127.0.0.1:8888 https://example.net
```

#### 2. SOCKS-only - works
```sh
ssh -f -N -D 0.0.0.0:1080 localhost
```
(assumes installed SSH client+server packages `ssh`,`openssh-server`)
```sh
curl --proxy socks5h://127.0.0.1:1080 https://example.net
```

#### 3. Attempt to forward SOCKS request by tinyproxy - does *not* work
```
Upstream socks5 127.0.0.1:1080 "example.net"
```

```sh
curl --proxy socks5h://127.0.0.1:8888 https://example.net
```
(idles infinitely)

> CONNECT   [1170]: Connect (file descriptor 7): localhost [127.0.0.1]

Also tried inserting `Upstream none "127.0.0.1/8"` to no avail.

----

Is there something I am doing wrong? Or is tinyproxy not capable of processing SOCKS requests? 

TIA

**Comment by rofl0r** [comment]
> Or is tinyproxy not capable of processing SOCKS requests?

correct. tinyproxy is a http proxy, so you can only access it as such.
