### ISSUE TITLE
Why tinyproxy drop Host header ?

### ISSUE THREAD

**Issue by mello7tre** [tinyproxy/tinyproxy#443]
After going mad getting 404 using curl with custom Host header, `curl -H "Host: serverhost`, i had a look at the code:
`reqs.c`
```
static int
process_client_headers (struct conn_s *connptr, orderedmap hashofheaders)
{
        static const char *skipheaders[] = {
                "host",
                "keep-alive",
                "proxy-connection",
                "te",
                "trailers",
                "upgrade"
        };

```
and later
```
        /*
         * Delete the headers listed in the skipheaders list
         */
        for (i = 0; i != (sizeof (skipheaders) / sizeof (char *)); i++) {
                orderedmap_remove (hashofheaders, skipheaders[i]);
        }
```

but why include the header Host too ?

(can explain #296)

Regards, Alberto.

**Comment by rofl0r** [comment]
i assume it does this because it fills in its own Host header using the destination (either because due to proxying the destination Host thing might change, or in order to prevent having multiple host headers, from a time before a hashmap was used for the headers).
this is a quite cornercase usage (using curl to fake a host header) and changing it might break some mainstream usecases, so it is difficult to decide what to do in this case.
if we removed the host header from the skiplist, it would require elaborate testing of all imaginable usecases to make sure nothing breaks. i guess you could just remove it in your local build and test it for a while, then report back.

**Comment by rofl0r** [comment]
> And classic Http 1.0/1.1 protocol work that way.

actually only http 1.1 makes the Host header obligatory

> Address host get resolved, you connect to ip and send header Host to specify the server hostname you want to process the request.

i'm aware how the Host header works, but doing curl hackery is only needed if the http server is addressed by raw ip instead of hostname, e.g. `curl http://1.1.1.1` vs `curl example.com` - the latter causes curl to put `Host: example.com` into the headers, and tinyproxy does the same.

**Comment by mello7tre** [comment]
So you should agree that keeping and using the Host header, if present, is simply following the _standard_ and it's not dangerous in any way.
Even because it's not documented anywhere that tinyproxy remove and override the Host header.

**Comment by rofl0r** [comment]
> as https://github.com/tinyproxy/tinyproxy/issues/296 i am not the only one that expect header Host, if present, to be taken in account but...

right, 2 people noticing the same issue in 21 years since this was commited.

anyway, let me know after few months of usage whether the change had some unexpected side effects.

**Comment by mello7tre** [comment]
Sure.
Currently i have changed only `handle_connection` to check for header Host and if successful pass it to `establish_http_connection` to use it in place of `request->host` but only for Ipv4 direct connection, no upstream proxy.
In all other cases current `request->host` is used.
(no need at all to remove Host from blacklisted headers, as they are processed later after `establish_http_connection`)

As i am using debian i changed the sources of `tinyproxy (1.11.1-1~bpo11+1)` and rebuilded the package.
All test made during rebuild where successful.

If i had time i will pull the code from git repo maybe code it better and put it under an option flag.

**Comment by rofl0r** [comment]
> Currently i have changed

could you paste a diff of that ?

> and put it under an option flag.

i'd really like to avoid adding yet more options, but rather just always do the right thing.

**Comment by mello7tre** [comment]
I will paste it as soon as i finish some fixes/tests, regarding the case in which the header Host include a port too, to avoid to double include it...

**Comment by mello7tre** [comment]
[Here](https://github.com/tinyproxy/tinyproxy/files/8928476/diff.txt)
have mercy for the code, i do not write a line of C from years....

**Comment by rofl0r** [comment]
why the whole dance around the port ?

**Comment by mello7tre** [comment]
I didn't wont to duplicate the `write_message` code.
But probably this is simpler and should work too (not tested).
No one should put a port only in Host header.
You had in mind this ?

````diff
diff --git a/src/reqs.c b/src/reqs.c
index 50aaec6..3c3967d 100644
--- a/src/reqs.c
+++ b/src/reqs.c
@@ -253,16 +253,19 @@ ERROR_EXIT:
  * Create a connection for HTTP connections.
  */
 static int
-establish_http_connection (struct conn_s *connptr, struct request_s *request)
+establish_http_connection (struct conn_s *connptr, struct request_s *request, char *header_host)
 {
         char portbuff[7];
         char dst[sizeof(struct in6_addr)];
 
         /* Build a port string if it's not a standard port */
-        if (request->port != HTTP_PORT && request->port != HTTP_PORT_SSL)
+        if (request->port != HTTP_PORT && request->port != HTTP_PORT_SSL) {
                 snprintf (portbuff, 7, ":%u", request->port);
-        else
+		/* If request include a port never use header Host */
+	        header_host = NULL;
+        } else {
                 portbuff[0] = '\0';
+        }
 
         if (inet_pton(AF_INET6, request->host, dst) > 0) {
                 /* host is an IPv6 address literal, so surround it with
@@ -288,6 +291,16 @@ establish_http_connection (struct conn_s *connptr, struct request_s *request)
                                                connptr->protocol.minor,
                                       request->host, portbuff,
                                       connptr->upstream_proxy->ua.authstr);
+        } else if (header_host) {
+	        /* If exist header Host send it */
+                return write_message (connptr->server_fd,
+                                      "%s %s HTTP/1.%u\r\n"
+                                      "Host: %s\r\n"
+                                      "Connection: close\r\n",
+                                      request->method, request->path,
+                                      connptr->protocol.major != 1 ? 0 :
+                                               connptr->protocol.minor,
+                                      header_host);
         } else {
                 return write_message (connptr->server_fd,
                                       "%s %s HTTP/1.%u\r\n"
@@ -296,7 +309,7 @@ establish_http_connection (struct conn_s *connptr, struct request_s *request)
                                       request->method, request->path,
                                       connptr->protocol.major != 1 ? 0 :
                                                connptr->protocol.minor,
-                                      request->host, portbuff);
+                                      header_host, portbuff);
         }
 }
```

**Comment by rofl0r** [comment]
i don't understand really what you're doing here, afaict it would be suffcient to just check whether "host" is already in hashofheaders, and if not, add it. plus remove the entry from the skiplist.

**Comment by mello7tre** [comment]
Unfortunately it's not so easy.
In `establish_http_connection` you send the Host header builded from the one in the URI.
```
                return write_message (connptr->server_fd,                                
                                      "%s %s HTTP/1.%u\r\n"                              
                                      "Host: %s%s\r\n"                                   
                                      "Connection: close\r\n",                           
                                      request->method, request->path,                    
                                      connptr->protocol.major != 1 ? 0 :                 
                                               connptr->protocol.minor,                  
                                      header_host, portbuff);
```
Any other Host header sent after are simply ignored (tested this).

Regarding the _dance around the port_:
let's say i want to connect to `example_host:8888` with firefox.
The browser send the Host header with content `example_host:8888`.
So if i do not remove the port part i will end up, with today code, with an Host header as:
`example_host:8888:8888`.

**Comment by rofl0r** [comment]
ok, i see now. what i would do instead is add a function `char* get_host()` that returns either (if available) hashofheaders["host"] with port stripped, or request->host, and use its result in this format string. here some care must be taken about how the returned string is allocated and after the use accordingly freed.

**Comment by mello7tre** [comment]
Ok, only problem is that in `establish_http_connection` we do not have `hashofheaders`.
We need to pass it from `handle_connection` and pass a NULL value in the others function where is called `establish_http_connection` too, as example `connect_to_upstream`. 
So any way we need an if condition to check if `hashofheaders` is not NULL.

(Unless we want to pass over `hashofheaders` in other functions too, to always call `establish_http_connection` with `hashofheaders` value.)

If you want me to open a PR about this, please tell me which _variant_ you prefer.

**Comment by rofl0r** [comment]
meh, i guess in that case it's best to just always put the Host header into request->host if it was in hashofheaders, after the client headers are processed.

> If you want me to open a PR about this

you can make a PR if you like, yeah, but it will still require some testing before it can go into master
