### ISSUE TITLE
Could not create file /var/log/tinyproxy/tinyproxy.log: Permission denied

### ISSUE THREAD

**Issue by Proofer** [tinyproxy/tinyproxy#444]
Version 1.11.0 installed yesterday from ubuntu package
Yesterday:
```
sudo tinyproxy -d
tinyproxy: Could not create listening sockets.
```
--although ss showed no other process using 8888.
I saw another Issues report of this problem that was fixed by changing tinyproxy's Port. But it was time to leave it for the night.

This morning, after rebooting, instead of the previous error, I got:
```
sudo tinyproxy -d
tinyproxy: Could not create file /var/log/tinyproxy/tinyproxy.log: Permission denied
^C
```

.conf :
User tinyproxy
Group tinyproxy
Port 8888
Listen 192.168.50.212  # address of one of this device's multiple ethernet interfaces
Bind 10.4.0.1      # address of virtual interface at other end of WireGuard tunnel
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
PidFile "/run/tinyproxy/tinyproxy.pid"
MaxClients 2
Allow 127.0.0.1
Allow 192.168.0.0/16
ViaProxyName "tinyproxy"

**Comment by rofl0r** [comment]
don't use sudo. and change your config to use neither pidfile, nor logfile, nor user, nor group, so it runs as your own restricted user.

**Comment by Proofer** [comment]
I had to wait **17 minutes** after posting my issue to get a response!

(But seriously: thanks!)
