### ISSUE TITLE
Use Tinyproxy like a "proxy website" on OpenWrt

### ISSUE THREAD

**Issue by GlassGruber** [tinyproxy/tinyproxy#447]
Hei there! 
Is it possible to use tinyproxy as one of those proxy website you can find online? (like dunno `proxysite.com` or whatever pops up with a search for _"proxy website"_ ).  
BTW what is the proper technical term for this? Proxy website sounds a bit naive?)

I'd like to allow people connected to my access point to do something like `<router.ip.address>:<port>/https://whatever.net/some-page#anchor` and see the page requested.
This should work without configuring browsers to use any specific proxy configs.

I'm on a OpenWrt router, unfortunately I see the package available is [v1.10](https://openwrt.org/packages/pkgdata/tinyproxy).

**Comment by rofl0r** [comment]
> BTW what is the proper technical term for this? Proxy website sounds a bit naive?

nothing specific crosses my mind...

> I'd like to allow people connected to my access point to do something like <router.ip.address>:<port>/https://whatever.net/some-page#anchor and see the page requested.

this is not a standard functionality built into tinyproxy, the closest to it is "reverse proxy" functionality, however it works with a predefined set of webpages/domains.

if i personally wanted to achieve something like this, i'd probably write a small [pyhttpd](https://github.com/rofl0r/pyhttpd) app that parses the url, fetches the initial html page and rewrites all urls to add the router.ip.address part to all hyperlinks and resources in there.

> I'm on a OpenWrt router, unfortunately I see the package available is [v1.10](https://openwrt.org/packages/pkgdata/tinyproxy).

you could contact openwrt maintainers via github issues and notify them that they are 2 releases behind, so anyone using openwrt can enjoy a newer and less buggy tinyproxy version.

**Comment by GlassGruber** [comment]
> this is not a standard functionality built into tinyproxy, the closest to it is "reverse proxy" functionality, however it works with a predefined set of webpages/domains.

Yea I started with that but got back some 400 bad request errors when doing https, I guess part of the problems are caused by the old version I have.

> if i personally wanted to achieve something like this, i'd probably write a small [pyhttpd](https://github.com/rofl0r/pyhttpd) app that parses the url, fetches the initial html page and rewrites all urls to add the router.ip.address part to all hyperlinks and resources in there.

Very interesting thank you this is something totally doable and your pyhttpd  project looks pretty cool too!  
One weird thing though: why python 2?  
Is python 2 still that common now even after EOL?

Anyway thank you for your answer and your time and for your projects! 
This can be closed if you want. Hopefully I'll give an update on how I solved this and share some code!

**Comment by rofl0r** [comment]
> Yea I started with that but got back some 400 bad request errors when doing https, I guess part of the problems are caused by the old version I have.

tinyproxy doesnt natively talk https, you would need to put an stunnel (or similar solution) in front of it to serve https requests.

> One weird thing though: why python 2?
> Is python 2 still that common now even after EOL?

i'm pretty fond of python2 as it is stable, and allows to write code that will keep on working regardless of the whims of the python maintainers, unlike python3.
i've written an [essay](https://sabotage-linux.neocities.org/blog/8/) about this topic, in case you're interested in details.
