### ISSUE TITLE
Best way to pickup conf changes and/or restart?

### ISSUE THREAD

**Issue by gingerbeardman** [tinyproxy/tinyproxy#453]
## Tinyproxy version
- 1.11.0 (docker)

## Issue
My local IP changes frequently, and I need to edit the Allow addresses in tinyproxy.

Currently I am doing this process:
1. login over SSH2. 
2. edit tinyproxy.conf
3. reboot server

Note: `tinyproxy restart` does not pick up my configuration changes.

Questions
1. what is the best way to pick up configuration changes?
2. what is the best way to restart tinyproxy?
3. is there a better way to solve my problem?

Thanks!

**Comment by rofl0r** [comment]
a config reload can be  triggered by sending SIGUSR1 to the main tinyproxy process,
however this doesn't affect listen or bind directives, as the listening sockets are created only on program start. it should work fine for allow directives though.

the best way to restart tinyproxy is using the distro's service supervisor.

**Comment by gingerbeardman** [comment]
I'll try it and report back. Thanks!

**Comment by gingerbeardman** [comment]
I moved to using a docker which lets me easily do `docker restart tinyproxy` on the container.

**Comment by gingerbeardman** [comment]
I eventually read in another issue that you can send SIGUSR1 the tinyproxy process, so now I do `killall -SIGUSR1 tinyproxy`
