### ISSUE TITLE
CentOS 7.9.2009 support

### ISSUE THREAD

**Issue by Pinnokkio** [tinyproxy/tinyproxy#454]
# IMPORTANT NOTICE

Before filing an issue here PLEASE keep in mind that **tinyproxy 1.10.0 and older are no longer supported**.
Do not report issues with 1.10.0 or older, first try latest release 1.11.0, or even better, git master, and see whether the issue is already fixed.

## Tinyproxy version
1.8.3-2.el7

## Issue
**I know this version is not supported anymore, but I have some questions:**

I was trying to setup tinyproxy on `CentOS Linux 7.9.2009`, tried to add BasicAuth but it failed to starte every time because of `Syntax error on line 219`. When removing the whole line "BasicAuth username password", it works as expected. The latest version I'm able to install via `yum -y install tinyproxy` is `1.8.3-2.el7`.

My questions are:

1. Will there be a newer version that supports BasicAuth for `CentOS 7.9` (which was release on november 12th, 2020)? If yes, when?
2. When switching server to `Ubuntu 22.04`, is it possible to use the latest version of tinyproxy  (which includes BasicAuth)?

I really appreciate your support, thank you.

**Comment by rofl0r** [comment]
> Will there be a newer version that supports BasicAuth for CentOS 7.9

it already is : you need to compile a newer version from source

> When switching server to Ubuntu 22.04, is it possible to use the latest version of tinyproxy (which includes BasicAuth)?

regardless of version provided by distros, it's always possible to use latest version, by compiling it from source. read instructions how to do so in README.

if you really don't want to compile from source, you have to nag your distro's maintainers to update their packages.
