### ISSUE TITLE
Nested TinyProxy not working

### ISSUE THREAD

**Issue by uchiha-pain** [tinyproxy/tinyproxy#455]
Hi, I have machine in public network and I have installed tinyproxy on that machine. The config is as follows for that tinyproxy
```
Listen 127.0.0.1
Port 19000
Allow my-private-address
```

this config is working fine for the machine (private-machine-1) in private network and I am able to access the internet from private network with the following tunnel.
```
Host serv-gate
        User user
        Hostname ip-addr
        Port 22
        LocalForward 19000 127.0.0.1:19000
```

Now, I have further installed tinyproxy in this machine (private-machine-1) and created another machine (private-machine-2) in another private network to get internet connection. The config is
```
Listen 192.168.*.*
Port 19000
Allow my-private-address
```
The ssh tunnel config is as follows for the private-machine-2
```
Host serv-gate
        User user
        Hostname ip-of-private-machine-1
        Port 22
        LocalForward 19000 ip-of-private-machine-2:19000
```
I get these logs in tinyproxy status
```
Sep 01 09:29:43 ip tinyproxy[10776]: Connect (file descriptor 7): 192.168.*.*
Sep 01 09:29:43 ip tinyproxy[10776]: Request (file descriptor 7): GET http://eu-west-2.ec2.archive.ubuntu.com/ubuntu/dists/jammy/InRelease HTTP/1.1
Sep 01 09:29:43 ip tinyproxy[10776]: No upstream proxy for eu-west-2.ec2.archive.ubuntu.com
Sep 01 09:29:43 ip tinyproxy[10776]: opensock: opening connection to eu-west-2.ec2.archive.ubuntu.com:80
Sep 01 09:29:43 ip tinyproxy[10776]: Connect (file descriptor 6): 192.168.*.*
Sep 01 09:29:43 ip tinyproxy[10776]: Request (file descriptor 6): GET http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease HTTP/1.1
Sep 01 09:29:43 ip tinyproxy[10776]: No upstream proxy for security.ubuntu.com
Sep 01 09:29:43 ip tinyproxy[10776]: opensock: opening connection to security.ubuntu.com:80
Sep 01 09:29:43 ip tinyproxy[10776]: opensock: getaddrinfo returned for security.ubuntu.com:80
Sep 01 09:29:43 ip tinyproxy[10776]: opensock: getaddrinfo returned for eu-west-2.ec2.archive.ubuntu.com:80
```

This is not working for the private machine 2. Can anyone help me please with the right settings?
Thanks

**Comment by rofl0r** [comment]
use `upstream` directive to connect pm2 to pm1 in pm2's tinyproxy config. also i'd recommend to use a dedicated program for the tunnels, such as ["portredir"](https://github.com/rofl0r/portredir), ["rrredir"](https://github.com/rofl0r/rrredir), or if the tunnel needs to be encrypted, ["credir"](https://codeberg.org/rofl0r/credir), since ssh port forwarding tended to be quite unstable in my experience

**Comment by uchiha-pain** [comment]
Thanks @rofl0r for the quick response. You mentioned that 

> use upstream directive to connect pm2 to pm1 in pm2's tinyproxy config

just to clear my concept, do I need to install tinyproxy in pm2 as well and then edit the upstream flags there or just add `upstream` in the ssh tunnel?
As a beginner, an example would be much appreciated.

Thanks

**Comment by rofl0r** [comment]
you just install tinyproxy on pm2 and add `upstream http ip_of_pm1:port`. you can also just add tunnels from one place to the other but as i said before, ssh tunnels are kinda quirky so i'd try to first establish the links with portredir program. once the entire setup works you can try to switch out the single portredir tunnels with ssh ones, one by one.
also check your firewall settings.

**Comment by uchiha-pain** [comment]
Hi @rofl0r I tried to follow your tutorial/guide but seems like I could not make it work.
I am attaching the pic I made to provide your more clear image of what I am trying to achieve
![TinyProxy](https://user-images.githubusercontent.com/103254069/189628117-ab33049c-8e71-4488-acf9-a807d8710f05.png)

**Comment by rofl0r** [comment]
well, it seems pm2 cant connect to pm1, probably due to firewall rules.

**Comment by uchiha-pain** [comment]
Thanks for your patience. I have triple checked but there is no firewall enabled in my machine. But leave it as I want to try "portredir". May I get an example for how can I make the connection using portredir between 3 machines in the above scenario and then use tiny proxy to get the internet in pm2. I would be really thankful to you.

**Comment by rofl0r** [comment]
`git clone https://github.com/rofl0r/portredir ; cd portredir`
then, citing from the README:
```
build: gcc redir.c -o redir
usage: ./redir --lport=8080 --laddr=0.0.0.0 --caddr=127.0.0.1 --cport=80
makes a tunnel from 127.0.0.1:80 to 0.0.0.0:8080
```

**Comment by uchiha-pain** [comment]
I am getting this error
`-bash: ./redir: No such file or directory`

**Comment by uchiha-pain** [comment]
I really want to thank you @rofl0r for your directions about portredir. I can confirm portredir is creating tunnel pm2 to pm1. I checked it through netcat command. Now, my PM2 is sending requests to PM1 but those requests are unauthorised. Below are the logs from my PM1's tinyproxy
```
Sep 13 16:12:41 ip-192-168-81-49 tinyproxy[4174]: Starting main loop. Accepting connections.
Sep 13 16:12:41 ip-192-168-81-49 systemd[1]: Started Tinyproxy lightweight HTTP Proxy.
Sep 13 16:14:38 ip-192-168-81-49 tinyproxy[4174]: Connect (file descriptor 2): PM2-IP
Sep 13 16:14:38 ip-192-168-81-49 tinyproxy[4174]: Unauthorized connection from "PM2-IP".
Sep 13 16:14:48 ip-192-168-81-49 tinyproxy[4174]: Error reading readable client_fd 2
Sep 13 16:14:48 ip-192-168-81-49 tinyproxy[4174]: Could not retrieve request entity
Sep 13 16:16:14 ip-192-168-81-49 tinyproxy[4174]: Connect (file descriptor 2): PM2-IP
Sep 13 16:16:14 ip-192-168-81-49 tinyproxy[4174]: Unauthorized connection from "PM2-IP".
Sep 13 16:16:17 ip-192-168-81-49 tinyproxy[4174]: Error reading readable client_fd 2
Sep 13 16:16:17 ip-192-168-81-49 tinyproxy[4174]: Could not retrieve request entity
```

**Comment by rofl0r** [comment]
you gotta run wireshark on both pm1 and pm2 while trying to do a connection, so you can figure out what goes wrong.

> Sep 13 16:36:06 ip-192-168-*-* tinyproxy[4570]: read_request_line: Client (file descriptor: 2) closed socket before read.

suggests that connection can be made, but no data goes through.

**Comment by uchiha-pain** [comment]
Thank you @rofl0r for your patience and help. I have started getting the connection in my PM2. I was getting this above error because I did not specify the correct IP in apt proxy. Thanks a lot.
