### ISSUE TITLE
Tinyproxy set to start at boot, but exits when starting

### ISSUE THREAD

**Issue by ExperiBass** [tinyproxy/tinyproxy#458]
## Tinyproxy version
1.11.1

## Issue
Tinyproxy starts at boot but then closes itself with no error, instead outputting "Deactivated successfully." and exiting. Starting tinyproxy afterwards results in no problems.

**Comment by rofl0r** [comment]
tinyproxy has no option to "start at boot". report to your distro service provider instead.

**Comment by ExperiBass** [comment]
tinyproxy has a systemd service it installs. Tinyproxy is the only service that exits itself, even after being delayed. for that reason, i dont think this is a systemd issue.

**Comment by rofl0r** [comment]
> tinyproxy has a systemd service it installs.

not officially. each distro provides their own systemd (or whatever service supervisor they use) service scripts. whatever is happening to you there is a shortcoming of your distros service scripts.
