### ISSUE TITLE
Listen, Bind, and Allow/Deny directives don't allow interface name

### ISSUE THREAD

**Issue by tb3088** [tinyproxy/tinyproxy#46]
It is customary to be able to specify for example 'eth0' in such circumstances. Requiring IP address not only makes the configuration file non-reusable and brittle, but may not be valid over the course of the host's lifetime. Think AWS or other cloud/dynamic environments or just plain ol' DHCP in use.

Listen and Bind should default to the first IP address returned by querying the interface, if not otherwise specified.

Q: is there any code to handle the interface IP changing over time? Or does it just exit with "tinyproxy: Could not create listening socket." BTW that should read 'ERROR ...' we know it's tinyproxy doing the logging. Or maybe this is a separate bug wherein logging to stdout and syslog is not differentiated when running in '-d' debug mode.

Docs also imply "Access control can be based on an Interface" but provides no example, and testing bears out that "The administrator of this proxy has not configured it to service requests from your host" if 'Allow eth0' is used. If the feature is not supported, shouldn't it at least result in a parse warning?

**Comment by rofl0r** [comment]
interface device handling is highly platform dependant, and tinyproxy strives to be portable.
