### ISSUE TITLE
tinyproxy make etc and install in that folder

### ISSUE THREAD

**Issue by khordady** [tinyproxy/tinyproxy#461]
tinyproxy 1-11-1.tar.gz

Hi I am new to tinyproxy. I use ssh to install it on VPS with root user. Downloaded latest release version. Run these commands inside downloaded folder:
`./augen.sh`
`./configure`
`make`
`make install`
and every thing's fine. But tinyproxy make `/etc` folder like `downloaded_tinyproxy1.11.1/etc/` and put config there. Even service is not installed.
Thank you for helping me.

**Comment by rofl0r** [comment]
> ./augen.sh

this seems to be a typo, the right name is autogen.sh, but its use is not required when using the release tarball.

> ./configure

if you don't specify a prefix here, make install will install stuff to /usr/local. you should use `./configure --prefix=/usr --sysconfdir=/etc` to find the installed files where you expect them.

> Even service is not installed.

every linux distro uses different service supervisors, so it is their responsibility to provide service scripts. if you want to use those without writing your own, you best install tinyproxy via the distro package manager. but then, tinyproxy can be used just fine without any service scripts too.

**Comment by khordady** [comment]
If I don't run autogen.sh, when running ./configure, give me an error about dependency track. but if i run autogen and the configure it works ok.
thanks for your help i make it and run it by 
`
root@srv176251:/etc/tinyproxy# tinyproxy -d -c tinyproxy.conf 
NOTICE    Oct 23 15:14:53.707 [26472]: Initializing tinyproxy ...
NOTICE    Oct 23 15:14:53.707 [26472]: Reloading config file
INFO      Oct 23 15:14:53.707 [26472]: Setting "Via" header to 'tinyproxy'
NOTICE    Oct 23 15:14:53.707 [26472]: Reloading config file finished
INFO      Oct 23 15:14:53.707 [26472]: listen_sock called with addr = '(NULL)'
INFO      Oct 23 15:14:53.707 [26472]: trying to listen on host[0.0.0.0], family[2], socktype[1], proto[6]
INFO      Oct 23 15:14:53.707 [26472]: listening on fd [3]
INFO      Oct 23 15:14:53.707 [26472]: trying to listen on host[::], family[10], socktype[1], proto[6]
INFO      Oct 23 15:14:53.707 [26472]: listening on fd [4]
INFO      Oct 23 15:14:53.707 [26472]: Now running as group "nogroup".
INFO      Oct 23 15:14:53.707 [26472]: Now running as user "nobody".
INFO      Oct 23 15:14:53.707 [26472]: Setting the various signals.
INFO      Oct 23 15:14:53.707 [26472]: Starting main loop. Accepting connections.
` 
but when I set http/https proxy in my browsr, and try to connect google.com it says
`
CONNECT   Oct 23 15:15:12.791 [26472]: Connect (file descriptor 5): "My local PC IP"
NOTICE    Oct 23 15:15:12.791 [26472]: Unauthorized connection from "My local PC IP".
`
i didn't change any setting except `group "nogroup"` and didn't set any user pass.
server os: ubuntu 20.04
client firefox 91.11

**Comment by rofl0r** [comment]
see http://tinyproxy.github.io/#quickstart and adjust Allow/Deny directive to suit your needs.

**Comment by khordady** [comment]
yes i saw that and i couldn't make it works. So i completely removed tinyproxy. thank you by the way
these were logs when i removed all allow option:
INFO      Oct 23 21:27:11.669 [4502]: Starting main loop. Accepting connections.
CONNECT   Oct 23 21:29:59.834 [4502]: Connect (file descriptor 6): MYIP
CONNECT   Oct 23 21:30:00.547 [4502]: Request (file descriptor 5): CONNECT www.google.com:443 HTTP/1.1
INFO      Oct 23 21:30:00.547 [4502]: No upstream proxy for www.google.com
INFO      Oct 23 21:30:00.547 [4502]: opensock: opening connection to www.google.com:443
INFO      Oct 23 21:30:00.565 [4502]: opensock: getaddrinfo returned for www.google.com:443
CONNECT   Oct 23 21:30:00.612 [4502]: Established connection to host "www.google.com" using file descriptor 7.
INFO      Oct 23 21:30:00.612 [4502]: Not sending client headers to remote machine
INFO      Oct 23 21:30:00.657 [4502]: Closed connection between local client (fd:5) and remote client (fd:7)

**Comment by rofl0r** [comment]
> So i completely removed tinyproxy.

ok, since you moved to another product i guess we can close this.
