### ISSUE TITLE
TinyProxy just died

### ISSUE THREAD

**Issue by HKowi** [tinyproxy/tinyproxy#463]
Version 1.11.1
OS Base: Openbsd 7.2
Build from tarball

Thanks for this product; works well so far.
I had however, just instances where TinyProxy just died. No reason why - at least to me. These are the only related messages:
Messages:
Oct 28 16:00:00 xxxxxxxxxxx tinyproxy: backwards memcpy
From TP Log:
CONNECT   Oct 28 16:00:00.105 [10106]: Connect (file descriptor 9): xxx.xx.x.xxx
CONNECT   Oct 28 16:00:00.105 [10106]: Request (file descriptor 9): connected.
ERROR     Oct 28 16:00:00.301 [10106]: process_request: Bad Request on file descriptor 9
ERROR     Oct 28 16:00:00.301 [10106]: Error opening error file '/usr/local/share/tinyproxy/400.html' (Permission denied)
CONNECT   Oct 28 16:00:00.316 [10106]: Connect (file descriptor 9): xxx.xx.x.xxx
CONNECT   Oct 28 16:00:00.317 [10106]: Request (file descriptor 9): connected.
ERROR     Oct 28 16:00:00.511 [10106]: process_request: Bad Request on file descriptor 9
DEBUG     Oct 28 16:11:42.114 [86456]: sending stored logs
NOTICE    Oct 28 16:11:42.114 [86456]: Initializing tinyproxy ...

Any hint? The permissions on the html-files are fixed.

Thanks
       Horst

**Comment by rofl0r** [comment]
please run tinyproxy in foreground mode in a debugger, e.g. `gdb --args tinyproxy -d -c tinyproxy.conf` then `run<ENTER>`

the message ` Oct 28 16:00:00 xxxxxxxxxxx tinyproxy: backwards memcpy` seems to come from openbsd and might indicate some bug in tinyproxy code. once the bug is hit gdb should halt and you can provide the backtrace via `bt`.

apart from that, you might want to try to change the line `208 src/child.c                              pthread_attr_setstacksize(attrp, 256*1024);` to 512*1024, maybe openbsd is using way more stack memory than other OS's.

**Comment by rofl0r** [comment]
> putting a debugger on just renders TP non-functional

did you use command line option `-d` ? this should prevent tinyproxy from backgrounding.

> A word of warning could have been needed regards the config. A new install overwrites the old conf-file. I find that a bit strange.

well, the job of make install is to overwrite everything shipped with tinyproxy. you can put the tinyproxy.conf file anywhere on your fs and just use the -c command line option to specify which one to use. i'd also recommend to use a minimal config file for debugging, such as the one mentioned in quickstart section on the homepage (i.e. no log, no pidfile, no user switching)

**Comment by HKowi** [comment]
Yes, I used the exact line you have provided. It is less a problem with TP going background (I started it from CLI on the router) it is more that TP is not creating a listener port at all. A "netstat -an | grep 8888" shows an empty response.

**Comment by rofl0r** [comment]
> it is more that TP is not creating a listener port at all

odd, your above log paste suggests otherwise.

> "netstat -an | grep 8888" shows an empty response.

at least on linux, you need to use `l` option for netstat to print listening sockets too

**Comment by HKowi** [comment]
Hi,
this is what I get:
bash-5.1# fstat | grep tiny
bash-5.1# ps -A | grep tiny
14201 p0  R+/1     0:00.00 grep tiny
50535 C0  I+       0:00.03 gdb --args tinyproxy -d -c /usr/local/etc/tinyproxy/tinyproxy.conf
bash-5.1# 
bash-5.1# 
/* Stopped the DEBUG session and started the "normal" app */
bash-5.1# fstat | grep tiny
nobody   tinyproxy  34372 text /         9224832  -rwxr-xr-x     r   299464
nobody   tinyproxy  34372   wd /               2  drwxr-xr-x     r     1024
nobody   tinyproxy  34372    0* internet stream tcp 0xffff800000c9b560 xxx.xxx.xxx.9:8888
nobody   tinyproxy  34372    1 /         9536758  -rw-r--r--    rw   118704
nobody   tinyproxy  34372    2* internet stream tcp 0xffff800000c9a060 xxx.xxx.xxx.9:8888 <-- xxx.xxx.xxx.19:52266
nobody   tinyproxy  34372    3* internet stream tcp 0xffff800000c9a960 192.168.1.2:14001 --> 13.107.42.14:443
nobody   tinyproxy  34372    4* internet stream tcp 0xffff800000c9bb60 xxx.xxx.xxx.9:8888 <-- xxx.xxx.xxx.19:52282
nobody   tinyproxy  34372    5* internet stream tcp 0xffff800000c9a360 192.168.1.2:15083 --> 152.199.21.118:443
nobody   tinyproxy  34372    6* internet stream tcp 0xffff800000be7b08 xxx.xxx.xxx.9:8888 <-- xxx.xxx.xxx.19:52286
nobody   tinyproxy  34372    7* internet stream tcp 0xffff800000be6308 192.168.1.2:1858 --> 152.199.21.118:443
nobody   tinyproxy  34372    8* internet stream tcp 0xffff800000bca900 xxx.xxx.xxx.9:8888 <-- xxx.xxx.xxx.19:52290
nobody   tinyproxy  34372    9* internet stream tcp 0xffff800000bca600 192.168.1.2:17434 --> 13.107.42.14:443
nobody   tinyproxy  34372   10* internet stream tcp 0xffff800000bcb500 xxx.xxx.xxx.9:8888 <-- xxx.xxx.xxx.19:52306
nobody   tinyproxy  34372   11* internet stream tcp 0xffff800000bcb800 192.168.1.2:6154 --> 13.107.42.14:443

As mentioned, it happened only once and i am happy to bury it, was just wondering why it happened.

**Comment by rofl0r** [comment]
so the bug happened just once ? maybe next time it happens, try to recall what sites you opened in the browser, then try to do everything again while running tinyproxy under gdb. i've skimmed a couple of memcpy calls in the source code but didn't see occurences where memory ranges could overlap.

**Comment by HKowi** [comment]
So far yes, I think.
I will collect more evidence for next time. Closing for now. Thanks for looking (got me converted from Squid ....).
