### ISSUE TITLE
tinyproxy

### ISSUE THREAD

**Issue by jjjjaaaaaaa** [tinyproxy/tinyproxy#465]
# IMPORTANT NOTICE

Before filing an issue here PLEASE keep in mind that **tinyproxy 1.10.0 and older are no longer supported**.
Do not report issues with 1.10.0 or older, first try latest release 1.11.0, or even better, git master, and see whether the issue is already fixed.

## Tinyproxy version
State the tinyproxy version you're using; whether git master or 1.11.0 stable.

## Issue
what the need of  checking particular header files like sysexits.h , values.h in confugure.ac file in tinyproxy ? what is the dependency 
 of these header files in tiny proxy ?

**Comment by rofl0r** [comment]
probably cruft from 20 years ago, but since each configure check takes like 10 ms i guess it can't hurt to leave it there even if unneeded. the time needed to figure out why or where they could be needed would be a lot bigger.

**Comment by jjjjaaaaaaa** [comment]
what is the mean of oddball headers ? is this madatory headers files riquired for tinyproxy  or it doesn't effect much on the functionality ?

**Comment by rofl0r** [comment]
doesn't affect functionality. i suppose they are/were needed to get some definitions on exotic OSs like sun os, HPUX, etc.
