### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by HKowi** [tinyproxy/tinyproxy#466]
## Issue
First of all: TP works generally for local networks. 
My setup incorporates 3 networks - all in the 10.x.x.x range. The first one is local to TP the other two are VPN. Using VPN iam getting:

CONNECT   Dec  [69397]: Connect (file descriptor 3): 10.7.5.14
NOTICE    Dec     [69397]: Unauthorized connection from "10.7.5.14".
INFO      Dec        [69397]: Read request entity of 245 bytes

The browser comes back with error...cannot connect (not really surprising).
The order is like:
Allow 10.100.0.0/16
Allow 10.7.5.0/24
Allow 10.44.99.0/24

I even tried "Allow 10.0.0.0/8" - same error.

I know it is not the firewall/router, same IP are working with SQUID.

I have a crude workaround, using SOCKS, but I would prefer TP.

I am lost now, where to go from here.

Thanks, 
   Horst

**Comment by rofl0r** [comment]
does it work without any Allow directives ? do you have BasicAuth enabled ?

**Comment by HKowi** [comment]
No, same error with any "Allow" removed. No Auth enabled.

**Comment by HKowi** [comment]
FYI - my config (to make things easier)
==================================
User nobody
Group nobody
Port 3142
Listen 10.100.88.3
Timeout 600
ErrorFile 400 "/usr/local/share/tinyproxy/400.html"
ErrorFile 500 "/usr/local/share/tinyproxy/500.html"
ErrorFile 404 "/usr/local/share/tinyproxy/404.html"
DefaultErrorFile "/usr/local/share/tinyproxy/default.html"
StatFile "/usr/local/share/tinyproxy/stats.html"
LogFile "/usr/local/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
PidFile "/usr/local/var/run/tinyproxy/tinyproxy.pid"
MaxClients 100
Allow 10.100.0.0/16
Allow 10.7.5.0/24
Allow 10.44.99.0/24
ViaProxyName "myproxy"

**Comment by rofl0r** [comment]
#463 doesnt mention any modifications afaics
