### ISSUE TITLE
Is there a way to bind to an IP address for all traffic?

### ISSUE THREAD

**Issue by bogorad** [tinyproxy/tinyproxy#475]
## Tinyproxy version
tinyproxy version 1.10.0 running on an OpenWRT (x64) system

## Issue
I have a Wireguard tunnel set up, with a unique IP address that I bind tinyproxy to. I want all proxied traffic to go via this tunnel. I don't have (or need) any upstream proxies. Currently, whatever I do, the proxied traffic goes out directly. On https://tinyproxy.github.io/ it says:

> Bind 
> This allows you to specify which address Tinyproxy will bind to for 
> outgoing connections **to web servers** or upstream proxies.

(emphasis mine)

But I can't figure out if this is even possible without an upstream proxy.

**Comment by rofl0r** [comment]
i guess this comment should just be shortened to "This allows you to specify which address Tinyproxy will bind to for outgoing connections."

But yeah, this is the option you want to use to achieve your goal.
btw you should try to acquire tinyproxy 1.11.1 (compile it yourself if not available in openwrt repos or push openwrt folks to update their package).
