### ISSUE TITLE
Support apr1 hashing for BasicAuth passwords

### ISSUE THREAD

**Issue by ilyaevseev** [tinyproxy/tinyproxy#480]
Passwords for BasicAuth in htpasswd can be stored in apr1 or ssha format.
It's supported by Apache, [Nginx](http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html) and many other apps.
It woult be fine to get the same possibility in tinyproxy.

**Comment by rofl0r** [comment]
is this about not storing the password in plaintext in the config file ?

**Comment by ilyaevseev** [comment]
> is this about not storing the password in plaintext in the config file ?

Yes

**Comment by rofl0r** [comment]
well, you can use unix permissions so only tinyproxy user and root can read the file. the password is sent in plaintext over network anyway, so i dont see the point of adding outdated and broken password hashes to obfuscate the password in the config.
