### ISSUE TITLE
Proxy didn't work

### ISSUE THREAD

**Issue by zzhkiller** [tinyproxy/tinyproxy#490]
## Tinyproxy version
 Tinyproxy  1.11.1

INFO      Apr 25 11:40:33.123 [10933]: opensock: opening connection to api.openai.com:443
INFO      Apr 25 11:40:33.126 [10933]: opensock: getaddrinfo returned for api.openai.com:443
CONNECT   Apr 25 11:40:33.138 [10933]: Established connection to host "api.openai.com" using file descriptor 10.
INFO      Apr 25 11:40:33.139 [10933]: Not sending client headers to remote machine
ERROR     Apr 25 11:40:33.997 [10933]: read_buffer: read() failed on fd 9: Connection reset by peer

**Comment by rofl0r** [comment]
maybe GFW is interfering. can't help you without further info. generally you can test whether tp works by running it on localhost, then try curl with and without the proxy.

**Comment by ianmarcinkowski** [comment]
Can this issue be closed?
