### ISSUE TITLE
Allow/Deny by User-Agent?

### ISSUE THREAD

**Issue by gingerbeardman** [tinyproxy/tinyproxy#496]
## Tinyproxy version
- 1.11.1

## Issue
I find myself constantly adjusting Allow/Deny when I'm travelling or on my iPhone. 

It would be great if I could Allow requests from a specific user agent (app not browser). .

Forgive me if this is a bad idea, and I'll also accept any recommendations to better manage my personal proxy when I'm travelling/mobile.

**Comment by rofl0r** [comment]
how about using basicauth username/password for the proxy ? that makes sure only you can use it.

**Comment by gingerbeardman** [comment]
That sounds like a plan, but has raised another issue: #497

**Comment by gingerbeardman** [comment]
Sure!
