### ISSUE TITLE
ReversePath to https direct to error upstream

### ISSUE THREAD

**Issue by idreamerhx** [tinyproxy/tinyproxy#505]
# IMPORTANT NOTICE

Before filing an issue here PLEASE keep in mind that **tinyproxy 1.10.0 and older are no longer supported**.
Do not report issues with 1.10.0 or older, first try latest release 1.11.0, or even better, git master, and see whether the issue is already fixed.

## Tinyproxy version
State the tinyproxy version you're using; whether git master or 1.11.0 stable.
1.11.1

## Issue
Fill in your Issue text here.
A good issue report is detailed and includes full error messages from tinyproxy's output, not "X doesn't work".

tinyproxy.config

ReversePath "/xxx-xxx-2/"    "https://192.168.6.18:443/"

**Comment by rofl0r** [comment]
closing due to lack of information
