### ISSUE TITLE
ReversePath to https direct to error upstream

### ISSUE THREAD

**Issue by idreamerhx** [tinyproxy/tinyproxy#506]
# IMPORTANT NOTICE

Before filing an issue here PLEASE keep in mind that **tinyproxy 1.10.0 and older are no longer supported**.
Do not report issues with 1.10.0 or older, first try latest release 1.11.0, or even better, git master, and see whether the issue is already fixed.

## Tinyproxy version
State the tinyproxy version you're using; whether git master or 1.11.0 stable.
1.11.1

## Issue
Fill in your Issue text here.
A good issue report is detailed and includes full error messages from tinyproxy's output, not "X doesn't work".

tinyproxy.config

ReversePath "/xxx-xxx-2/"    "https://192.168.6.18:443/"

[root@guppy src]# cat tinyproxy.log
NOTICE    Aug 11 12:39:21.756 [2172965]: Initializing tinyproxy ...
NOTICE    Aug 11 12:39:21.757 [2172965]: Reloading config file
INFO      Aug 11 12:39:21.757 [2172965]: Setting "Via" header to 'tinyproxy'
INFO      Aug 11 12:39:21.758 [2172965]: Adding Port [443] to the list allowed by CONNECT
INFO      Aug 11 12:39:21.758 [2172965]: Adding Port [563] to the list allowed by CONNECT
INFO      Aug 11 12:39:21.758 [2172965]: Added reverse proxy rule: /rio-home8500/ -> http://192.168.3.10/
INFO      Aug 11 12:39:21.759 [2172965]: Added reverse proxy rule: /f/ -> http://192.168.1.7:8085/
INFO      Aug 11 12:39:21.759 [2172965]: Added reverse proxy rule: /xxx-xxx-2/ -> https://192.168.6.18:443/
NOTICE    Aug 11 12:39:21.760 [2172965]: Reloading config file finished
INFO      Aug 11 12:39:21.760 [2172965]: listen_sock called with addr = '(NULL)'
INFO      Aug 11 12:39:21.761 [2172965]: trying to listen on host[0.0.0.0], family[2], socktype[1], proto[6]
INFO      Aug 11 12:39:21.761 [2172965]: listening on fd [3]
INFO      Aug 11 12:39:21.761 [2172965]: trying to listen on host[::], family[10], socktype[1], proto[6]
INFO      Aug 11 12:39:21.762 [2172965]: listening on fd [4]
INFO      Aug 11 12:39:21.762 [2172965]: Now running as group "root".
INFO      Aug 11 12:39:21.763 [2172965]: Now running as user "root".
INFO      Aug 11 12:39:21.763 [2172965]: Setting the various signals.
INFO      Aug 11 12:39:21.763 [2172965]: Starting main loop. Accepting connections.
CONNECT   Aug 11 12:39:26.460 [2172965]: Connect (file descriptor 6): 192.168.1.35
CONNECT   Aug 11 12:39:26.460 [2172965]: Connect (file descriptor 7): 192.168.1.35
CONNECT   Aug 11 12:39:26.461 [2172965]: Request (file descriptor 6): GET /xxx-xxx-2/ HTTP/1.1
CONNECT   Aug 11 12:39:26.463 [2172965]: Rewriting URL: /xxx-xxx-2/ -> https://192.168.6.18:443/
INFO      Aug 11 12:39:26.463 [2172965]: process_request: trans Host GET http://192.168.1.7:5050https://192.168.6.18:443/ for 6
INFO      Aug 11 12:39:26.464 [2172965]: No upstream proxy for 192.168.1.7
INFO      Aug 11 12:39:26.465 [2172965]: opensock: opening connection to 192.168.1.7:5050
INFO      Aug 11 12:39:26.466 [2172965]: opensock: getaddrinfo returned for 192.168.1.7:5050
CONNECT   Aug 11 12:39:26.467 [2172965]: Established connection to host "192.168.1.7" using file descriptor 8.
CONNECT   Aug 11 12:39:26.467 [2172965]: Connect (file descriptor 9): 192.168.1.7
CONNECT   Aug 11 12:39:26.469 [2172965]: Prevented endless loop (file descriptor 9): 192.168.1.7
INFO      Aug 11 12:39:26.470 [2172965]: Read request entity of 569 bytes
ERROR     Aug 11 12:39:26.471 [2172965]: Error opening error file '/usr/share/tinyproxy/default.html' (No such file or directory)
INFO      Aug 11 12:39:26.472 [2172965]: Closed connection between local client (fd:6) and remote client (fd:8)
CONNECT   Aug 11 12:39:26.663 [2172965]: Request (file descriptor 7): GET /favicon.ico HTTP/1.1
INFO      Aug 11 12:39:26.664 [2172965]: Magical tracking cookie says: /xxx-xxx-2/
CONNECT   Aug 11 12:39:26.665 [2172965]: Rewriting URL: /favicon.ico -> https://192.168.6.18:443/favicon.ico
INFO      Aug 11 12:39:26.665 [2172965]: process_request: trans Host GET http://192.168.1.7:5050https://192.168.6.18:443/favicon.ico for 7
INFO      Aug 11 12:39:26.666 [2172965]: No upstream proxy for 192.168.1.7
INFO      Aug 11 12:39:26.667 [2172965]: opensock: opening connection to 192.168.1.7:5050
INFO      Aug 11 12:39:26.668 [2172965]: opensock: getaddrinfo returned for 192.168.1.7:5050
CONNECT   Aug 11 12:39:26.668 [2172965]: Established connection to host "192.168.1.7" using file descriptor 6.
CONNECT   Aug 11 12:39:26.669 [2172965]: Connect (file descriptor 8): 192.168.1.7
CONNECT   Aug 11 12:39:26.670 [2172965]: Prevented endless loop (file descriptor 8): 192.168.1.7
INFO      Aug 11 12:39:26.671 [2172965]: Read request entity of 501 bytes
ERROR     Aug 11 12:39:26.672 [2172965]: Error opening error file '/usr/share/tinyproxy/default.html' (No such file or directory)
INFO      Aug 11 12:39:26.673 [2172965]: Closed connection between local client (fd:7) and remote client (fd:6)
NOTICE    Aug 11 12:39:36.801 [2172965]: Shutting down.
INFO      Aug 11 12:39:36.802 [2172965]: trying to bring down 2 threads...

**Comment by idreamerhx** [comment]
src/transparent-proxy.c:115

**Comment by rofl0r** [comment]
bug is fixed in master, also you cant reverse proxy https due to ssl.

**Comment by idreamerhx** [comment]
thanks for the great project. I'll try

**Comment by gingerbeardman** [comment]
Thanks for this, I was running an old version that has this or a similar error and I realised my docker container was not auto-updating.
