### ISSUE TITLE
create_file_safely() should take args for write-ability and permissions

### ISSUE THREAD

**Issue by tb3088** [tinyproxy/tinyproxy#52]
First, truncate_file should be a 'char'. Unsigned int for a boolean?!
Don't just force 0600. The correct value is 0666. if you want to extra paranoid (underlying hasn't bothered to set a umask) then 0644. Or more correctly 'S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH'.

Being able to read a log or pid file by non-privileged users can be damn convenient.
And why creating files as O_RDWR when all that matters is O_WRONLY?

**Comment by tb3088** [comment]
in main() the umask is being set to 0177 which is frankly wrong; the comment about mkstemp() not-withstanding. Sure, it might make sense to have it in child.c _child_lock_init() and in heap.c malloc_shared_memory() but doesn't belong in main(). 

Set to 022 if at all.

**Comment by rofl0r** [comment]
looks like an opinion to me, noted.
