### ISSUE TITLE
When binding multiple IPv6 addresses, only the first one will be used as the outbound IP

### ISSUE THREAD

**Issue by Rainscall** [tinyproxy/tinyproxy#526]
## Tinyproxy version
State the tinyproxy version you're using; whether git master or 1.11.0 stable.
tinyproxy 1.11.0

## Issue
When binding multiple IPv6 addresses, only the first one will be used as the outbound IP
My configuration file is like this
```
User tinyproxy
Group tinyproxy
Listen ::1
Port 3129
Bind 2605:6400:4222::1
Bind 2605:6400:4222::2
Bind 2605:6400:4222::3
Bind 2605:6400:4222::4
Timeout 60
```
In any case, only "2605:6400:4222::1" will be used, and the remaining other IPs will not work.
Moreover, "2605:6400:4222::/48" has been routed to lo. Using "curl example.com --int 2605:6400:4222::1234" to bind the Outgoing IP can work normally.

**Comment by rofl0r** [comment]
> In any case, only "2605:6400:4222::1" will be used, and the remaining other IPs will not work.

you mean connecting to them will not work, or as the title says the outcoming connection will come from ::1 ?

then the question becomes, what **should** happen ?
is it expected an outgoing connection is being made from the address the incoming ip was bound to, or via the one set as default gateway in the kernel routing configuration ? and even if that is the agreed upon behaviour, how can it be implemented in a portable manner (i.e. not using linux-specific syscalls) ?

**Comment by rofl0r** [comment]
i just recalled there's the BindSame directive. from the manpage:
```
    BindSame
          If  this boolean parameter is set to `yes`, then Tinyproxy will bind
          the outgoing connection to the IP address of the incoming connection
          that triggered the outgoing request.
```
did you use that ?
