### ISSUE TITLE
Need to get the source code of tinyproxy 1.8.3 version from where I can get that version.

### ISSUE THREAD

**Issue by ravburra** [tinyproxy/tinyproxy#528]
# IMPORTANT NOTICE

Before filing an issue here PLEASE keep in mind that **tinyproxy 1.10.0 and older are no longer supported**.
Do not report issues with 1.10.0 or older, first try latest release 1.11.0, or even better, git master, and see whether the issue is already fixed.

## Tinyproxy version
State the tinyproxy version you're using; whether git master or 1.11.0 stable.

## Issue
Fill in your Issue text here.
A good issue report is detailed and includes full error messages from tinyproxy's output, not "X doesn't work".

**Comment by rofl0r** [comment]
http://www.slackware.com/~alien/slackbuilds/tinyproxy/build/  3rd result in google for tinyproxy-1.8.3.tar

you can also click on tags in this repo, select 1.8.3, then download the source tarball.
