### ISSUE TITLE
User, Group directives should be evaluated at parse time, NOT at change_user()

### ISSUE THREAD

**Issue by tb3088** [tinyproxy/tinyproxy#53]
Values in configuration files need to be verified first and program aborted if invalid. Not wait until trying to drop privs.

!!FIXME!!
if config.user or config.group are not set or or empty string it SKIPS over setuid() and setgroups().

**Comment by rofl0r** [comment]
please reopen this with more context if still relevant.
with more context i mean not just a line number dropped here but a link to a specific blob, etc
