### ISSUE TITLE
Allow /range not working as expected?

### ISSUE THREAD

**Issue by gingerbeardman** [tinyproxy/tinyproxy#534]
## Tinyproxy version
1.11.0 stable (docker)

## Issue
I'm trying to open up the proxy to a range of dynamic IP (company) where the final digits vary. 

So, I'm doing:

`Allow 12.34.56.0/255`

But that doesn't seem to work? Access is sometimes not granted (seems based on how big the final number is). 

Is there a limit?

I've even tried smaller batches, of 85 and 50, but still no joy. 

```
Allow 12.34.56.0/85
Allow 12.34.56.85/85
Allow 12.34.56.170/85
```

I'm also allowing access from some specific dyndns domains, for devices temporarily on other networks.

`Allow example.dydns.org`

Any help or advice appreciated.

**Comment by rofl0r** [comment]
see CIDR notation section in https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing
