### ISSUE TITLE
Option to disable disclosure of version via header and templates?

### ISSUE THREAD

**Issue by jpmckinney** [tinyproxy/tinyproxy#542]
e.g. https://github.com/tinyproxy/tinyproxy/blob/72b93f6d4b598a1f809f4e5ff383757c52fa9765/src/utils.c#L42 and https://github.com/tinyproxy/tinyproxy/blob/72b93f6d4b598a1f809f4e5ff383757c52fa9765/src/html-error.c#L202

For example, Apache has [ServerTokens Prod](https://httpd.apache.org/docs/2.4/mod/core.html#servertokens) and nginx has [server_tokens off;](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens).

When getting cybersecurity insurance, for example, the insurer often uses an automated service to check for vulnerabilities, and Ubuntu, Debian, etc. do not update version numbers after patching, therefore the service reports false positives and the insurer then wants to increase premiums, unless the insured goes through the process of getting those false positives removed. A much simpler solution is to prevent those automated services from raising false positives to begin with, by not disclosing tinyproxy's version.

**Comment by rofl0r** [comment]
for some reason it was chic to announce product version in the 90ies.
i suppose it can't hurt to just remove the version output from everywhere except the command line output (so a user can check the version). can you come up with a PR doing that ?

**Comment by jpmckinney** [comment]
@rofl0r Any chance there's a new release soon? Last release was in May 2024.
