### ISSUE TITLE
[HELP] The ERROR logs show a sequence, even though the proxy is working well.

### ISSUE THREAD

**Issue by laiminhtrung1997** [tinyproxy/tinyproxy#544]
```
CONNECT   Jun 21 12:03:43.195 [1]: Connect (file descriptor 6): 10.113.43.218
ERROR     Jun 21 12:03:43.195 [1]: read_request_line: Client (file descriptor: 6) closed socket before read.
```
An error has been logged. The IP address 10.113.43.218 belongs to the EC2 instance. I have deployed Tinyproxy as a Kubernetes pod within an AWS EKS cluster. Despite the proxy functioning properly, the error logs persist. What could be causing this issue? And how can I prevent it from occurring in the future?

**Comment by rofl0r** [comment]
it's probably some sort of  heartbeat checker. no need to worrry, just ignore these lines.
