### ISSUE TITLE
Is tinyproxy.service systemd file correct?

### ISSUE THREAD

**Issue by keelerad** [tinyproxy/tinyproxy#553]
Couldn't see the systemd file in your source but in case anyone else has the issue created this here for them to find

## Tinyproxy version
tinyproxy-1.11.2-1.el9.x86_64 from EPEL 9 running on Rocky 9

## Issue
After a reboot tinyproxy failed to start but it was trying to start before NetworkManager had finished its startup

Aug 16 07:03:35 rocinante tinyproxy[896]: /usr/bin/tinyproxy: Could not create listening sockets.
Aug 16 07:03:35 rocinante systemd[1]: Started Command Scheduler.
Aug 16 07:03:35 rocinante systemd[1]: Started Getty on tty1.
Aug 16 07:03:35 rocinante systemd[1]: Reached target Login Prompts.
Aug 16 07:03:35 rocinante systemd[1]: tinyproxy.service: Main process exited, code=exited, status=71/OSERR
Aug 16 07:03:35 rocinante systemd[1]: tinyproxy.service: Failed with result 'exit-code'.
Aug 16 07:03:35 rocinante systemd[1]: Started OpenSSH server daemon.
Aug 16 07:03:37 rocinante systemd[1]: Starting Authorization Manager...
Aug 16 07:03:37 rocinante polkitd[977]: Started polkitd version 0.117
Aug 16 07:03:37 rocinante systemd[1]: Started Authorization Manager.
Aug 16 07:03:38 rocinante systemd[1]: Started Postfix Mail Transport Agent.
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.4314] device (ens192): state change: config -> ip-config (reason 'none', sys-iface-state: 'managed')
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.4344] dhcp4 (ens192): activation: beginning transaction (timeout in 45 seconds)
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.4762] dhcp4 (ens192): state changed new lease, address=172.16.0.99
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.4809] policy: set 'ens192' (ens192) as default for IPv4 routing and DNS
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.5188] device (ens192): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'managed')
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.5284] device (ens192): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'managed')
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.5308] device (ens192): state change: secondaries -> activated (reason 'none', sys-iface-state: 'managed')
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.5330] manager: NetworkManager state is now CONNECTED_SITE
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.5358] device (ens192): Activation: successful, device activated.
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.5387] manager: NetworkManager state is now CONNECTED_GLOBAL
Aug 16 07:03:38 rocinante NetworkManager[865]: <info>  [1723788218.5419] manager: startup complete
Aug 16 07:03:38 rocinante systemd[1]: Finished Network Manager Wait Online.
Aug 16 07:03:38 rocinante systemd[1]: Reached target Network is Online.

## Suggested fix 

change tinyproxy.service `After` line from `network.target` to `network-online.target`

This fixed it for me

Alec

**Comment by rofl0r** [comment]
@carlwgeorge ^

**Comment by carlwgeorge** [comment]
Thanks for the heads up.  This was also reported in bugzilla, so we can close this issue and focus the conversation over there.

https://bugzilla.redhat.com/show_bug.cgi?id=2305297

**Comment by rofl0r** [comment]
great, thanks!

**Comment by carlwgeorge** [comment]
After some investigation, we may want to re-open this, because I have a question for the tinyproxy developers.  systemd has this to say:

> It is strongly recommended not to make use of this target too liberally: for example network server software should generally not pull this in (since server software generally is happy to accept local connections even before any routable network interface is up). Its primary purpose is network client software that cannot operate without network.

https://systemd.io/NETWORK_ONLINE/

Based on that, would it be a more holistic fix to change tinyproxy to be able to start without a configured interface, and then listen on new interfaces as they come online?

**Comment by rofl0r** [comment]
i dont think adding that complexity to tinyproxy just to adhere to poettering's personal philosophy is worth the effort. and then, where does it end? should i change all my other network daemons, like microsocks, too ? i dont think so. let's just use the network-online target despite of the warning.
