### ISSUE TITLE
child.c child_main() holding onto SERVER_COUNT_LOCK much longer than needed

### ISSUE THREAD

**Issue by tb3088** [tinyproxy/tinyproxy#56]
line 323-339, take the lock, get server_waiting and then release the lock. Logging should not be done while holding the lock.

Frankly why do we care if servers_waiting is precisely accurate when evaluating the IF?
Same issue in child_main_loop().

'Killing child' messages are more properly "marking child(self) for destruction". 
Misplaced DEBUG2 at line 313

**Comment by rofl0r** [comment]
why don't you just open PRs instead of firing out words ? the line numbers you mention today will be entirely out of tune after some changes, and then people will have to waste a lot of time to find the code you're refering to.

**Comment by tb3088** [comment]
I do intend to file PR's. But it makes more sense to put issues out there and PR against them.

**Comment by nihilus** [comment]
@tb3088 did you resolve this?

**Comment by rofl0r** [comment]
obsoleted by b935dc85c3fca51de8e131d6aa2047f8a0404f0c
