### ISSUE TITLE
Sanity check configs before trying to run

### ISSUE THREAD

**Issue by tb3088** [tinyproxy/tinyproxy#57]
Another case of not checking inputs till LONG after the fact. I expect there are an easy dozen more!

child.c child_pool_create() lines 384-395

**Comment by obnoxxx** [comment]
Thanks for all your issues!
Will go through them and comment / fix soon (as I find time).

**Comment by tb3088** [comment]
I will be submitting pull requests as well when I get them written and tested.

**Comment by obnoxxx** [comment]
Great, thanks! (I might start looking into some myself at some point, but very happy to accept patches!)
