### ISSUE TITLE
too many configure tests

### ISSUE THREAD

**Issue by rofl0r** [tinyproxy/tinyproxy#65]
```
$ ./configure | wc -l
246

$ time ./configure >/dev/null

real    0m7.701s
user    0m0.002s
sys     0m0.000s

$ time make -j2 > /dev/null 2>&1

real    0m3.347s
user    0m0.000s
sys     0m0.000s
```

as you can see, time wasted in configure is more than 2x time needed to build. difference is even bigger with more cores used. there are about 30 configure test just checking if different warning options are supported. imo that doesnt make sense. just use -Wall -Wextra and leave it at that. there are also a lot of tests for things that just must be there. i mean if your libc doesn't have memcpy, you cannot compile anything anyway.
there are also a lot of tests for headers like stddef.h, stdio.h etc that are standard C. what's the point in testing for them ? is there even a fallback if not there ? i doubt it.
probably configure will fail with an error message that you need stdio.h. but that's no better than failing during `make` invocation with a message from the compiler that stdio.h could not be found.

**Comment by rofl0r** [comment]
most or all of these configure checks were written 20 years ago for C89 environments. it's about time to remove them!

**Comment by rofl0r** [comment]
even if it breaks someone's build on prehistoric AIX systems, it's better to just push out a release with the cruft removed and see if anyone cries. then we can add back the one or two header that they still do not have.

**Comment by obnoxxx** [comment]
What amount of speed-up do you see with #86 merged? @rofl0r

**Comment by rofl0r** [comment]
right now a configure run takes:
```
real    0m3.995s 
```
i.e. about half of the time than it was before #66 was applied.
