### ISSUE TITLE
Tinyproxy reorders the headers received before forwarding them

### ISSUE THREAD

**Issue by artemeus** [tinyproxy/tinyproxy#73]
Build I am using: tinyproxy-1.8.2-1.el6.rf.x86_64.rpm 

I have seen this mentioned in a couple of posts.
The order of HTTP Headers sent into the proxy is not in the same order as the ones which get forwarded.
Currently I send this (Chrome browser headers):
Host: request.urih.com
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,ru;q=0.6

And the tinyproxy sends out below (shuffling Accept, Upgrade... and Cache-control):
Host: request.urih.com
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

I know that RFC says it shouldn't matter, but it does - I have issues with half-dozen sites due to this. The consistency of behavior also allows to fingerprint the request as one likely coming from tinyproxy which takes away from its purpose.

There is a separate enhancement for Connection: keep-alive which would help there as well.

Screenshot from Chrome with Dev Tools pointing to a site printing raw headers:
![image](https://cloud.githubusercontent.com/assets/1572181/21590194/6a2b5206-d0ae-11e6-97cc-695652dfaa37.png)

Thank you!!

**Comment by JodeZer** [comment]
First of all,this tinyproxy uses a random hashmap to restore client request headers and then rewrite them to server socket  in that hashmap order.Thus,the order may not be same.
Secondly, the header "Connection" is removed in code  and replace with "Connection:Close" .l considerd that the author may think there is no need to keep long connections between proxy and server.(Or other more important reason ,please tell)

Therefore,l don't think tinyproxy meets your requirments :)

ps : l just red the code today and planed to use it as a forward proxy; If l misunderstood something ,please tell me! Thinks!
