### ISSUE TITLE
Tinyproxy does not change IP

### ISSUE THREAD

**Issue by ghost** [tinyproxy/tinyproxy#75]
I have installed tinyproxy on my system Ubuntu 14.04, and redirect wget requests through tinyproxy in a perl script. I am trying to avoid "too many requests".

When i check the IP address it is still my public IP address, nothing changes. Can you please share a config file that will achieve what i am looking for.

I have also tried to use proxychains with tinyproxy, for example every time a connection is refused the proxy will change. But i also cannot get this to work.

Can someone assist ?

**Comment by xxllp** [comment]
do you get the idea?

**Comment by rofl0r** [comment]
closing as author deleted his account.
