### ISSUE TITLE
Log files not being created when installing through Homebrew

### ISSUE THREAD

**Issue by wputnam** [tinyproxy/tinyproxy#80]
Macbook Pro 15" Retina Late 2013, masOS 10.12.3

Downloaded and installed v1.8.4 through Homebrew, and followed the instructions here:
[https://gist.github.com/RobbieClarken/4743751](url)
(I swapped out all mentions of v1.8.3 and replaced them with v1.8.4.)

The proxy service works, but the log files are never created. Even when running `tinyproxy -d`, I don't get any errors that it can't find or manipulate the file. However, the files still don't appear. LogLevel is set to Info.

**Comment by rofl0r** [comment]
i suppose this issue should be opened on the homebrew repo, apparently they've misconfigured something.

**Comment by wputnam** [comment]
I've crossposted this to the Issue page for homebrew-core. For anyone else interested, here's the link: [https://github.com/Homebrew/homebrew-core/issues/10284](url)

**Comment by ilovezfs** [comment]
We configure it with
```
    args = %W[
      --disable-debug
      --disable-dependency-tracking
      --disable-silent-rules
      --prefix=#{prefix}
      --localstatedir=#{var}
      --sysconfdir=#{etc}
      --disable-regexcheck
    ]
```
Contrary to the gist above, the log location is /usr/local/var/log/tinyproxy/tinyproxy.log

In Homebrew
#{var} is /usr/local/var
#{etc} is /usr/local/etc
