### ISSUE TITLE
How to use tinyproxy in transparent mode

### ISSUE THREAD

**Issue by dailingngcom** [tinyproxy/tinyproxy#82]
I am using tinyproxy in a small system.
Now it worked if I configure the Browser manually: preference>advanced>net>
But I want it work in the transparent mode, which means don't need to configure the browser.
Does tinyproxy support this mode? I read "Tinyproxy supports being configured as a transparent proxy".
what I have done:
1. change the Makefile.am (delete docs in SUBDIR),so it can be compiled withtout asciidoc
2. ./configure --enable-transparent(I thought this will let tinyproxy work in the transparent mode, but it didn't really work)
3. run tinyproxy: tinyproxy -d
So what can I do? or I just missunderstand the meaning of transparent proxy.
thank U so much.

**Comment by dailingngcom** [comment]
I install the tinyproxy in the computer where I use browser.

**Comment by rofl0r** [comment]
you need to set up your firewall to redirect outgoing packets to port 80 to the proxy port.
usually you have the transparent proxy on your router, and you would configure the firewall as decribed here: http://www.tldp.org/HOWTO/TransparentProxy.html

**Comment by dailingngcom** [comment]
thanks so much，i will have a try！谢谢你！发自网易邮箱大师
            On 03/05/2017 22:53, rofl0r wrote: you need to set up your firewall to redirect outgoing packets to port 80 to the proxy port.
usually you have the transparent proxy on your router, and you would configure the firewall as decribed here: http://www.tldp.org/HOWTO/TransparentProxy.html

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tinyproxy/tinyproxy","title":"tinyproxy/tinyproxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tinyproxy/tinyproxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rofl0r in #82: you need to set up your firewall to redirect outgoing packets to port 80 to the proxy port.\r\nusually you have the transparent proxy on your router, and you would configure the firewall as decribed here: http://www.tldp.org/HOWTO/TransparentProxy.html"}],"action":{"name":"View Issue","url":"https://github.com/tinyproxy/tinyproxy/issues/82#issuecomment-284233005"}}}
