### ISSUE TITLE
tinyproxy with upstream ip/bits is not working

### ISSUE THREAD

**Issue by dytsiang** [tinyproxy/tinyproxy#83]
I installed tinyproxy 1.8.4 in centos with --enable-upstream option. I edited tinyproxy.conf with following line:
upstream 172.20.1.52:8208 "100.0.0.0/8"
upstream 172.20.1.52:8208 ".facebook.com"
I accessed "http://100.1.1.2" and "http://www.facebook.com" in browser via proxy.  Using the facebook url succeeded to upstream to 172.20.1.52。 But accessing 100.1.1.2 failed to upstream。
The tinyproxy log:
INFO      Mar 08 02:18:11 [22610]: Initializing tinyproxy ...
INFO      Mar 08 02:18:11 [22610]: Reloading config file
INFO      Mar 08 02:18:11 [22610]: Added upstream 172.20.1.52:8208 for 100.0.0.0/8
INFO      Mar 08 02:18:11 [22610]: Added upstream 172.20.1.52:8208 for .facebook.com
INFO      Mar 08 02:18:11 [22610]: Setting "Via" header to 'tinyproxy'
INFO      Mar 08 02:18:11 [22610]: Adding Port [443] to the list allowed by CONNECT
INFO      Mar 08 02:18:11 [22610]: Adding Port [563] to the list allowed by CONNECT
INFO      Mar 08 02:18:11 [22610]: listen_sock called with addr = '(NULL)'
INFO      Mar 08 02:18:11 [22610]: trying to listen on host[0.0.0.0], family[2], socktype[1], proto[6]
INFO      Mar 08 02:18:11 [22610]: listening on fd [4]
INFO      Mar 08 02:18:11 [22610]: trying to listen on host[::], family[10], socktype[1], proto[6]
INFO      Mar 08 02:18:11 [22610]: listening on fd [5]
CONNECT   Mar 08 02:18:25 [22618]: Connect (file descriptor 10): 161.152.243.43 [161.152.243.43]
CONNECT   Mar 08 02:18:25 [22618]: Request (file descriptor 10): GET http://100.1.1.2/ HTTP/1.1
INFO      Mar 08 02:18:25 [22618]: No upstream proxy for 100.1.1.2
CONNECT   Mar 08 02:25:02 [22615]: Connect (file descriptor 10): 161.152.243.43 [161.152.243.43]
CONNECT   Mar 08 02:25:02 [22615]: Request (file descriptor 10): CONNECT www.facebook.com:443 HTTP/1.1
INFO      Mar 08 02:25:02 [22615]: Found upstream proxy 172.20.1.52:8208 for www.facebook.com
CONNECT   Mar 08 02:25:02 [22615]: Established connection to upstream proxy "172.20.1.52" using file descriptor 11.
Something is wrong ？Thx。

**Comment by rofl0r** [comment]
do you own the 100.x.x.x class A subnet ? i doubt so. it looks as if you're mistaking `100.0.0.0` for `10.0.0.0' i.e. 100 vs 10.

**Comment by dytsiang** [comment]
100.0.0.0 is test subnet 。
I have changed to 114.92.181.0/24 for upstream 
INFO      Mar 08 07:00:07 [22717]: Initializing tinyproxy ...
INFO      Mar 08 07:00:07 [22717]: Reloading config file
INFO      Mar 08 07:00:07 [22717]: Added upstream 172.20.1.52:8208 for 114.92.181.0/24
INFO      Mar 08 07:00:07 [22717]: Added upstream 172.20.1.52:8208 for .facebook.com
INFO      Mar 08 07:00:07 [22717]: Setting "Via" header to 'tinyproxy'
INFO      Mar 08 07:00:07 [22717]: Adding Port [443] to the list allowed by CONNECT
INFO      Mar 08 07:00:07 [22717]: Adding Port [563] to the list allowed by CONNECT

CONNECT   Mar 08 07:00:40 [22728]: Request (file descriptor 10): GET http://114.92.181.68/ HTTP/1.1
INFO      Mar 08 07:00:40 [22728]: No upstream proxy for 114.92.181.68

**Comment by rofl0r** [comment]
> 100.0.0.0/8 is subnet of testing

that's a bug. you cannot use an ip adress range that is not defined for private usage for internal use and assume that it will work. it sometimes happen to work in practice, at least for a while. the ip ranges you can use for testing are 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. https://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces

**Comment by visago** [comment]
I'm having the same issues. On CentOS 7 with 1.8.3 (I even tried the latest git releases, same issue)

In my config..
`
upstream 192.168.1.2:8888 "10.0.0.0/8"
`

In the logs..

`
INFO      Aug 17 10:24:54 [75250]: Initializing tinyproxy ...
INFO      Aug 17 10:24:54 [75250]: Reloading config file
INFO      Aug 17 10:24:54 [75250]: Added upstream 192.168.1.2:8888 for 10.0.0.0/8
INFO      Aug 17 10:24:54 [75250]: Setting "Via" header to 'tinyproxy'
`
Then when i tried to access 10.x.x.x IPs,
`
CONNECT   Aug 17 10:25:03 [75251]: Request (file descriptor 6): GET http://10.72.1.18/ HTTP/1.1
INFO      Aug 17 10:25:03 [75251]: No upstream proxy for 10.72.1.18
`

I have tried variations of 10.72.0.0/16 or 10.0.0.0/255.255.255.0  or 10.72.0.0/255.255.0.0, it all don't work.
Setting a single IP of "10.72.1.18" fixes the issue, but I need to proxy for a certain segment only. Domain upstream works.

**Comment by Kalyan-Alamuru** [comment]
Guys, 

I tried setting up Tinyproxy to access Amazon EC2 Instance defined in Private Hosted Zone(with Domain defined in Google Cloud DNS, A record created with Domain defined in GC DNS with Public IP of Instance). I allowed ports 8888/443/563  and defined with Upstream as : DomainName :8888 linked to Public IP. Also Allowed Local Host and My IP in the Conf File. I'm getting following error.

"No Upstream for xxxxxxx.xxx(Which is my domain name) also I'm getting error opensock: Could not establish a connection to tiles.services.mozilla.com and  no entity.

Do you know how to resolve this??
