### ISSUE TITLE
Can tinyproxy work as a transparent https proxy?

### ISSUE THREAD

**Issue by yanggis** [tinyproxy/tinyproxy#88]
I know tinyproxy can work perfectly as a transparent http proxy, but when I failed to use tinyproxy works as a transparent https proxy by forwarding the HTTPS port to the HTTP port on the server:

iptables -t nat -A PREROUTING -p tcp –destination-port 443 -j REDIRECT –to-ports 80
However, I could not get correct https responses.

So, guys, please give a hand, anything I did wrong?

**Comment by hanxue** [comment]
No, tinyproxy does not support transparent HTTPS proxying. Only transparent HTTP proxy. Rerouting port 443 to port 80 will not work; those are two very different protocols. The only way is to manually set up proxy in the system/environment, or in the browser. 

If HTTPS transparent proxying is a must, consider using Squid.

**Comment by riturajtiwari** [comment]
@hanxue FYI: Transparent proxy does not necessarily work on Squid unless you do a man in the middle (MIM) setup where clients trust Squid's SSL cert.

**Comment by nihilus** [comment]
Indeed, transparent HTTPS proxying is usually done by using a cert to decrypt the traffic from/to the proxy and the reencrypt it against the target destination.

**Comment by yanggis** [comment]
search "goproxy" project on github, which can be used as a transparent https proxy server.

**Comment by rofl0r** [comment]
can you add a link @yanggis there are several "goproxy" on github.

**Comment by nihilus** [comment]
It should be npted that anything written in Go is the opposite to "tiny".

**Comment by nihilus** [comment]
@33d how is that supposed to be proxying? Seems like routing magic and not proxying per se.

**Comment by 33d** [comment]
My case was to transparently send HTTPS requests to an upstream proxy, like Tinyproxy already does with HTTP.
