### ISSUE TITLE
tinyproxy can not use `restart` to work by Ubuntu 16.04

### ISSUE THREAD

**Issue by shazi7804** [tinyproxy/tinyproxy#89]
I use EC2 run tinyproxy in AWS, but when use `restart` not work.

`sudo service tinyproxy restart`

The tinyproxy port number not working.

> $ ss -tunlp
> Netid  State      Recv-Q Send-Q      Local Address:Port                     Peer Address:Port
> udp    UNCONN     0      0                       *:68                                  *:*
> tcp    LISTEN     0      128                     *:22                                  *:*
> tcp    LISTEN     0      128                    :::22                                 :::*

But I can see deamon is active(running)

> ● tinyproxy.service - LSB: Tinyproxy HTTP proxy
>    Loaded: loaded (/etc/init.d/tinyproxy; bad; vendor preset: enabled)
>    Active: active (running) since Wed 2017-04-19 06:11:40 UTC; 18min ago

I think service stop did not finish the job at 1 sec

>   restart)
>         echo -n "Restarting $DESC: "
>         start-stop-daemon --stop --quiet -o --exec $DAEMON
>         sleep 1
>         start-stop-daemon --start --quiet -o --exec $DAEMON -- $FLAGS
>         echo "$NAME."
>         ;;

**Comment by rofl0r** [comment]
looks like a problem of your distribution's service supervision to me. i'm afraid it's not the job of the tinyproxy maintainer to check that all linux distribution have working service scripts.

**Comment by hus787** [comment]
Use CentOS. It fixed the problem for me.

**Comment by shazi7804** [comment]
@hus787 

OKAY

Maybe I need change use squid.

**Comment by obnoxxx** [comment]
@shazi7804 at least we would need more information about your system and logs in order to help understand and narrow it down...
