### ISSUE TITLE
unrecognized options: --enable-static

### ISSUE THREAD

**Issue by thomasdarimont** [tinyproxy/tinyproxy#90]
After downloading and extracting the latest `tinyproxy-1.8.4.tar.gz` I tried to configure tinyproxy as a statically compiled binary via:
```./configure --enable-static```

This resulted in the following error message at the end of the configure script:
```configure: WARNING: unrecognized options: --enable-static```

**Comment by rofl0r** [comment]
that's not an error, it's a warning.

**Comment by thomasdarimont** [comment]
You are technically correct ;-) But isn't it an error that the --enable-static option is not recognized? :)

**Comment by rofl0r** [comment]
not really. usually --enable-static is used to express the desire to build static libraries, and --enable-shared to build dynamic libraries. but in the case of tinyproxy, no libraries are built.
you probably meant to use the option to create a statically linked app, but that's not how it works. for that case you just add `-static` to your `LDFLAGS`, i.e. `LDFLAGS=-static ./configure ...`.

**Comment by rdpate** [comment]
Why is --enable-static mentioned by [README.md](https://github.com/tinyproxy/tinyproxy/blob/master/README.md#installation)?

**Comment by rofl0r** [comment]
well yes, that is indeed an error! would you mind to open a PR removing it? thanks!

**Comment by obnoxxx** [comment]
resolved via #100
