### ISSUE TITLE
Tinyproxy not tracing XMLHttpRequest type calls

### ISSUE THREAD

**Issue by praveensagarc** [tinyproxy/tinyproxy#91]
Hi,
I have installed tinyproxy in ubuntu to trace all http calls and append custom header for each http call going from that system. 

And i tried to make http call by using curl command and it is working fine and the header is also getting appended.
But when I execute some tests in chrome  browser, tinyproxy is not tracing requests od type XMLHttpRequests. 

I have seen tinyproxy logs but dint find any logs related to my XMLHttpRequest type call.

Can somebody help in setting of tinyproxy to trace out all kind of calls?

**Comment by rofl0r** [comment]
XMLHttpRequest's are usually done on an open connection (those with Connection: keep-alive). maybe that's why they dont show up in the log ? it's possible that only connection-establishment is logged, but i'm not sure.
