### ISSUE TITLE
The administrator of this proxy has not configured it to service requests from your host

### ISSUE THREAD

**Issue by richburdon** [tinyproxy/tinyproxy#92]
I'm trying to use tp as a reverse proxy but get the error.

Using a standard config (http://distro.ibiblio.org/tinycorelinux/3.x/tcz/src/tinyproxy/tinyproxy.conf) with:

````
ReversePath "/test/" "http://192.168.64.2:30058/"
ReverseOnly Yes
ReverseBaseURL "http://localhost:8888/"
````

I've also tried (both with and without)
````
Allow 127.0.0.1
````

`curl http://localhost:8888/test`

returns

`The administrator of this proxy has not configured it to service requests from your host`

**Comment by StianOvrevage** [comment]
Same here.

**Comment by rofl0r** [comment]
works for me using tinyproxy from git (master):
```
cp etc/tinyproxy.conf revproxy.conf
# append config lines
cat << EOF >> revproxy.conf
ReversePath "/test/"    "http://192.168.0.2:8000/"
ReverseOnly Yes
ReverseBaseURL "http://localhost:8888/"
EOF
src/tinyproxy -d -c revprox.conf

#second terminal
cd /tmp
python -m BasicHTTPServer
```
now opening `http://localhost:8888/test/` in the browser shows the directory listing of /tmp as expected.

**Comment by rofl0r** [comment]
assuming fixed.

**Comment by zhaizz** [comment]
Allow 127.0.0.1 注释掉，或者换成被代理的ip

**Comment by zhaizz** [comment]
> I'm trying to use tp as a reverse proxy but get the error.
> 
> Using a standard config (http://distro.ibiblio.org/tinycorelinux/3.x/tcz/src/tinyproxy/tinyproxy.conf) with:
> 
> ```
> ReversePath "/test/" "http://192.168.64.2:30058/"
> ReverseOnly Yes
> ReverseBaseURL "http://localhost:8888/"
> ```
> 
> I've also tried (both with and without)
> 
> ```
> Allow 127.0.0.1
> ```
> 
> `curl http://localhost:8888/test`
> 
> returns
> 
> `The administrator of this proxy has not configured it to service requests from your host`

1、注释掉Allow 127.0.0.1
2、Allow 127.0.0.1 换成被代理ip

**Comment by zhaizz** [comment]
1、注释掉 允许 127.0.0.1
2、允许 127.0.0.1 换成被代理IP

**Comment by zhaizz** [comment]
可以试试 注释Allow 127.0.0.1 或者改成真实被代理IP

**Comment by mihir-kumar-thakur** [comment]
Still facing the same issue

**Comment by rofl0r** [comment]
> Still facing the same issue

with which version ? also, try "/test/" as url, not "/test" (i.e. add a trailing slash)

**Comment by msglueck** [comment]
if you use: `Allow 127.0.0.1`
at least as a forward proxy you have to use: `curl --proxy 127.0.0.1:<proxyport> http://whatever.url`
so maybe add a second `Allow localhost`
