### ISSUE TITLE
Default gateway

### ISSUE THREAD

**Issue by 66Ton99** [tinyproxy/tinyproxy#93]
I have VPN which wrap all traffic. And I need to route Proxy traffic to specific gateway.
Is it possible?

**Comment by spectras** [comment]
Yes it is, but that's something you do at the OS level, perhaps even the firewall level depending on your specific setup. It's unrelated to tinyproxy itself.

**Comment by 66Ton99** [comment]
I have configured routs in the system but how can I configure TinyProxy to connect specific IP? In my case getaway.
It looks like Bind option works only with local Ethernet Interfaces. As I understood it is possible to create virtual Ethernet Interface and configure TinyProxy to use it but is not applicable way.

**Comment by spectras** [comment]
Routing is not related to tinyproxy, so you won't find any option in tinyproxy for this. You must look at you os level. For instance, under Linux this is done using a combination of routes and iptables rules.
A starting point could be this: https://stackoverflow.com/questions/5231279/iptables-forward-specific-port-to-specific-nic

**Comment by 66Ton99** [comment]
Thanks.
