### ISSUE TITLE
Run as normal proxy

### ISSUE THREAD

**Issue by ppanero** [tinyproxy/tinyproxy#98]
I want to run tinyproxy as a simple proxy. I set the bind and the listen ip, etc. however when I run I get:
```"Bind" cannot be used with transparent support enabled. ``` (PR exsistent)
which in any case is not what I want because I just want it to run as a normal proxy: not transparent, not reverse...

**Comment by rofl0r** [comment]
fixed by https://github.com/tinyproxy/tinyproxy/commit/09979629c03ae237617e7142594b5b9508be24a9
